<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseAppHost>false</UseAppHost>
  </PropertyGroup>

  <ItemGroup>
	  <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
	  <PackageReference Include="DevExpress.AspNetCore.Reporting" Version="24.1.5" />
	  <PackageReference Include="log4net" Version="3.3.2" />
	  <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="3.1.2" />
	  <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.9" />
	  <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.9" />
	  <PackageReference Include="OpenTelemetry.Api" Version="1.16.0" />
	  <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.9" />
	  <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.19.1" />
  </ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\EG.Application\EG.Application.csproj" />
		<ProjectReference Include="..\EG.Common\EG.Common.csproj" />
		<ProjectReference Include="..\EG.Logger\EG.Logger.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Controllers\Platform\" />
	  <Folder Include="Controllers\Modules\GRP\Catalogos\Tesoreria\" />
	</ItemGroup>

	<ItemGroup>
	  <Content Include="Reporting\ExportedXml\**\*.repx" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
	  <Content Include="..\EG.Logger\log4net.config" Link="log4net.config" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
	</ItemGroup>

</Project>
