// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace EG.Dommain.DTOs.Responses;


public class UsuarioDto
{
    public int PkIdUsuario { get; set; }

    public int FkidEmpresaSis { get; set; }

    public string Nombre { get; set; }

    public string ApellidoPaterno { get; set; }

    public string ApellidoMaterno { get; set; }

    public string Iniciales { get; set; }

    public string PayrollId { get; set; }

    public string CodigoPostal { get; set; }

    public string Telefono { get; set; }

    public string Direccion1 { get; set; }

    public string Direccion2 { get; set; }

    public string Email { get; set; }

    public string NumeroSocial { get; set; }

    public string Gafete { get; set; }

    public bool Sexo { get; set; }

    public bool Activo { get; set; }
}


public class FotografiaUsuarioDto
{
    public int FkidUsuarioSis { get; set; }

    public byte[] Fotografia { get; set; }

    public string ContentType { get; set; }

    public string FileName { get; set; }

    public string FileExtension { get; set; }

    public bool Activo { get; set; }

}



