using AutoMapper;
using EG.Domain.Entities;
using EG.Dommain.DTOs.Responses;

namespace EG.Business.Mapping.Entidades
{
    public class UsuarioMappingProfile : Profile
    {
        public UsuarioMappingProfile()
        {
            // ✅ CORRECTO - Mapeo directo de la vista al Response
            CreateMap<VwUsuarioSucursal, UsuarioResponse>()
                .ForMember(dest => dest.PkIdUsuario, opt => opt.MapFrom(src => src.PkIdUsuario))
                .ForMember(dest => dest.IdEmpresa, opt => opt.MapFrom(src => src.IdEmpresa))
                .ForMember(dest => dest.NombreEmpresa, opt => opt.MapFrom(src => src.NombreEmpresa))
                .ForMember(dest => dest.RfcEmpresa, opt => opt.MapFrom(src => src.RfcEmpresa))
                .ForMember(dest => dest.NombreCompleto, opt => opt.MapFrom(src => src.NombreCompleto))
                .ForMember(dest => dest.NombreUsuario, opt => opt.MapFrom(src => src.NombreUsuario))
                .ForMember(dest => dest.ApellidoPaterno, opt => opt.MapFrom(src => src.ApellidoPaterno))
                .ForMember(dest => dest.ApellidoMaterno, opt => opt.MapFrom(src => src.ApellidoMaterno))
                .ForMember(dest => dest.Iniciales, opt => opt.MapFrom(src => src.Iniciales))
                .ForMember(dest => dest.PayrollId, opt => opt.MapFrom(src => src.PayrollId))
                .ForMember(dest => dest.CodigoPostalUsuario, opt => opt.MapFrom(src => src.CodigoPostalUsuario))
                .ForMember(dest => dest.TelefonoUsuario, opt => opt.MapFrom(src => src.TelefonoUsuario))
                .ForMember(dest => dest.Direccion1, opt => opt.MapFrom(src => src.Direccion1))
                .ForMember(dest => dest.Direccion2, opt => opt.MapFrom(src => src.Direccion2))
                .ForMember(dest => dest.Email, opt => opt.MapFrom(src => src.Email))
                .ForMember(dest => dest.NumeroSocial, opt => opt.MapFrom(src => src.NumeroSocial))
                .ForMember(dest => dest.Gafete, opt => opt.MapFrom(src => src.Gafete))
                .ForMember(dest => dest.SexoDescripcion, opt => opt.MapFrom(src => src.SexoDescripcion))
                .ForMember(dest => dest.Sexo, opt => opt.MapFrom(src => src.Sexo))
                .ForMember(dest => dest.UsuarioActivo, opt => opt.MapFrom(src => src.UsuarioActivo))
                .ForMember(dest => dest.UsuarioFechaCreacion, opt => opt.MapFrom(src => src.UsuarioFechaCreacion))
                .ForMember(dest => dest.UsuarioCreadorId, opt => opt.MapFrom(src => src.UsuarioCreadorId))
                .ForMember(dest => dest.PkidSucursal, opt => opt.MapFrom(src => src.PkidSucursal))
                .ForMember(dest => dest.NombreSucursal, opt => opt.MapFrom(src => src.NombreSucursal))
                .ForMember(dest => dest.CodigoSucursal, opt => opt.MapFrom(src => src.CodigoSucursal))
                .ForMember(dest => dest.AliasSucursal, opt => opt.MapFrom(src => src.AliasSucursal))
                .ForMember(dest => dest.TipoSucursal, opt => opt.MapFrom(src => src.TipoSucursal))
                .ForMember(dest => dest.TipoSucursalDescripcion, opt => opt.MapFrom(src => src.TipoSucursalDescripcion))
                .ForMember(dest => dest.DireccionSucursal, opt => opt.MapFrom(src => src.DireccionSucursal))
                .ForMember(dest => dest.Colonia, opt => opt.MapFrom(src => src.Colonia))
                .ForMember(dest => dest.Ciudad, opt => opt.MapFrom(src => src.Ciudad))
                .ForMember(dest => dest.CodigoPostalSucursal, opt => opt.MapFrom(src => src.CodigoPostalSucursal))
                .ForMember(dest => dest.TelefonoPrincipal, opt => opt.MapFrom(src => src.TelefonoPrincipal))
                .ForMember(dest => dest.TelefonoSecundario, opt => opt.MapFrom(src => src.TelefonoSecundario))
                .ForMember(dest => dest.EmailSucursal, opt => opt.MapFrom(src => src.EmailSucursal))
                .ForMember(dest => dest.HorarioApertura, opt => opt.MapFrom(src => src.HorarioApertura))
                .ForMember(dest => dest.HorarioCierre, opt => opt.MapFrom(src => src.HorarioCierre))
                .ForMember(dest => dest.EsMatriz, opt => opt.MapFrom(src => src.EsMatriz))
                .ForMember(dest => dest.TipoSucursalLabel, opt => opt.MapFrom(src => src.TipoSucursalLabel))
                .ForMember(dest => dest.EsActiva, opt => opt.MapFrom(src => src.EsActiva))
                .ForMember(dest => dest.Latitud, opt => opt.MapFrom(src => src.Latitud))
                .ForMember(dest => dest.Longitud, opt => opt.MapFrom(src => src.Longitud))
                .ForMember(dest => dest.MetrosCuadrados, opt => opt.MapFrom(src => src.MetrosCuadrados))
                .ForMember(dest => dest.CapacidadPersonas, opt => opt.MapFrom(src => src.CapacidadPersonas))
                .ForMember(dest => dest.SucursalActivo, opt => opt.MapFrom(src => src.SucursalActivo))
                .ForMember(dest => dest.PkidEstado, opt => opt.MapFrom(src => src.PkidEstado))
                .ForMember(dest => dest.NombreEstado, opt => opt.MapFrom(src => src.NombreEstado))
                .ForMember(dest => dest.IdDepartamento, opt => opt.MapFrom(src => src.IdDepartamento))
                .ForMember(dest => dest.NombreDepartamento, opt => opt.MapFrom(src => src.NombreDepartamento))
                .ForMember(dest => dest.EsGerente, opt => opt.MapFrom(src => src.EsGerente))
                .ForMember(dest => dest.EsSupervisor, opt => opt.MapFrom(src => src.EsSupervisor))
                .ForMember(dest => dest.PuedeAcceder, opt => opt.MapFrom(src => src.PuedeAcceder))
                .ForMember(dest => dest.PuedeConfigurar, opt => opt.MapFrom(src => src.PuedeConfigurar))
                .ForMember(dest => dest.PuedeOperar, opt => opt.MapFrom(src => src.PuedeOperar))
                .ForMember(dest => dest.PuedeReportes, opt => opt.MapFrom(src => src.PuedeReportes))
                .ForMember(dest => dest.FechaAsignacion, opt => opt.MapFrom(src => src.FechaAsignacion))
                .ForMember(dest => dest.FechaFinAsignacion, opt => opt.MapFrom(src => src.FechaFinAsignacion))
                .ForMember(dest => dest.RelacionActiva, opt => opt.MapFrom(src => src.RelacionActiva))
                .ForMember(dest => dest.RolUsuario, opt => opt.MapFrom(src => src.RolUsuario))
                .ForMember(dest => dest.NivelAcceso, opt => opt.MapFrom(src => src.NivelAcceso));

            // Mapeo de Request a Entity (para operaciones de escritura)
            CreateMap<UsuarioDto, Usuario>()
                .ForMember(dest => dest.PkIdUsuario, opt => opt.Ignore())
                .ForMember(dest => dest.FechaCreacion, opt => opt.Ignore())
                .ForMember(dest => dest.FechaModificacion, opt => opt.Ignore())
                .ForMember(dest => dest.AspNetUsers, opt => opt.Ignore())
                .ForMember(dest => dest.PerfilUsuario, opt => opt.Ignore())
                .ForMember(dest => dest.UsuarioSucursals, opt => opt.Ignore())
                .ForMember(dest => dest.FkidEmpresaSisNavigation, opt => opt.Ignore());

            // Si necesitas mapear desde VwUsuarioSucursal a UsuarioDto para operaciones de actualización
            CreateMap<VwUsuarioSucursal, UsuarioDto>()
                .ForMember(dest => dest.PkIdUsuario, opt => opt.MapFrom(src => src.PkIdUsuario))
                .ForMember(dest => dest.FkidEmpresaSis, opt => opt.MapFrom(src => src.IdEmpresa))
                .ForMember(dest => dest.Nombre, opt => opt.MapFrom(src => src.NombreUsuario))
                .ForMember(dest => dest.ApellidoPaterno, opt => opt.MapFrom(src => src.ApellidoPaterno))
                .ForMember(dest => dest.ApellidoMaterno, opt => opt.MapFrom(src => src.ApellidoMaterno))
                .ForMember(dest => dest.Iniciales, opt => opt.MapFrom(src => src.Iniciales))
                .ForMember(dest => dest.PayrollId, opt => opt.MapFrom(src => src.PayrollId))
                .ForMember(dest => dest.CodigoPostal, opt => opt.MapFrom(src => src.CodigoPostalUsuario))
                .ForMember(dest => dest.Telefono, opt => opt.MapFrom(src => src.TelefonoUsuario))
                .ForMember(dest => dest.Direccion1, opt => opt.MapFrom(src => src.Direccion1))
                .ForMember(dest => dest.Direccion2, opt => opt.MapFrom(src => src.Direccion2))
                .ForMember(dest => dest.Email, opt => opt.MapFrom(src => src.Email))
                .ForMember(dest => dest.NumeroSocial, opt => opt.MapFrom(src => src.NumeroSocial))
                .ForMember(dest => dest.Gafete, opt => opt.MapFrom(src => src.Gafete))
                .ForMember(dest => dest.Sexo, opt => opt.MapFrom(src => src.Sexo))
                .ForMember(dest => dest.Activo, opt => opt.MapFrom(src => src.UsuarioActivo))
                .ForMember(dest => dest.FechaCreacion, opt => opt.MapFrom(src => src.UsuarioFechaCreacion))
                .ForMember(dest => dest.UsuarioCreacion, opt => opt.MapFrom(src => src.UsuarioCreadorId));
        }
    }
}