// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class AlertaConfig
{
    public int PkidAlertaConfig { get; set; }

    public int FkidProgramaPresupuestarioPbr { get; set; }

    public int? FkidIndicadorPbr { get; set; }

    public string Nombre { get; set; }

    public string Tipo { get; set; }

    public decimal Umbral { get; set; }

    public string Direccion { get; set; }

    public bool Activa { get; set; }

    public DateTime? UltimaRevision { get; set; }

    public DateTime FechaCreacion { get; set; }

    public DateTime? FechaModificacion { get; set; }
}