// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class Anio
{
    public int PkidAnio { get; set; }

    public int Clave { get; set; }

    public bool Activo { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public int UsuarioCreacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public int? UsuarioModificacion { get; set; }

    public virtual ICollection<Almacen> Almacens { get; set; } = new List<Almacen>();

    public virtual ICollection<Baja> Bajas { get; set; } = new List<Baja>();

    public virtual ICollection<CierreInventario> CierreInventarios { get; set; } = new List<CierreInventario>();

    public virtual ICollection<ConsecutivoPoliza> ConsecutivoPolizas { get; set; } = new List<ConsecutivoPoliza>();

    public virtual ICollection<Cotizacion> Cotizacions { get; set; } = new List<Cotizacion>();

    public virtual ICollection<EstudioMercado> EstudioMercados { get; set; } = new List<EstudioMercado>();

    public virtual ICollection<IngreAdecuacion> IngreAdecuacions { get; set; } = new List<IngreAdecuacion>();

    public virtual ICollection<MatrizConversion> MatrizConversions { get; set; } = new List<MatrizConversion>();

    public virtual ICollection<MatrizIngreso> MatrizIngresos { get; set; } = new List<MatrizIngreso>();

    public virtual ICollection<Paaa> Paaas { get; set; } = new List<Paaa>();

    public virtual ICollection<Poliza> Polizas { get; set; } = new List<Poliza>();

    public virtual ICollection<Programa> Programas { get; set; } = new List<Programa>();

    public virtual ICollection<Requisicion> Requisicions { get; set; } = new List<Requisicion>();

    public virtual ICollection<SolicitudSalidum> SolicitudSalida { get; set; } = new List<SolicitudSalidum>();

    public virtual Usuario UsuarioCreacionNavigation { get; set; }

    public virtual Usuario UsuarioModificacionNavigation { get; set; }
}