// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class Area
{
    public int PkidArea { get; set; }

    public int? FkidAreaSis { get; set; }

    public int? FkidAreaDoctoSis { get; set; }

    public string Clave { get; set; }

    public string Nombre { get; set; }

    public DateTime? UltimoInv { get; set; }

    public string ZonaEconomica { get; set; }

    public string Direccion { get; set; }

    public string Colonia { get; set; }

    public string Cp { get; set; }

    public string Telefono { get; set; }

    public bool Aprovado { get; set; }

    public bool Activo { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public int UsuarioCreacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public int? UsuarioModificacion { get; set; }

    public virtual ICollection<Bien> Biens { get; set; } = new List<Bien>();

    public virtual ICollection<EgresoAutorizado> EgresoAutorizados { get; set; } = new List<EgresoAutorizado>();

    public virtual ICollection<EgresoProyectado> EgresoProyectados { get; set; } = new List<EgresoProyectado>();

    public virtual Area FkidAreaSisNavigation { get; set; }

    public virtual ICollection<Area> InverseFkidAreaSisNavigation { get; set; } = new List<Area>();

    public virtual ICollection<Paaa> Paaas { get; set; } = new List<Paaa>();

    public virtual ICollection<PersonaArea> PersonaAreas { get; set; } = new List<PersonaArea>();

    public virtual ICollection<Requisicion> Requisicions { get; set; } = new List<Requisicion>();

    public virtual Usuario UsuarioCreacionNavigation { get; set; }

    public virtual Usuario UsuarioModificacionNavigation { get; set; }
}