// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class Asm
{
    public int PkidAsm { get; set; }

    public int FkidEvaluacionPbr { get; set; }

    public string Titulo { get; set; }

    public string Descripcion { get; set; }

    public string Prioridad { get; set; }

    public string TipoAsm { get; set; }

    public DateTime? FechaTermino { get; set; }

    public string ResultadoEsperado { get; set; }

    public int Avance { get; set; }

    public string Estado { get; set; }

    public int FkidResponsablePbr { get; set; }

    public string Observaciones { get; set; }

    public string Evidencia { get; set; }

    public string AccionesPamge { get; set; }

    public DateTime FechaCreacion { get; set; }

    public DateTime? FechaModificacion { get; set; }
}