// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class CierreInventario
{
    public int PkidCierreInventario { get; set; }

    public int FkidEmpresaSis { get; set; }

    public int FkidAnioSis { get; set; }

    public int FkidTipoBienAlma { get; set; }

    public int? FkidUnidadesAlma { get; set; }

    public byte Mes { get; set; }

    public decimal Existencias { get; set; }

    public decimal? CostoExistencias { get; set; }

    public decimal? CostoPromedio { get; set; }

    public bool Activo { get; set; }

    public DateTime FechaCreacion { get; set; }

    public int UsuarioCreacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public int? UsuarioModificacion { get; set; }

    public virtual Anio FkidAnioSisNavigation { get; set; }

    public virtual Empresa FkidEmpresaSisNavigation { get; set; }

    public virtual TipoBien FkidTipoBienAlmaNavigation { get; set; }

    public virtual Unidade FkidUnidadesAlmaNavigation { get; set; }
}