// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class Clc
{
    public int PkidClc { get; set; }

    public int FkidEmpresaSis { get; set; }

    public int FkidContratoPres { get; set; }

    public int FkidPolizaConta { get; set; }

    public string NumClc { get; set; }

    public DateOnly FechaSolicitud { get; set; }

    public DateOnly? FechaAutorizacion { get; set; }

    public decimal ImporteTotal { get; set; }

    public string Observaciones { get; set; }

    public int Estatus { get; set; }

    public bool Activo { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public int UsuarioCreacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public int? UsuarioModificacion { get; set; }

    public virtual ICollection<Cheque> Cheques { get; set; } = new List<Cheque>();

    public virtual ICollection<Clcdetalle> Clcdetalles { get; set; } = new List<Clcdetalle>();

    public virtual ICollection<Clcfactura> Clcfacturas { get; set; } = new List<Clcfactura>();

    public virtual Contrato1 FkidContratoPresNavigation { get; set; }

    public virtual Empresa FkidEmpresaSisNavigation { get; set; }

    public virtual Poliza FkidPolizaContaNavigation { get; set; }

    public virtual Usuario UsuarioCreacionNavigation { get; set; }

    public virtual Usuario UsuarioModificacionNavigation { get; set; }
}