// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class Clcfactura
{
    public int PkidClcfactura { get; set; }

    public int FkidEmpresaSis { get; set; }

    public int FkidClcPres { get; set; }

    public int FkidFacturaPres { get; set; }

    public int FkidFacturaDetallePres { get; set; }

    public decimal MontoAplicado { get; set; }

    public string Observaciones { get; set; }

    public bool Activo { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public int UsuarioCreacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public int? UsuarioModificacion { get; set; }

    public virtual Clc FkidClcPresNavigation { get; set; }

    public virtual Empresa FkidEmpresaSisNavigation { get; set; }

    public virtual FacturaDetalle FkidFacturaDetallePresNavigation { get; set; }

    public virtual Factura FkidFacturaPresNavigation { get; set; }

    public virtual Usuario UsuarioCreacionNavigation { get; set; }

    public virtual Usuario UsuarioModificacionNavigation { get; set; }
}