// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class ContratoDetalle
{
    public int PkidContratoDetalle { get; set; }

    public int FkidEmpresaSis { get; set; }

    public int FkidContratoPres { get; set; }

    public int FkidAutorizacionSuficienciaDetallePres { get; set; }

    public int FkidPartidaConta { get; set; }

    public decimal? Enero { get; set; }

    public decimal? Febrero { get; set; }

    public decimal? Marzo { get; set; }

    public decimal? Abril { get; set; }

    public decimal? Mayo { get; set; }

    public decimal? Junio { get; set; }

    public decimal? Julio { get; set; }

    public decimal? Agosto { get; set; }

    public decimal? Septiembre { get; set; }

    public decimal? Octubre { get; set; }

    public decimal? Noviembre { get; set; }

    public decimal? Diciembre { get; set; }

    public decimal? Total { get; set; }

    public string Observaciones { get; set; }

    public bool Activo { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public int UsuarioCreacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public int? UsuarioModificacion { get; set; }

    public virtual ICollection<Clcdetalle> Clcdetalles { get; set; } = new List<Clcdetalle>();

    public virtual ICollection<FacturaDetalle> FacturaDetalles { get; set; } = new List<FacturaDetalle>();

    public virtual AutorizacionSuficienciaDetalle FkidAutorizacionSuficienciaDetallePresNavigation { get; set; }

    public virtual Contrato FkidContratoPresNavigation { get; set; }

    public virtual Empresa FkidEmpresaSisNavigation { get; set; }

    public virtual Partidum FkidPartidaContaNavigation { get; set; }

    public virtual Usuario UsuarioCreacionNavigation { get; set; }

    public virtual Usuario UsuarioModificacionNavigation { get; set; }
}