// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class CorridaNomina
{
    public int PkidCorridaNomina { get; set; }

    public int FkidEmpresaSis { get; set; }

    public int IdPeriodo { get; set; }

    public int? Anio { get; set; }

    public string TipoCorrida { get; set; }

    public string Estatus { get; set; }

    public DateOnly FechaProceso { get; set; }

    public string Observaciones { get; set; }

    public int TotalPersonas { get; set; }

    public int TotalMovimientos { get; set; }

    public decimal TotalPercepcion { get; set; }

    public decimal TotalDeduccion { get; set; }

    public decimal TotalAportacion { get; set; }

    public decimal TotalNeto { get; set; }

    public int? UsuarioCreacion { get; set; }

    public DateTime FechaCreacion { get; set; }

    public int? UsuarioModificacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public bool Activo { get; set; }

    public int? FkidEmpresaNominaNom { get; set; }

    public virtual ICollection<CorridaNominaDetalle> CorridaNominaDetalles { get; set; } = new List<CorridaNominaDetalle>();

    public virtual Empresa FkidEmpresaSisNavigation { get; set; }
}