// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class Credito
{
    public int PkidCredito { get; set; }

    public int FkidPersonaNom { get; set; }

    public int FkidContratoTerceroNom { get; set; }

    public string MotivoCredito { get; set; }

    public decimal ImporteCredito { get; set; }

    public decimal TasaInteres { get; set; }

    public int NumeroPagos { get; set; }

    public int FkidPeriodoInicial { get; set; }

    public decimal ImportePago { get; set; }

    public int? UsuarioCreacion { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public int? UsuarioModificacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public bool Activo { get; set; }
}