// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class Cri
{
    public int Id { get; set; }

    public string Codigo { get; set; }

    public string Nombre { get; set; }

    public string Rubro { get; set; }

    public string Tipo { get; set; }

    public string Clase { get; set; }

    public string Concepto { get; set; }

    public bool Activo { get; set; }

    public DateTime FechaCreacion { get; set; }
}