// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class CuentaContable
{
    public int PkidCuentaContable { get; set; }

    public int FkidEmpresaSis { get; set; }

    public int FkidTipoCuentaConta { get; set; }

    public string Cuenta { get; set; }

    public string SubCuenta { get; set; }

    public string SubSubCuenta { get; set; }

    public string SubSubSubCuenta { get; set; }

    public string SubSubSubSubCuenta { get; set; }

    public decimal Saldo { get; set; }

    public string Descripcion { get; set; }

    public bool Activo { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public int UsuarioCreacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public int? UsuarioModificacion { get; set; }

    public string S5 { get; set; }

    public string S6 { get; set; }

    public string S7 { get; set; }

    public string ClaveOrd { get; set; }

    public string Padre { get; set; }

    public string Hijo { get; set; }

    public int? NivelCuenta { get; set; }

    public string CtaCoi { get; set; }

    public string DescCoi { get; set; }

    public string TipoCuenta { get; set; }

    public string S8 { get; set; }

    public string S9 { get; set; }

    public string S10 { get; set; }

    public int IsCuentaDetalle { get; set; }

    public virtual Empresa FkidEmpresaSisNavigation { get; set; }

    public virtual TipoCuentum FkidTipoCuentaContaNavigation { get; set; }

    public virtual ICollection<TipoBien> TipoBiens { get; set; } = new List<TipoBien>();
}