// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class DetalleSolicitudSalidum
{
    public int PkidDetalleSolicitudSalida { get; set; }

    public int FkidSolicitudSalidaAlma { get; set; }

    public int? FkidAlmacenAlma { get; set; }

    public int FkidTipoBienAlma { get; set; }

    public int? FkidUnidadesAlma { get; set; }

    public decimal CantidadSolicitada { get; set; }

    public decimal? CantidadAutorizada { get; set; }

    public decimal? CantidadEntregada { get; set; }

    public decimal CantidadPendiente { get; set; }

    public string Observaciones { get; set; }

    public bool Activo { get; set; }

    public DateTime FechaCreacion { get; set; }

    public int UsuarioCreacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public int? UsuarioModificacion { get; set; }

    public virtual Almacen FkidAlmacenAlmaNavigation { get; set; }

    public virtual SolicitudSalidum FkidSolicitudSalidaAlmaNavigation { get; set; }

    public virtual TipoBien FkidTipoBienAlmaNavigation { get; set; }
}