// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class Diagnostico
{
    public int PkidDiagnostico { get; set; }

    public int FkidProgramaPresupuestarioPbr { get; set; }

    public string ProblemaCentral { get; set; }

    public string Metodologia { get; set; }

    public string Estado { get; set; }

    public DateTime FechaCreacion { get; set; }

    public DateTime? FechaModificacion { get; set; }
}