// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class DocumentoAnotacion
{
    public long PkidDocumentoAnotacion { get; set; }

    public long FkidDocumento { get; set; }

    public int FkidDocumentoTipoAnotacion { get; set; }

    public string Comentario { get; set; }

    public string TextoSeleccionado { get; set; }

    public int? Pagina { get; set; }

    public decimal? PosicionX { get; set; }

    public decimal? PosicionY { get; set; }

    public decimal? Ancho { get; set; }

    public decimal? Alto { get; set; }

    public string Color { get; set; }

    public bool Activo { get; set; }

    public int CtCreatedBy { get; set; }

    public DateTime CtCreatedDate { get; set; }

    public int? CtModifiedBy { get; set; }

    public DateTime? CtModifiedDate { get; set; }

    public byte[] RowVersion { get; set; }

    public virtual Documento FkidDocumentoNavigation { get; set; }

    public virtual DocumentoTipoAnotacion FkidDocumentoTipoAnotacionNavigation { get; set; }
}