// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class Documento
{
    public long PkidDocumento { get; set; }

    public string Modulo { get; set; }

    public string SubModulo { get; set; }

    public string Controlador { get; set; }

    public string Servicio { get; set; }

    public long EntidadId { get; set; }

    public int? FkidEmpresaSis { get; set; }

    public string Titulo { get; set; }

    public string Descripcion { get; set; }

    public string NombreOriginal { get; set; }

    public string NombreAlmacenado { get; set; }

    public string Extension { get; set; }

    public string TipoMime { get; set; }

    public long TamanoBytes { get; set; }

    public string ModoAlmacenamiento { get; set; }

    public byte[] ContenidoArchivo { get; set; }

    public string RutaRelativa { get; set; }

    public byte[] HashSha256 { get; set; }

    public int VersionDocumento { get; set; }

    public bool EsImagen { get; set; }

    public bool EsPdf { get; set; }

    public bool Activo { get; set; }

    public int CtCreatedBy { get; set; }

    public DateTime CtCreatedDate { get; set; }

    public int? CtModifiedBy { get; set; }

    public DateTime? CtModifiedDate { get; set; }

    public byte[] RowVersion { get; set; }

    public virtual ICollection<DocumentoAnotacion> DocumentoAnotacions { get; set; } = new List<DocumentoAnotacion>();

    public virtual ICollection<DocumentoEvento> DocumentoEventos { get; set; } = new List<DocumentoEvento>();
}