// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class DocumentoEvento
{
    public long PkidDocumentoEvento { get; set; }

    public long FkidDocumento { get; set; }

    public string Evento { get; set; }

    public string Comentario { get; set; }

    public int CtCreatedBy { get; set; }

    public DateTime CtCreatedDate { get; set; }

    public virtual Documento FkidDocumentoNavigation { get; set; }
}