// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class DocumentoTipoAnotacion
{
    public int PkidDocumentoTipoAnotacion { get; set; }

    public string Clave { get; set; }

    public string Descripcion { get; set; }

    public bool Activo { get; set; }

    public int? CtCreatedBy { get; set; }

    public DateTime CtCreatedDate { get; set; }

    public virtual ICollection<DocumentoAnotacion> DocumentoAnotacions { get; set; } = new List<DocumentoAnotacion>();
}