// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using EG.Domain.Entities;
using Microsoft.EntityFrameworkCore;

namespace EG.Infraestructure.Models;

public partial class EGestionContext : DbContext
{
    public EGestionContext(DbContextOptions<EGestionContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AspNetClaim> AspNetClaims { get; set; }

    public virtual DbSet<AspNetClaimType> AspNetClaimTypes { get; set; }

    public virtual DbSet<AspNetClaimValue> AspNetClaimValues { get; set; }

    public virtual DbSet<AspNetRole> AspNetRoles { get; set; }

    public virtual DbSet<AspNetUser> AspNetUsers { get; set; }

    public virtual DbSet<AspNetUserRole> AspNetUserRoles { get; set; }

    public virtual DbSet<CatTipoSucursal> CatTipoSucursals { get; set; }

    public virtual DbSet<Departamento> Departamentos { get; set; }

    public virtual DbSet<Empresa> Empresas { get; set; }

    public virtual DbSet<EmpresaEstado> EmpresaEstados { get; set; }

    public virtual DbSet<Estado> Estados { get; set; }

    public virtual DbSet<Idioma> Idiomas { get; set; }

    public virtual DbSet<Menu> Menus { get; set; }

    public virtual DbSet<MenuRole> MenuRoles { get; set; }

    public virtual DbSet<Monedum> Moneda { get; set; }

    public virtual DbSet<OrigenLogMessage> OrigenLogMessages { get; set; }

    public virtual DbSet<Paise> Paises { get; set; }

    public virtual DbSet<PerfilUsuario> PerfilUsuarios { get; set; }

    public virtual DbSet<Sucursal> Sucursals { get; set; }

    public virtual DbSet<SystemLog> SystemLogs { get; set; }

    public virtual DbSet<SystemParamCatalog> SystemParamCatalogs { get; set; }

    public virtual DbSet<SystemParamValue> SystemParamValues { get; set; }

    public virtual DbSet<Usuario> Usuarios { get; set; }

    public virtual DbSet<UsuarioDepartamento> UsuarioDepartamentos { get; set; }

    public virtual DbSet<UsuarioSucursal> UsuarioSucursals { get; set; }

    public virtual DbSet<VwEmpresaDepartamanto> VwEmpresaDepartamantos { get; set; }

    public virtual DbSet<VwEstadoEmpresa> VwEstadoEmpresas { get; set; }

    public virtual DbSet<VwMenu> VwMenus { get; set; }

    public virtual DbSet<VwSucursalEmpresaEstado> VwSucursalEmpresaEstados { get; set; }

    public virtual DbSet<VwUsuarioEmpresa> VwUsuarioEmpresas { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AspNetClaim>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("CONSTRAINT_PK_AspNetClaims");

            entity.Property(e => e.Code).HasMaxLength(10);
            entity.Property(e => e.Created).HasColumnType("datetime");
            entity.Property(e => e.Description).HasMaxLength(200);
            entity.Property(e => e.Group).HasMaxLength(100);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(150);
            entity.Property(e => e.ReferenceId).HasAnnotation("Relational:DefaultConstraintName", "CONSTRAINT_DF_AspNetClaims_ReferenceId");
            entity.Property(e => e.RoleId).HasMaxLength(128);
            entity.Property(e => e.SubGroup).HasMaxLength(100);
            entity.Property(e => e.TokenFormat).HasMaxLength(50);
            entity.Property(e => e.Values).IsUnicode(false);

            entity.HasOne(d => d.ClaimType).WithMany(p => p.AspNetClaims)
                .HasForeignKey(d => d.ClaimTypeId)
                .HasConstraintName("CONSTRAINT_FK_AspNetClaims_ClaimType");

            entity.HasOne(d => d.Role).WithMany(p => p.AspNetClaims)
                .HasForeignKey(d => d.RoleId)
                .HasConstraintName("CONSTRAINT_FK_AspNetClaims_Role");
        });

        modelBuilder.Entity<AspNetClaimType>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("CONSTRAINT_PK_AspNetClaimTypes");

            entity.Property(e => e.Created).HasColumnType("datetime");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<AspNetClaimValue>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("CONSTRAINT_PK_AspNetClaimValues");

            entity.Property(e => e.Created)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "CONSTRAINT_DF_AspNetClaimValues_Created")
                .HasColumnType("datetime");
            entity.Property(e => e.Value)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.Claim).WithMany(p => p.AspNetClaimValues)
                .HasForeignKey(d => d.ClaimId)
                .HasConstraintName("CONSTRAINT_FK_AspNetClaimValues_Claim");
        });

        modelBuilder.Entity<AspNetRole>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("CONSTRAINT_PK_AspNetRoles");

            entity.HasIndex(e => e.Name, "CONSTRAINT_UX_AspNetRoles_Name").IsUnique();

            entity.Property(e => e.Id).HasMaxLength(128);
            entity.Property(e => e.Code).HasMaxLength(10);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(256);
        });

        modelBuilder.Entity<AspNetUser>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("CONSTRAINT_PK_AspNetUsers");

            entity.Property(e => e.Id).HasMaxLength(128);
            entity.Property(e => e.AccessNumber).HasMaxLength(25);
            entity.Property(e => e.Email).HasMaxLength(256);
            entity.Property(e => e.LockoutEndDateUtc).HasColumnType("datetime");

            entity.HasOne(d => d.PkIdUsuarioNavigation).WithMany(p => p.AspNetUsers)
                .HasForeignKey(d => d.PkIdUsuario)
                .HasConstraintName("CONSTRAINT_FK_AspNetUsers_Usuario");
        });

        modelBuilder.Entity<AspNetUserRole>(entity =>
        {
            entity.HasKey(e => new { e.UserId, e.RoleId }).HasName("CONSTRAINT_PK_AspNetUserRoles");

            entity.Property(e => e.UserId).HasMaxLength(128);
            entity.Property(e => e.RoleId).HasMaxLength(128);
            entity.Property(e => e.ExpireDate).HasColumnType("datetime");

            entity.HasOne(d => d.Role).WithMany(p => p.AspNetUserRoles)
                .HasForeignKey(d => d.RoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("CONSTRAINT_FK_AspNetUserRoles_Role");

            entity.HasOne(d => d.User).WithMany(p => p.AspNetUserRoles)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("CONSTRAINT_FK_AspNetUserRoles_User");
        });

        modelBuilder.Entity<CatTipoSucursal>(entity =>
        {
            entity.HasKey(e => e.PkidTipoSucursal).HasName("PK_TipoSucursal");

            entity.ToTable("CatTipoSucursal", "SIS");

            entity.HasIndex(e => e.Descripcion, "UQ_TipoSucursal_Descripcion").IsUnique();

            entity.Property(e => e.PkidTipoSucursal).HasColumnName("PKIdTipoSucursal");
            entity.Property(e => e.Activo).HasDefaultValue(true);
            entity.Property(e => e.Descripcion)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<Departamento>(entity =>
        {
            entity.HasKey(e => e.PkidDepartamento);

            entity.ToTable("Departamento", "SIS");

            entity.HasIndex(e => e.FkidEmpresaSis, "IX_Departamento_Empresa").HasFilter("([Activo]=(1))");

            entity.HasIndex(e => e.FkidSucursalSis, "IX_Departamento_Sucursal").HasFilter("([Activo]=(1))");

            entity.Property(e => e.PkidDepartamento).HasColumnName("PKIdDepartamento");
            entity.Property(e => e.Activo).HasDefaultValue(true);
            entity.Property(e => e.Descripcion).HasMaxLength(255);
            entity.Property(e => e.FechaCreacion).HasDefaultValueSql("(sysdatetime())");
            entity.Property(e => e.FkidEmpresaSis).HasColumnName("FKIdEmpresa_SIS");
            entity.Property(e => e.FkidSucursalSis).HasColumnName("FKIdSucursal_SIS");
            entity.Property(e => e.NivelJerarquico).HasDefaultValue(1);
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(128);

            entity.HasOne(d => d.FkidEmpresaSisNavigation).WithMany(p => p.Departamentos)
                .HasForeignKey(d => d.FkidEmpresaSis)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Departamento_Empresa");

            entity.HasOne(d => d.FkidSucursalSisNavigation).WithMany(p => p.Departamentos)
                .HasForeignKey(d => d.FkidSucursalSis)
                .HasConstraintName("FK_Departamento_Sucursal");
        });

        modelBuilder.Entity<Empresa>(entity =>
        {
            entity.HasKey(e => e.PkidEmpresa);

            entity.ToTable("Empresa", "SIS");

            entity.HasIndex(e => e.Rfc, "UQ_Empresa_RFC").IsUnique();

            entity.Property(e => e.PkidEmpresa).HasColumnName("PKIdEmpresa");
            entity.Property(e => e.Activo).HasDefaultValue(true);
            entity.Property(e => e.FechaCreacion).HasDefaultValueSql("(sysdatetime())");
            entity.Property(e => e.FkidIdiomaPreferidoSis).HasColumnName("FKIdIdiomaPreferido_SIS");
            entity.Property(e => e.FkidMonedaBaseSis).HasColumnName("FKIdMonedaBase_SIS");
            entity.Property(e => e.Giro).HasMaxLength(100);
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(128);
            entity.Property(e => e.RazonSocial).HasMaxLength(255);
            entity.Property(e => e.Rfc)
                .IsRequired()
                .HasMaxLength(13)
                .HasColumnName("RFC");

            entity.HasOne(d => d.FkidIdiomaPreferidoSisNavigation).WithMany(p => p.Empresas)
                .HasForeignKey(d => d.FkidIdiomaPreferidoSis)
                .HasConstraintName("FK_Empresa_Idioma");

            entity.HasOne(d => d.FkidMonedaBaseSisNavigation).WithMany(p => p.Empresas)
                .HasForeignKey(d => d.FkidMonedaBaseSis)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Empresa_Moneda");
        });

        modelBuilder.Entity<EmpresaEstado>(entity =>
        {
            entity.HasKey(e => new { e.FkidEmpresaSis, e.FkidEstadoSis });

            entity.ToTable("EmpresaEstado", "SIS");

            entity.Property(e => e.FkidEmpresaSis).HasColumnName("FKIdEmpresa_SIS");
            entity.Property(e => e.FkidEstadoSis).HasColumnName("FKIdEstado_SIS");
            entity.Property(e => e.Activo).HasDefaultValue(true);

            entity.HasOne(d => d.FkidEmpresaSisNavigation).WithMany(p => p.EmpresaEstados)
                .HasForeignKey(d => d.FkidEmpresaSis)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_EmpresaEstado_Empresa");

            entity.HasOne(d => d.FkidEstadoSisNavigation).WithMany(p => p.EmpresaEstados)
                .HasForeignKey(d => d.FkidEstadoSis)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_EmpresaEstado_Estado");
        });

        modelBuilder.Entity<Estado>(entity =>
        {
            entity.HasKey(e => e.PkidEstado);

            entity.ToTable("Estados", "SIS");

            entity.HasIndex(e => new { e.FkidPaisSis, e.Nombre }, "UQ_Estados_Pais_Nombre").IsUnique();

            entity.Property(e => e.PkidEstado).HasColumnName("PKIdEstado");
            entity.Property(e => e.Activo).HasDefaultValue(true);
            entity.Property(e => e.CodigoEstado)
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.FkidPaisSis).HasColumnName("FKIdPais_SIS");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(64)
                .IsUnicode(false);

            entity.HasOne(d => d.FkidPaisSisNavigation).WithMany(p => p.Estados)
                .HasForeignKey(d => d.FkidPaisSis)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Estados_Paises");
        });

        modelBuilder.Entity<Idioma>(entity =>
        {
            entity.HasKey(e => e.PkidIdioma);

            entity.ToTable("Idioma", "SIS");

            entity.HasIndex(e => e.CodigoIso6391, "UQ_Idioma_Codigo").IsUnique();

            entity.Property(e => e.PkidIdioma).HasColumnName("PKIdIdioma");
            entity.Property(e => e.Activo).HasDefaultValue(true);
            entity.Property(e => e.CodigoIso6391)
                .IsRequired()
                .HasMaxLength(2)
                .IsUnicode(false)
                .IsFixedLength()
                .HasColumnName("CodigoISO639_1");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.NombreNativo).HasMaxLength(50);
        });

        modelBuilder.Entity<Menu>(entity =>
        {
            entity.HasKey(e => e.PkidMenu).HasName("CONSTRAINT_PK_Menu");

            entity.ToTable("Menu", "SIS");

            entity.Property(e => e.PkidMenu)
                .ValueGeneratedNever()
                .HasColumnName("PKIdMenu");
            entity.Property(e => e.Activo).HasDefaultValue(true);
            entity.Property(e => e.CreatedDateTime)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.FkidMenuSis).HasColumnName("FKIdMenu_SIS");
            entity.Property(e => e.ImageUrl).HasMaxLength(120);
            entity.Property(e => e.LegacyName).HasMaxLength(80);
            entity.Property(e => e.Lenguaje)
                .IsRequired()
                .HasMaxLength(3)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.ModifiedDateTime).HasColumnType("datetime");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(150);
            entity.Property(e => e.Ruta).HasMaxLength(200);

            entity.HasOne(d => d.FkidMenuSisNavigation).WithMany(p => p.InverseFkidMenuSisNavigation)
                .HasForeignKey(d => d.FkidMenuSis)
                .HasConstraintName("CONSTRAINT_FK_Menu_Padre");
        });

        modelBuilder.Entity<MenuRole>(entity =>
        {
            entity.HasKey(e => new { e.FkidMenuSis, e.RoleId }).HasName("CONSTRAINT_PK_MenuRole");

            entity.ToTable("MenuRole", "SIS");

            entity.Property(e => e.FkidMenuSis).HasColumnName("FKIdMenu_SIS");
            entity.Property(e => e.RoleId).HasMaxLength(128);
            entity.Property(e => e.Activo).HasDefaultValue(true);
            entity.Property(e => e.CreatedDateTime)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.ModifiedDateTime).HasColumnType("datetime");

            entity.HasOne(d => d.FkidMenuSisNavigation).WithMany(p => p.MenuRoles)
                .HasForeignKey(d => d.FkidMenuSis)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("CONSTRAINT_FK_MenuRole_Menu");

            entity.HasOne(d => d.Role).WithMany(p => p.MenuRoles)
                .HasForeignKey(d => d.RoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("CONSTRAINT_FK_MenuRole_Role");
        });

        modelBuilder.Entity<Monedum>(entity =>
        {
            entity.HasKey(e => e.PkidMoneda);

            entity.ToTable("Moneda", "SIS");

            entity.HasIndex(e => e.CodigoIso4217, "UQ_Moneda_Codigo").IsUnique();

            entity.Property(e => e.PkidMoneda).HasColumnName("PKIdMoneda");
            entity.Property(e => e.Activo).HasDefaultValue(true);
            entity.Property(e => e.CodigoIso4217)
                .IsRequired()
                .HasMaxLength(3)
                .IsUnicode(false)
                .IsFixedLength()
                .HasColumnName("CodigoISO4217");
            entity.Property(e => e.Decimales).HasDefaultValue(2);
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Simbolo)
                .IsRequired()
                .HasMaxLength(5);
        });

        modelBuilder.Entity<OrigenLogMessage>(entity =>
        {
            entity.HasKey(e => e.PkidOrigenLogMessage).HasName("CONSTRAINT_PK_OrigenLogMessage");

            entity.ToTable("OrigenLogMessage", "SIS");

            entity.Property(e => e.PkidOrigenLogMessage)
                .ValueGeneratedNever()
                .HasColumnName("PKIdOrigenLogMessage");
            entity.Property(e => e.Activo).HasDefaultValue(true);
            entity.Property(e => e.Descripcion).HasMaxLength(50);
            entity.Property(e => e.FechaCreacion).HasDefaultValueSql("(sysdatetime())");
        });

        modelBuilder.Entity<Paise>(entity =>
        {
            entity.HasKey(e => e.PkidPais);

            entity.ToTable("Paises", "SIS");

            entity.HasIndex(e => e.CodigoIso2, "UQ_Paises_CodigoISO2").IsUnique();

            entity.HasIndex(e => e.CodigoIso3, "UQ_Paises_CodigoISO3").IsUnique();

            entity.Property(e => e.PkidPais).HasColumnName("PKIdPais");
            entity.Property(e => e.Activo).HasDefaultValue(true);
            entity.Property(e => e.CodigoIso2)
                .IsRequired()
                .HasMaxLength(2)
                .IsUnicode(false)
                .IsFixedLength()
                .HasColumnName("CodigoISO2");
            entity.Property(e => e.CodigoIso3)
                .IsRequired()
                .HasMaxLength(3)
                .IsUnicode(false)
                .IsFixedLength()
                .HasColumnName("CodigoISO3");
            entity.Property(e => e.FechaCreacion).HasDefaultValueSql("(sysdatetime())");
            entity.Property(e => e.FkidIdiomaPrincipalSis).HasColumnName("FKIdIdiomaPrincipal_SIS");
            entity.Property(e => e.FkidMonedaPrincipalSis).HasColumnName("FKIdMonedaPrincipal_SIS");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(64)
                .IsUnicode(false);

            entity.HasOne(d => d.FkidIdiomaPrincipalSisNavigation).WithMany(p => p.Paises)
                .HasForeignKey(d => d.FkidIdiomaPrincipalSis)
                .HasConstraintName("FK_Paises_Idioma");

            entity.HasOne(d => d.FkidMonedaPrincipalSisNavigation).WithMany(p => p.Paises)
                .HasForeignKey(d => d.FkidMonedaPrincipalSis)
                .HasConstraintName("FK_Paises_Moneda");
        });

        modelBuilder.Entity<PerfilUsuario>(entity =>
        {
            entity.HasKey(e => e.FkidUsuarioSis).HasName("PK__PerfilUs__98F09D6B86C38442");

            entity.ToTable("PerfilUsuario", "SIS");

            entity.Property(e => e.FkidUsuarioSis)
                .ValueGeneratedNever()
                .HasColumnName("FKIdUsuario_SIS");
            entity.Property(e => e.Activo).HasDefaultValue(true);
            entity.Property(e => e.ContentType).HasMaxLength(50);
            entity.Property(e => e.FechaCreacion).HasDefaultValueSql("(sysdatetime())");
            entity.Property(e => e.FileExtension).HasMaxLength(8);
            entity.Property(e => e.FileName).HasMaxLength(64);

            entity.HasOne(d => d.FkidUsuarioSisNavigation).WithOne(p => p.PerfilUsuario)
                .HasForeignKey<PerfilUsuario>(d => d.FkidUsuarioSis)
                .HasConstraintName("FK__PerfilUsu__Usuar__367C1819");
        });

        modelBuilder.Entity<Sucursal>(entity =>
        {
            entity.HasKey(e => e.PkidSucursal);

            entity.ToTable("Sucursal", "SIS");

            entity.HasIndex(e => e.FkidEmpresaSis, "IX_Sucursal_Empresa").HasFilter("([Activo]=(1))");

            entity.HasIndex(e => e.CodigoSucursal, "UQ_Sucursal_Codigo").IsUnique();

            entity.Property(e => e.PkidSucursal).HasColumnName("PKIdSucursal");
            entity.Property(e => e.Activo).HasDefaultValue(true);
            entity.Property(e => e.Alias).HasMaxLength(50);
            entity.Property(e => e.Ciudad).HasMaxLength(100);
            entity.Property(e => e.CodigoPostal).HasMaxLength(10);
            entity.Property(e => e.CodigoSucursal)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.Colonia).HasMaxLength(100);
            entity.Property(e => e.Direccion)
                .IsRequired()
                .HasMaxLength(256);
            entity.Property(e => e.Email).HasMaxLength(100);
            entity.Property(e => e.EsActiva).HasDefaultValue(true);
            entity.Property(e => e.FechaCreacion).HasDefaultValueSql("(sysdatetime())");
            entity.Property(e => e.FkidEmpresaSis).HasColumnName("FKIdEmpresa_SIS");
            entity.Property(e => e.FkidEstadoSis).HasColumnName("FKIdEstado_SIS");
            entity.Property(e => e.FkidMonedaLocalSis).HasColumnName("FKIdMonedaLocal_SIS");
            entity.Property(e => e.FkidTipoSucursal)
                .HasDefaultValue(2)
                .HasColumnName("FKIdTipoSucursal");
            entity.Property(e => e.Latitud).HasColumnType("decimal(9, 6)");
            entity.Property(e => e.Longitud).HasColumnType("decimal(9, 6)");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(128);
            entity.Property(e => e.TelefonoPrincipal).HasMaxLength(20);
            entity.Property(e => e.TelefonoSecundario).HasMaxLength(20);

            entity.HasOne(d => d.FkidEmpresaSisNavigation).WithMany(p => p.Sucursals)
                .HasForeignKey(d => d.FkidEmpresaSis)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Sucursal_Empresa");

            entity.HasOne(d => d.FkidEstadoSisNavigation).WithMany(p => p.Sucursals)
                .HasForeignKey(d => d.FkidEstadoSis)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Sucursal_Estado");

            entity.HasOne(d => d.FkidMonedaLocalSisNavigation).WithMany(p => p.Sucursals)
                .HasForeignKey(d => d.FkidMonedaLocalSis)
                .HasConstraintName("FK_Sucursal_Moneda");

            entity.HasOne(d => d.FkidTipoSucursalNavigation).WithMany(p => p.Sucursals)
                .HasForeignKey(d => d.FkidTipoSucursal)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Sucursal_Tipo");
        });

        modelBuilder.Entity<SystemLog>(entity =>
        {
            entity.HasKey(e => e.PkidSystemLog).HasName("CONSTRAINT_PK_SystemLog");

            entity.ToTable("SystemLog", "SIS");

            entity.Property(e => e.PkidSystemLog).HasColumnName("PKIdSystemLog");
            entity.Property(e => e.Category).HasMaxLength(24);
            entity.Property(e => e.Context).HasMaxLength(10);
            entity.Property(e => e.Date).HasDefaultValueSql("(sysdatetime())");
            entity.Property(e => e.EmployeeNo).HasMaxLength(24);
            entity.Property(e => e.Exception).HasMaxLength(4000);
            entity.Property(e => e.FkidOrigenLogMessageSis).HasColumnName("FKIdOrigenLogMessage_SIS");
            entity.Property(e => e.HostName).HasMaxLength(32);
            entity.Property(e => e.Ipclient)
                .HasMaxLength(24)
                .HasColumnName("IPClient");
            entity.Property(e => e.Level)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Logger)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.Message)
                .HasMaxLength(4000)
                .IsUnicode(false);
            entity.Property(e => e.MethodName).HasMaxLength(200);
            entity.Property(e => e.Parameters).HasMaxLength(4000);
            entity.Property(e => e.ProgName).HasMaxLength(256);
            entity.Property(e => e.Thread)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.Type).HasMaxLength(24);

            entity.HasOne(d => d.FkidOrigenLogMessageSisNavigation).WithMany(p => p.SystemLogs)
                .HasForeignKey(d => d.FkidOrigenLogMessageSis)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("CONSTRAINT_FK_SystemLog_OrigenLogMessage");
        });

        modelBuilder.Entity<SystemParamCatalog>(entity =>
        {
            entity.HasKey(e => e.PkidSystemParamCatalog).HasName("CONSTRAINT_PK_SystemParamCatalog");

            entity.ToTable("SystemParamCatalog", "SIS");

            entity.Property(e => e.PkidSystemParamCatalog)
                .ValueGeneratedNever()
                .HasColumnName("PKIdSystemParamCatalog");
            entity.Property(e => e.Activo).HasDefaultValue(true);
            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.FechaCreacion).HasDefaultValueSql("(sysdatetime())");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<SystemParamValue>(entity =>
        {
            entity.HasKey(e => e.PkidSystemParamValue).HasName("CONSTRAINT_PK_SystemParamValue");

            entity.ToTable("SystemParamValue", "SIS");

            entity.Property(e => e.PkidSystemParamValue)
                .ValueGeneratedNever()
                .HasColumnName("PKIdSystemParamValue");
            entity.Property(e => e.Activo).HasDefaultValue(true);
            entity.Property(e => e.Descripcion)
                .IsRequired()
                .HasMaxLength(128)
                .IsUnicode(false);
            entity.Property(e => e.FechaCreacion).HasDefaultValueSql("(sysdatetime())");
            entity.Property(e => e.FkidSystemParamCatalogSis).HasColumnName("FKIdSystemParamCatalog_SIS");
            entity.Property(e => e.Value).IsRequired();

            entity.HasOne(d => d.FkidSystemParamCatalogSisNavigation).WithMany(p => p.SystemParamValues)
                .HasForeignKey(d => d.FkidSystemParamCatalogSis)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("CONSTRAINT_FK_SystemParamCatalog_SystemParamValue");
        });

        modelBuilder.Entity<Usuario>(entity =>
        {
            entity.HasKey(e => e.PkIdUsuario);

            entity.ToTable("Usuario", "SIS");

            entity.HasIndex(e => e.AspNetUserId, "IX_Usuario_AspNetUserId");

            entity.HasIndex(e => e.Email, "IX_Usuario_Email").HasFilter("([Activo]=(1))");

            entity.HasIndex(e => e.FkidEmpresaSis, "IX_Usuario_Empresa").HasFilter("([Activo]=(1))");

            entity.HasIndex(e => e.AspNetUserId, "UQ_Usuario_AspNetUserId").IsUnique();

            entity.HasIndex(e => e.Email, "UQ_Usuario_Email").IsUnique();

            entity.HasIndex(e => e.Gafete, "UQ_Usuario_Gafete").IsUnique();

            entity.HasIndex(e => e.PayrollId, "UQ_Usuario_PayrollID").IsUnique();

            entity.Property(e => e.Activo).HasDefaultValue(true);
            entity.Property(e => e.ApellidoMaterno).HasMaxLength(64);
            entity.Property(e => e.ApellidoPaterno)
                .IsRequired()
                .HasMaxLength(64);
            entity.Property(e => e.AspNetUserId).IsRequired();
            entity.Property(e => e.CodigoPostal).HasMaxLength(9);
            entity.Property(e => e.Direccion1)
                .IsRequired()
                .HasMaxLength(128);
            entity.Property(e => e.Direccion2).HasMaxLength(64);
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(60);
            entity.Property(e => e.FechaCreacion).HasDefaultValueSql("(sysdatetime())");
            entity.Property(e => e.FkidEmpresaSis).HasColumnName("FKIdEmpresa_SIS");
            entity.Property(e => e.FkidIdiomaPreferidoSis).HasColumnName("FKIdIdiomaPreferido_SIS");
            entity.Property(e => e.FkidMonedaPreferidaSis).HasColumnName("FKIdMonedaPreferida_SIS");
            entity.Property(e => e.Gafete)
                .IsRequired()
                .HasMaxLength(11);
            entity.Property(e => e.Iniciales)
                .IsRequired()
                .HasMaxLength(3);
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(64);
            entity.Property(e => e.NumeroSocial)
                .IsRequired()
                .HasMaxLength(12);
            entity.Property(e => e.PayrollId)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("PayrollID");
            entity.Property(e => e.Telefono)
                .IsRequired()
                .HasMaxLength(16);

            entity.HasOne(d => d.FkidEmpresaSisNavigation).WithMany(p => p.Usuarios)
                .HasForeignKey(d => d.FkidEmpresaSis)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Usuario_Empresa");

            entity.HasOne(d => d.FkidIdiomaPreferidoSisNavigation).WithMany(p => p.Usuarios)
                .HasForeignKey(d => d.FkidIdiomaPreferidoSis)
                .HasConstraintName("FK_Usuario_Idioma");

            entity.HasOne(d => d.FkidMonedaPreferidaSisNavigation).WithMany(p => p.Usuarios)
                .HasForeignKey(d => d.FkidMonedaPreferidaSis)
                .HasConstraintName("FK_Usuario_Moneda");
        });

        modelBuilder.Entity<UsuarioDepartamento>(entity =>
        {
            entity.HasKey(e => new { e.FkidUsuarioSis, e.FkidDepartamentoSis, e.FechaAsignacion });

            entity.ToTable("UsuarioDepartamento", "SIS");

            entity.HasIndex(e => e.FkidDepartamentoSis, "IX_UsuarioDepartamento_Departamento").HasFilter("([Activo]=(1))");

            entity.HasIndex(e => e.FkidUsuarioSis, "IX_UsuarioDepartamento_Usuario").HasFilter("([Activo]=(1))");

            entity.Property(e => e.FkidUsuarioSis).HasColumnName("FKIdUsuario_SIS");
            entity.Property(e => e.FkidDepartamentoSis).HasColumnName("FKIdDepartamento_SIS");
            entity.Property(e => e.FechaAsignacion).HasDefaultValueSql("(sysdatetime())");
            entity.Property(e => e.Activo).HasDefaultValue(true);
            entity.Property(e => e.FechaCreacion).HasDefaultValueSql("(sysdatetime())");

            entity.HasOne(d => d.FkidDepartamentoSisNavigation).WithMany(p => p.UsuarioDepartamentos)
                .HasForeignKey(d => d.FkidDepartamentoSis)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UsuarioDepartamento_Departamento");

            entity.HasOne(d => d.FkidUsuarioSisNavigation).WithMany(p => p.UsuarioDepartamentos)
                .HasForeignKey(d => d.FkidUsuarioSis)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UsuarioDepartamento_Usuario");
        });

        modelBuilder.Entity<UsuarioSucursal>(entity =>
        {
            entity.HasKey(e => new { e.FkidUsuarioSis, e.FkidSucursalSis });

            entity.ToTable("UsuarioSucursal", "SIS");

            entity.HasIndex(e => e.FkidSucursalSis, "IX_UsuarioSucursal_Sucursal").HasFilter("([Activo]=(1))");

            entity.HasIndex(e => e.FkidUsuarioSis, "IX_UsuarioSucursal_Usuario").HasFilter("([Activo]=(1))");

            entity.Property(e => e.FkidUsuarioSis).HasColumnName("FKIdUsuario_SIS");
            entity.Property(e => e.FkidSucursalSis).HasColumnName("FKIdSucursal_SIS");
            entity.Property(e => e.Activo).HasDefaultValue(true);
            entity.Property(e => e.FechaAsignacion).HasDefaultValueSql("(sysdatetime())");
            entity.Property(e => e.FechaCreacion).HasDefaultValueSql("(sysdatetime())");
            entity.Property(e => e.PuedeAcceder).HasDefaultValue(true);
            entity.Property(e => e.PuedeOperar).HasDefaultValue(true);

            entity.HasOne(d => d.FkidSucursalSisNavigation).WithMany(p => p.UsuarioSucursals)
                .HasForeignKey(d => d.FkidSucursalSis)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UsuarioSucursal_Sucursal");

            entity.HasOne(d => d.FkidUsuarioSisNavigation).WithMany(p => p.UsuarioSucursals)
                .HasForeignKey(d => d.FkidUsuarioSis)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UsuarioSucursal_Usuario");
        });

        modelBuilder.Entity<VwEmpresaDepartamanto>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("VW_EmpresaDepartamanto", "SIS");

            entity.Property(e => e.DepartamentoNombre)
                .IsRequired()
                .HasMaxLength(128);
            entity.Property(e => e.EmpresaNombre)
                .IsRequired()
                .HasMaxLength(128);
            entity.Property(e => e.PkidDepartamento).HasColumnName("PKIdDepartamento");
            entity.Property(e => e.PkidEmpresa).HasColumnName("PKIdEmpresa");
            entity.Property(e => e.Rfc)
                .IsRequired()
                .HasMaxLength(13)
                .HasColumnName("RFC");
        });

        modelBuilder.Entity<VwEstadoEmpresa>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("VW_EstadoEmpresa", "SIS");

            entity.Property(e => e.EmpresaNombre)
                .IsRequired()
                .HasMaxLength(128);
            entity.Property(e => e.EstadoNombre)
                .IsRequired()
                .HasMaxLength(64)
                .IsUnicode(false);
            entity.Property(e => e.PkidEmpresa).HasColumnName("PKIdEmpresa");
            entity.Property(e => e.PkidEstado).HasColumnName("PKIdEstado");
            entity.Property(e => e.Rfc)
                .IsRequired()
                .HasMaxLength(13)
                .HasColumnName("RFC");
        });

        modelBuilder.Entity<VwMenu>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("vw_Menu", "SIS");

            entity.Property(e => e.CreatedDateTime).HasColumnType("datetime");
            entity.Property(e => e.Estado)
                .IsRequired()
                .HasMaxLength(8)
                .IsUnicode(false);
            entity.Property(e => e.FkidMenuSis).HasColumnName("FKIdMenu_SIS");
            entity.Property(e => e.ImageUrl).HasMaxLength(120);
            entity.Property(e => e.LegacyName).HasMaxLength(80);
            entity.Property(e => e.Lenguaje)
                .IsRequired()
                .HasMaxLength(3)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.ModifiedDateTime).HasColumnType("datetime");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(150);
            entity.Property(e => e.NombreMenuPadre).HasMaxLength(150);
            entity.Property(e => e.PkidMenu).HasColumnName("PKIdMenu");
            entity.Property(e => e.Ruta).HasMaxLength(200);
            entity.Property(e => e.RutaCompleta).HasMaxLength(303);
            entity.Property(e => e.TipoDescripcion)
                .IsRequired()
                .HasMaxLength(27)
                .IsUnicode(false);
            entity.Property(e => e.TipoMenuPadreDescripcion)
                .IsRequired()
                .HasMaxLength(11)
                .IsUnicode(false);
            entity.Property(e => e.ValidacionEstructura)
                .IsRequired()
                .HasMaxLength(46)
                .IsUnicode(false);
        });

        modelBuilder.Entity<VwSucursalEmpresaEstado>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("VW_SucursalEmpresaEstado", "SIS");

            entity.Property(e => e.Alias).HasMaxLength(50);
            entity.Property(e => e.Ciudad).HasMaxLength(100);
            entity.Property(e => e.CodigoEstado)
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.CodigoPostal).HasMaxLength(10);
            entity.Property(e => e.CodigoSucursal)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.Colonia).HasMaxLength(100);
            entity.Property(e => e.Direccion)
                .IsRequired()
                .HasMaxLength(256);
            entity.Property(e => e.Email).HasMaxLength(100);
            entity.Property(e => e.FkidEmpresaSis).HasColumnName("FKIdEmpresa_SIS");
            entity.Property(e => e.FkidEstadoSis).HasColumnName("FKIdEstado_SIS");
            entity.Property(e => e.FkidMonedaLocalSis).HasColumnName("FKIdMonedaLocal_SIS");
            entity.Property(e => e.FkidTipoSucursal).HasColumnName("FKIdTipoSucursal");
            entity.Property(e => e.Latitud).HasColumnType("decimal(9, 6)");
            entity.Property(e => e.Longitud).HasColumnType("decimal(9, 6)");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(128);
            entity.Property(e => e.NombreEmpresa)
                .IsRequired()
                .HasMaxLength(128);
            entity.Property(e => e.NombreEstado)
                .IsRequired()
                .HasMaxLength(64)
                .IsUnicode(false);
            entity.Property(e => e.NombrePais)
                .IsRequired()
                .HasMaxLength(64)
                .IsUnicode(false);
            entity.Property(e => e.PkidSucursal).HasColumnName("PKIdSucursal");
            entity.Property(e => e.Rfc)
                .IsRequired()
                .HasMaxLength(13)
                .HasColumnName("RFC");
            entity.Property(e => e.TelefonoPrincipal).HasMaxLength(20);
            entity.Property(e => e.TelefonoSecundario).HasMaxLength(20);
        });

        modelBuilder.Entity<VwUsuarioEmpresa>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("VW_UsuarioEmpresa", "SIS");

            entity.Property(e => e.ApellidoMaterno).HasMaxLength(64);
            entity.Property(e => e.ApellidoPaterno)
                .IsRequired()
                .HasMaxLength(64);
            entity.Property(e => e.AspNetUserId)
                .IsRequired()
                .HasMaxLength(450);
            entity.Property(e => e.CoberturaSucursales)
                .IsRequired()
                .HasMaxLength(17)
                .IsUnicode(false);
            entity.Property(e => e.CodigoPostalUsuario).HasMaxLength(9);
            entity.Property(e => e.DepartamentosComoJefe).HasMaxLength(4000);
            entity.Property(e => e.Direccion1)
                .IsRequired()
                .HasMaxLength(128);
            entity.Property(e => e.Direccion2).HasMaxLength(64);
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(60);
            entity.Property(e => e.FechaIngresoFormat).HasMaxLength(4000);
            entity.Property(e => e.Gafete)
                .IsRequired()
                .HasMaxLength(11);
            entity.Property(e => e.GiroEmpresa).HasMaxLength(100);
            entity.Property(e => e.IdiomaPreferido).HasMaxLength(50);
            entity.Property(e => e.Iniciales)
                .IsRequired()
                .HasMaxLength(3);
            entity.Property(e => e.InicialesNombre).HasMaxLength(2);
            entity.Property(e => e.ListaDepartamentos).HasMaxLength(4000);
            entity.Property(e => e.ListaSucursales).HasMaxLength(4000);
            entity.Property(e => e.MonedaBaseEmpresa).HasMaxLength(50);
            entity.Property(e => e.MonedaPreferida).HasMaxLength(50);
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(64);
            entity.Property(e => e.NombreCompleto)
                .IsRequired()
                .HasMaxLength(194);
            entity.Property(e => e.NombreEmpresa)
                .IsRequired()
                .HasMaxLength(128);
            entity.Property(e => e.NumeroEmpleado)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.NumeroSocial)
                .IsRequired()
                .HasMaxLength(12);
            entity.Property(e => e.PayrollId)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("PayrollID");
            entity.Property(e => e.PkidEmpresa).HasColumnName("PKIdEmpresa");
            entity.Property(e => e.RazonSocialEmpresa).HasMaxLength(255);
            entity.Property(e => e.RfcEmpresa)
                .IsRequired()
                .HasMaxLength(13);
            entity.Property(e => e.RolPrincipal)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.SexoDescripcion)
                .IsRequired()
                .HasMaxLength(9)
                .IsUnicode(false);
            entity.Property(e => e.SimboloMoneda).HasMaxLength(5);
            entity.Property(e => e.SimboloMonedaBase).HasMaxLength(5);
            entity.Property(e => e.SucursalMatrizAsignada).HasMaxLength(128);
            entity.Property(e => e.TelefonoUsuario)
                .IsRequired()
                .HasMaxLength(16);
            entity.Property(e => e.UsuarioFechaCreacionFormat).HasMaxLength(4000);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}