// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using EG.Infraestructure.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace EG.Infraestructure.Models
{
    public partial class EGestionContext
    {
        private IEGestionContextProcedures _procedures;

        public virtual IEGestionContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new EGestionContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IEGestionContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class EGestionContextProcedures : IEGestionContextProcedures
    {
        private readonly EGestionContext _context;

        public EGestionContextProcedures(EGestionContext context)
        {
            _context = context;
        }

        public virtual async Task<List<LoginInformationEmployeeResult>> LoginInformationEmployeeAsync(string payrollID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "PayrollID",
                    Size = 120,
                    Value = payrollID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<LoginInformationEmployeeResult>("EXEC @returnValue = [SIS].[LoginInformationEmployee] @PayrollID = @PayrollID", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<sp_RegistrarConteoResult>> sp_RegistrarConteoAsync(int? pKIdArticuloConteo, decimal? cantidadContada, int? fKIdUsuario_SIS, string observaciones, decimal? latitud, decimal? longitud, string fotoPath, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "PKIdArticuloConteo",
                    Value = pKIdArticuloConteo ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "CantidadContada",
                    Precision = 18,
                    Scale = 4,
                    Value = cantidadContada ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Decimal,
                },
                new SqlParameter
                {
                    ParameterName = "FKIdUsuario_SIS",
                    Value = fKIdUsuario_SIS ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "Observaciones",
                    Size = 1000,
                    Value = observaciones ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Latitud",
                    Precision = 9,
                    Scale = 6,
                    Value = latitud ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Decimal,
                },
                new SqlParameter
                {
                    ParameterName = "Longitud",
                    Precision = 9,
                    Scale = 6,
                    Value = longitud ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Decimal,
                },
                new SqlParameter
                {
                    ParameterName = "FotoPath",
                    Size = 1000,
                    Value = fotoPath ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<sp_RegistrarConteoResult>("EXEC @returnValue = [ALMA].[sp_RegistrarConteo] @PKIdArticuloConteo = @PKIdArticuloConteo, @CantidadContada = @CantidadContada, @FKIdUsuario_SIS = @FKIdUsuario_SIS, @Observaciones = @Observaciones, @Latitud = @Latitud, @Longitud = @Longitud, @FotoPath = @FotoPath", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<spConfiguracionDeRolYClaimsResult>> spConfiguracionDeRolYClaimsAsync(string group, string subgroup, string code, string values, string description, string rolName, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "group",
                    Size = 200,
                    Value = group ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "subgroup",
                    Size = 200,
                    Value = subgroup ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "code",
                    Size = 20,
                    Value = code ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "values",
                    Size = -1,
                    Value = values ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "description",
                    Size = 400,
                    Value = description ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "rolName",
                    Size = 512,
                    Value = rolName ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<spConfiguracionDeRolYClaimsResult>("EXEC @returnValue = [dbo].[spConfiguracionDeRolYClaims] @group = @group, @subgroup = @subgroup, @code = @code, @values = @values, @description = @description, @rolName = @rolName", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<spEliminarUsuarioSucursalResult>> spEliminarUsuarioSucursalAsync(int? fkidUsuarioSis, int? fkidSucursalSis, string usuarioModificacion, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "FkidUsuarioSis",
                    Value = fkidUsuarioSis ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "FkidSucursalSis",
                    Value = fkidSucursalSis ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "UsuarioModificacion",
                    Size = 100,
                    Value = usuarioModificacion ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<spEliminarUsuarioSucursalResult>("EXEC @returnValue = [SIS].[spEliminarUsuarioSucursal] @FkidUsuarioSis = @FkidUsuarioSis, @FkidSucursalSis = @FkidSucursalSis, @UsuarioModificacion = @UsuarioModificacion", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<spGetClaimsByUserResult>> spGetClaimsByUserAsync(int? pkIdUser, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "PkIdUser",
                    Value = pkIdUser ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<spGetClaimsByUserResult>("EXEC @returnValue = [SIS].[spGetClaimsByUser] @PkIdUser = @PkIdUser", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<spNodeMenuResult>> spNodeMenuAsync(int? noEmploye, string lenguaje, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "NoEmploye",
                    Value = noEmploye ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "Lenguaje",
                    Size = 3,
                    Value = lenguaje ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Char,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<spNodeMenuResult>("EXEC @returnValue = [SIS].[spNodeMenu] @NoEmploye = @NoEmploye, @Lenguaje = @Lenguaje", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> WriteSystemLogAsync(string fK_IdOrigenLogMessage__SIS, string date, string _Type, string progName, string employeeNo, string category, string iPClient, string hostName, string thread, string level, string logger, string message, string exception, string context, string methodName, string parameters, string executionTime, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "FK_IdOrigenLogMessage__SIS",
                    Size = 48,
                    Value = fK_IdOrigenLogMessage__SIS ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Date",
                    Size = 48,
                    Value = date ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "_Type",
                    Size = 48,
                    Value = _Type ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "ProgName",
                    Size = 512,
                    Value = progName ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "EmployeeNo",
                    Size = 48,
                    Value = employeeNo ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Category",
                    Size = 48,
                    Value = category ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "IPClient",
                    Size = 48,
                    Value = iPClient ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "HostName",
                    Size = 64,
                    Value = hostName ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Thread",
                    Size = 510,
                    Value = thread ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Level",
                    Size = 40,
                    Value = level ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Logger",
                    Size = 510,
                    Value = logger ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Message",
                    Size = 8000,
                    Value = message ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Exception",
                    Size = 8000,
                    Value = exception ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Context",
                    Size = 20,
                    Value = context ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "MethodName",
                    Size = 400,
                    Value = methodName ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Parameters",
                    Size = 8000,
                    Value = parameters ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "ExecutionTime",
                    Size = 64,
                    Value = executionTime ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [SIS].[WriteSystemLog] @FK_IdOrigenLogMessage__SIS = @FK_IdOrigenLogMessage__SIS, @Date = @Date, @_Type = @_Type, @ProgName = @ProgName, @EmployeeNo = @EmployeeNo, @Category = @Category, @IPClient = @IPClient, @HostName = @HostName, @Thread = @Thread, @Level = @Level, @Logger = @Logger, @Message = @Message, @Exception = @Exception, @Context = @Context, @MethodName = @MethodName, @Parameters = @Parameters, @ExecutionTime = @ExecutionTime", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
