// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using EG.Domain.Entities;
using Microsoft.EntityFrameworkCore;

namespace EG.Infraestructure.Models;

public partial class EGestionContext : DbContext
{
    public EGestionContext(DbContextOptions<EGestionContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AspNetClaim> AspNetClaims { get; set; }

    public virtual DbSet<AspNetClaimType> AspNetClaimTypes { get; set; }

    public virtual DbSet<AspNetClaimValue> AspNetClaimValues { get; set; }

    public virtual DbSet<AspNetRole> AspNetRoles { get; set; }

    public virtual DbSet<AspNetUser> AspNetUsers { get; set; }

    public virtual DbSet<AspNetUserRole> AspNetUserRoles { get; set; }

    public virtual DbSet<CatTipoSucursal> CatTipoSucursals { get; set; }

    public virtual DbSet<Departamento> Departamentos { get; set; }

    public virtual DbSet<Empresa> Empresas { get; set; }

    public virtual DbSet<EmpresaEstado> EmpresaEstados { get; set; }

    public virtual DbSet<Estado> Estados { get; set; }

    public virtual DbSet<Menu> Menus { get; set; }

    public virtual DbSet<MenuRole> MenuRoles { get; set; }

    public virtual DbSet<OrigenLogMessage> OrigenLogMessages { get; set; }

    public virtual DbSet<Paise> Paises { get; set; }

    public virtual DbSet<PerfilUsuario> PerfilUsuarios { get; set; }

    public virtual DbSet<Sucursal> Sucursals { get; set; }

    public virtual DbSet<SystemLog> SystemLogs { get; set; }

    public virtual DbSet<SystemParamCatalog> SystemParamCatalogs { get; set; }

    public virtual DbSet<SystemParamValue> SystemParamValues { get; set; }

    public virtual DbSet<Usuario> Usuarios { get; set; }

    public virtual DbSet<UsuarioSucursal> UsuarioSucursals { get; set; }

    public virtual DbSet<VwEmpresaDepartamanto> VwEmpresaDepartamantos { get; set; }

    public virtual DbSet<VwEstadoEmpresa> VwEstadoEmpresas { get; set; }

    public virtual DbSet<VwMenu> VwMenus { get; set; }

    public virtual DbSet<VwUsuarioSucursal> VwUsuarioSucursals { get; set; }

    public virtual DbSet<VwUsuarioSucursalSimplificadum> VwUsuarioSucursalSimplificada { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AspNetClaim>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("CONSTRAINT_PK_AspNetClaims");

            entity.Property(e => e.Code).HasMaxLength(10);
            entity.Property(e => e.Created).HasColumnType("datetime");
            entity.Property(e => e.Description).HasMaxLength(200);
            entity.Property(e => e.Group).HasMaxLength(100);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(150);
            entity.Property(e => e.RoleId).HasMaxLength(128);
            entity.Property(e => e.SubGroup).HasMaxLength(100);
            entity.Property(e => e.TokenFormat).HasMaxLength(50);
            entity.Property(e => e.Values).IsUnicode(false);

            entity.HasOne(d => d.ClaimType).WithMany(p => p.AspNetClaims)
                .HasForeignKey(d => d.ClaimTypeId)
                .HasConstraintName("CONSTRAINT_FK_AspNetClaims_ClaimType");

            entity.HasOne(d => d.Role).WithMany(p => p.AspNetClaims)
                .HasForeignKey(d => d.RoleId)
                .HasConstraintName("CONSTRAINT_FK_AspNetClaims_Role");
        });

        modelBuilder.Entity<AspNetClaimType>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("CONSTRAINT_PK_AspNetClaimTypes");

            entity.Property(e => e.Created).HasColumnType("datetime");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<AspNetClaimValue>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("CONSTRAINT_PK_AspNetClaimValues");

            entity.Property(e => e.Created)
                .HasDefaultValueSql("(getdate())", "CONSTRAINT_DF_AspNetClaimValues_Created")
                .HasColumnType("datetime");
            entity.Property(e => e.Value)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.Claim).WithMany(p => p.AspNetClaimValues)
                .HasForeignKey(d => d.ClaimId)
                .HasConstraintName("CONSTRAINT_FK_AspNetClaimValues_Claim");
        });

        modelBuilder.Entity<AspNetRole>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("CONSTRAINT_PK_AspNetRoles");

            entity.HasIndex(e => e.Name, "CONSTRAINT_UX_AspNetRoles_Name").IsUnique();

            entity.Property(e => e.Id).HasMaxLength(128);
            entity.Property(e => e.Code).HasMaxLength(10);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(256);
        });

        modelBuilder.Entity<AspNetUser>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("CONSTRAINT_PK_AspNetUsers");

            entity.Property(e => e.Id).HasMaxLength(128);
            entity.Property(e => e.AccessNumber).HasMaxLength(25);
            entity.Property(e => e.Email).HasMaxLength(256);
            entity.Property(e => e.LockoutEndDateUtc).HasColumnType("datetime");

            entity.HasOne(d => d.PkIdUsuarioNavigation).WithMany(p => p.AspNetUsers)
                .HasForeignKey(d => d.PkIdUsuario)
                .HasConstraintName("CONSTRAINT_FK_AspNetUsers_Usuario");
        });

        modelBuilder.Entity<AspNetUserRole>(entity =>
        {
            entity.HasKey(e => new { e.UserId, e.RoleId }).HasName("CONSTRAINT_PK_AspNetUserRoles");

            entity.Property(e => e.UserId).HasMaxLength(128);
            entity.Property(e => e.RoleId).HasMaxLength(128);
            entity.Property(e => e.ExpireDate).HasColumnType("datetime");

            entity.HasOne(d => d.Role).WithMany(p => p.AspNetUserRoles)
                .HasForeignKey(d => d.RoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("CONSTRAINT_FK_AspNetUserRoles_Role");

            entity.HasOne(d => d.User).WithMany(p => p.AspNetUserRoles)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("CONSTRAINT_FK_AspNetUserRoles_User");
        });

        modelBuilder.Entity<CatTipoSucursal>(entity =>
        {
            entity.HasKey(e => e.PkidTipoSucursal).HasName("PK_TipoSucursal");

            entity.ToTable("CatTipoSucursal", "SIS");

            entity.Property(e => e.PkidTipoSucursal)
                .ValueGeneratedNever()
                .HasColumnName("PKIdTipoSucursal");
            entity.Property(e => e.Activo).HasDefaultValue(true);
            entity.Property(e => e.Descripcion)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.FechaCreacion).HasDefaultValueSql("(sysdatetime())");
        });

        modelBuilder.Entity<Departamento>(entity =>
        {
            entity.HasKey(e => e.PkidDepartamento).HasName("CONSTRAINT_PK_Departamento");

            entity.ToTable("Departamento", "SIS");

            entity.Property(e => e.PkidDepartamento).HasColumnName("PKIdDepartamento");
            entity.Property(e => e.Activo).HasDefaultValue(true);
            entity.Property(e => e.FechaCreacion).HasDefaultValueSql("(sysdatetime())");
            entity.Property(e => e.FkidEmpresaSis).HasColumnName("FKIdEmpresa_SIS");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(128);

            entity.HasOne(d => d.FkidEmpresaSisNavigation).WithMany(p => p.Departamentos)
                .HasForeignKey(d => d.FkidEmpresaSis)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("CONSTRAINT_FK_Departamento_Empresa");
        });

        modelBuilder.Entity<Empresa>(entity =>
        {
            entity.HasKey(e => e.PkidEmpresa).HasName("CONSTRAINT_PK_Empresa");

            entity.ToTable("Empresa", "SIS");

            entity.Property(e => e.PkidEmpresa).HasColumnName("PKIdEmpresa");
            entity.Property(e => e.Activo).HasDefaultValue(true);
            entity.Property(e => e.FechaCreacion).HasDefaultValueSql("(sysdatetime())");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(128);
            entity.Property(e => e.Rfc)
                .IsRequired()
                .HasMaxLength(13)
                .HasColumnName("RFC");
        });

        modelBuilder.Entity<EmpresaEstado>(entity =>
        {
            entity.HasKey(e => new { e.FkidEmpresaSis, e.FkidEstadoSis }).HasName("CONSTRAINT_PK_EmpresaEstado_Empresa_Estado");

            entity.ToTable("EmpresaEstado", "SIS");

            entity.Property(e => e.FkidEmpresaSis).HasColumnName("FKIdEmpresa_SIS");
            entity.Property(e => e.FkidEstadoSis).HasColumnName("FKIdEstado_SIS");
            entity.Property(e => e.Activo).HasDefaultValue(true);
            entity.Property(e => e.FechaCreacion).HasDefaultValueSql("(sysdatetime())");

            entity.HasOne(d => d.FkidEmpresaSisNavigation).WithMany(p => p.EmpresaEstados)
                .HasForeignKey(d => d.FkidEmpresaSis)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("CONSTRAINT_FK_EmpresaEstado_Empresa");

            entity.HasOne(d => d.FkidEstadoSisNavigation).WithMany(p => p.EmpresaEstados)
                .HasForeignKey(d => d.FkidEstadoSis)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("CONSTRAINT_FK_EmpresaEstado_Estados");
        });

        modelBuilder.Entity<Estado>(entity =>
        {
            entity.HasKey(e => e.PkidEstado).HasName("CONSTRAINT_PK_Estados");

            entity.ToTable("Estados", "SIS");

            entity.Property(e => e.PkidEstado)
                .ValueGeneratedNever()
                .HasColumnName("PKIdEstado");
            entity.Property(e => e.FkidPaisSis).HasColumnName("FKIdPais_SIS");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(64)
                .IsUnicode(false);

            entity.HasOne(d => d.FkidPaisSisNavigation).WithMany(p => p.Estados)
                .HasForeignKey(d => d.FkidPaisSis)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("CONSTRAINT_FK_Estados_Paises");
        });

        modelBuilder.Entity<Menu>(entity =>
        {
            entity.HasKey(e => e.PkidMenu).HasName("CONSTRAINT_PK_Menu");

            entity.ToTable("Menu", "SIS");

            entity.Property(e => e.PkidMenu)
                .ValueGeneratedNever()
                .HasColumnName("PKIdMenu");
            entity.Property(e => e.Activo).HasDefaultValue(true);
            entity.Property(e => e.CreatedDateTime)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.FkidMenuSis).HasColumnName("FKIdMenu_SIS");
            entity.Property(e => e.ImageUrl).HasMaxLength(120);
            entity.Property(e => e.LegacyName).HasMaxLength(80);
            entity.Property(e => e.Lenguaje)
                .IsRequired()
                .HasMaxLength(3)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.ModifiedDateTime).HasColumnType("datetime");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(150);
            entity.Property(e => e.Ruta).HasMaxLength(200);

            entity.HasOne(d => d.FkidMenuSisNavigation).WithMany(p => p.InverseFkidMenuSisNavigation)
                .HasForeignKey(d => d.FkidMenuSis)
                .HasConstraintName("CONSTRAINT_FK_Menu_Padre");
        });

        modelBuilder.Entity<MenuRole>(entity =>
        {
            entity.HasKey(e => new { e.FkidMenuSis, e.RoleId }).HasName("CONSTRAINT_PK_MenuRole");

            entity.ToTable("MenuRole", "SIS");

            entity.Property(e => e.FkidMenuSis).HasColumnName("FKIdMenu_SIS");
            entity.Property(e => e.RoleId).HasMaxLength(128);
            entity.Property(e => e.Activo).HasDefaultValue(true);
            entity.Property(e => e.CreatedDateTime)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.ModifiedDateTime).HasColumnType("datetime");

            entity.HasOne(d => d.FkidMenuSisNavigation).WithMany(p => p.MenuRoles)
                .HasForeignKey(d => d.FkidMenuSis)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("CONSTRAINT_FK_MenuRole_Menu");

            entity.HasOne(d => d.Role).WithMany(p => p.MenuRoles)
                .HasForeignKey(d => d.RoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("CONSTRAINT_FK_MenuRole_Role");
        });

        modelBuilder.Entity<OrigenLogMessage>(entity =>
        {
            entity.HasKey(e => e.PkidOrigenLogMessage).HasName("CONSTRAINT_PK_OrigenLogMessage");

            entity.ToTable("OrigenLogMessage", "SIS");

            entity.Property(e => e.PkidOrigenLogMessage)
                .ValueGeneratedNever()
                .HasColumnName("PKIdOrigenLogMessage");
            entity.Property(e => e.Activo).HasDefaultValue(true);
            entity.Property(e => e.Descripcion).HasMaxLength(50);
            entity.Property(e => e.FechaCreacion).HasDefaultValueSql("(sysdatetime())");
        });

        modelBuilder.Entity<Paise>(entity =>
        {
            entity.HasKey(e => e.PkidPais).HasName("CONSTRAINT_PKIdPaises");

            entity.ToTable("Paises", "SIS");

            entity.Property(e => e.PkidPais)
                .ValueGeneratedNever()
                .HasColumnName("PKIdPais");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(64)
                .IsUnicode(false);
        });

        modelBuilder.Entity<PerfilUsuario>(entity =>
        {
            entity.HasKey(e => e.FkidUsuarioSis).HasName("PK__PerfilUs__98F09D6BA589FA1F");

            entity.ToTable("PerfilUsuario", "SIS");

            entity.Property(e => e.FkidUsuarioSis)
                .ValueGeneratedNever()
                .HasColumnName("FKIdUsuario_SIS");
            entity.Property(e => e.Activo).HasDefaultValue(true);
            entity.Property(e => e.ContentType).HasMaxLength(50);
            entity.Property(e => e.FechaCreacion).HasDefaultValueSql("(sysdatetime())");
            entity.Property(e => e.FileExtension).HasMaxLength(8);
            entity.Property(e => e.FileName).HasMaxLength(64);

            entity.HasOne(d => d.FkidUsuarioSisNavigation).WithOne(p => p.PerfilUsuario)
                .HasForeignKey<PerfilUsuario>(d => d.FkidUsuarioSis)
                .HasConstraintName("FK__PerfilUsu__Usuar__10566F31");
        });

        modelBuilder.Entity<Sucursal>(entity =>
        {
            entity.HasKey(e => e.PkidSucursal).HasName("CONSTRAINT_PK_Sucursal");

            entity.ToTable("Sucursal", "SIS");

            entity.HasIndex(e => e.CodigoSucursal, "IX_Sucursal_Codigo").HasFilter("([Activo]=(1))");

            entity.HasIndex(e => e.FkidEmpresaSis, "IX_Sucursal_Empresa").HasFilter("([Activo]=(1))");

            entity.HasIndex(e => e.FkidEstadoSis, "IX_Sucursal_Estado").HasFilter("([Activo]=(1))");

            entity.HasIndex(e => new { e.FkidEmpresaSis, e.EsMatriz }, "IX_Sucursal_Matriz").HasFilter("([Activo]=(1))");

            entity.HasIndex(e => e.TipoSucursal, "IX_Sucursal_Tipo").HasFilter("([Activo]=(1))");

            entity.HasIndex(e => e.CodigoSucursal, "UQ__Sucursal__E9A9A1029EB4253B").IsUnique();

            entity.Property(e => e.PkidSucursal).HasColumnName("PKIdSucursal");
            entity.Property(e => e.Activo).HasDefaultValue(true);
            entity.Property(e => e.Alias).HasMaxLength(50);
            entity.Property(e => e.Ciudad).HasMaxLength(100);
            entity.Property(e => e.CodigoPostal).HasMaxLength(10);
            entity.Property(e => e.CodigoSucursal)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.Colonia).HasMaxLength(100);
            entity.Property(e => e.Direccion)
                .IsRequired()
                .HasMaxLength(256);
            entity.Property(e => e.Email).HasMaxLength(100);
            entity.Property(e => e.EsActiva).HasDefaultValue(true);
            entity.Property(e => e.FechaCreacion).HasDefaultValueSql("(sysdatetime())");
            entity.Property(e => e.FkidEmpresaSis).HasColumnName("FKIdEmpresa_SIS");
            entity.Property(e => e.FkidEstadoSis).HasColumnName("FKIdEstado_SIS");
            entity.Property(e => e.Latitud).HasColumnType("decimal(9, 6)");
            entity.Property(e => e.Longitud).HasColumnType("decimal(9, 6)");
            entity.Property(e => e.MetrosCuadrados).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(128);
            entity.Property(e => e.TelefonoPrincipal).HasMaxLength(20);
            entity.Property(e => e.TelefonoSecundario).HasMaxLength(20);
            entity.Property(e => e.TipoSucursal).HasDefaultValue(1);

            entity.HasOne(d => d.FkidEmpresaSisNavigation).WithMany(p => p.Sucursals)
                .HasForeignKey(d => d.FkidEmpresaSis)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("CONSTRAINT_FK_Sucursal_Empresa");

            entity.HasOne(d => d.FkidEstadoSisNavigation).WithMany(p => p.Sucursals)
                .HasForeignKey(d => d.FkidEstadoSis)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("CONSTRAINT_FK_Sucursal_Estado");
        });

        modelBuilder.Entity<SystemLog>(entity =>
        {
            entity.HasKey(e => e.PkidSystemLog).HasName("CONSTRAINT_PK_SystemLog");

            entity.ToTable("SystemLog", "SIS");

            entity.Property(e => e.PkidSystemLog).HasColumnName("PKIdSystemLog");
            entity.Property(e => e.Category).HasMaxLength(24);
            entity.Property(e => e.Context).HasMaxLength(10);
            entity.Property(e => e.Date).HasDefaultValueSql("(sysdatetime())");
            entity.Property(e => e.EmployeeNo).HasMaxLength(24);
            entity.Property(e => e.Exception).HasMaxLength(4000);
            entity.Property(e => e.FkidOrigenLogMessageSis).HasColumnName("FKIdOrigenLogMessage_SIS");
            entity.Property(e => e.HostName).HasMaxLength(32);
            entity.Property(e => e.Ipclient)
                .HasMaxLength(24)
                .HasColumnName("IPClient");
            entity.Property(e => e.Level)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Logger)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.Message)
                .HasMaxLength(4000)
                .IsUnicode(false);
            entity.Property(e => e.MethodName).HasMaxLength(200);
            entity.Property(e => e.Parameters).HasMaxLength(4000);
            entity.Property(e => e.ProgName).HasMaxLength(256);
            entity.Property(e => e.Thread)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.Type).HasMaxLength(24);

            entity.HasOne(d => d.FkidOrigenLogMessageSisNavigation).WithMany(p => p.SystemLogs)
                .HasForeignKey(d => d.FkidOrigenLogMessageSis)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("CONSTRAINT_FK_SystemLog_OrigenLogMessage");
        });

        modelBuilder.Entity<SystemParamCatalog>(entity =>
        {
            entity.HasKey(e => e.PkidSystemParamCatalog).HasName("CONSTRAINT_PK_SystemParamCatalog");

            entity.ToTable("SystemParamCatalog", "SIS");

            entity.Property(e => e.PkidSystemParamCatalog)
                .ValueGeneratedNever()
                .HasColumnName("PKIdSystemParamCatalog");
            entity.Property(e => e.Activo).HasDefaultValue(true);
            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.FechaCreacion).HasDefaultValueSql("(sysdatetime())");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<SystemParamValue>(entity =>
        {
            entity.HasKey(e => e.PkidSystemParamValue).HasName("CONSTRAINT_PK_SystemParamValue");

            entity.ToTable("SystemParamValue", "SIS");

            entity.Property(e => e.PkidSystemParamValue)
                .ValueGeneratedNever()
                .HasColumnName("PKIdSystemParamValue");
            entity.Property(e => e.Activo).HasDefaultValue(true);
            entity.Property(e => e.Descripcion)
                .IsRequired()
                .HasMaxLength(128)
                .IsUnicode(false);
            entity.Property(e => e.FechaCreacion).HasDefaultValueSql("(sysdatetime())");
            entity.Property(e => e.FkidSystemParamCatalogSis).HasColumnName("FKIdSystemParamCatalog_SIS");
            entity.Property(e => e.Value).IsRequired();

            entity.HasOne(d => d.FkidSystemParamCatalogSisNavigation).WithMany(p => p.SystemParamValues)
                .HasForeignKey(d => d.FkidSystemParamCatalogSis)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("CONSTRAINT_FK_SystemParamCatalog_SystemParamValue");
        });

        modelBuilder.Entity<Usuario>(entity =>
        {
            entity.HasKey(e => e.PkIdUsuario).HasName("CONSTRAINT_PK_Usuario");

            entity.ToTable("Usuario", "SIS");

            entity.Property(e => e.Activo).HasDefaultValue(true);
            entity.Property(e => e.ApellidoMaterno)
                .IsRequired()
                .HasMaxLength(64);
            entity.Property(e => e.ApellidoPaterno)
                .IsRequired()
                .HasMaxLength(64);
            entity.Property(e => e.CodigoPostal).HasMaxLength(9);
            entity.Property(e => e.Direccion1)
                .IsRequired()
                .HasMaxLength(128);
            entity.Property(e => e.Direccion2)
                .IsRequired()
                .HasMaxLength(64);
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(60);
            entity.Property(e => e.FechaCreacion).HasDefaultValueSql("(sysdatetime())");
            entity.Property(e => e.FkidEmpresaSis).HasColumnName("FKIdEmpresa_SIS");
            entity.Property(e => e.Gafete)
                .IsRequired()
                .HasMaxLength(11);
            entity.Property(e => e.Iniciales)
                .IsRequired()
                .HasMaxLength(3);
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(64);
            entity.Property(e => e.NumeroSocial)
                .IsRequired()
                .HasMaxLength(12);
            entity.Property(e => e.PayrollId)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("PayrollID");
            entity.Property(e => e.Telefono)
                .IsRequired()
                .HasMaxLength(16);

            entity.HasOne(d => d.FkidEmpresaSisNavigation).WithMany(p => p.Usuarios)
                .HasForeignKey(d => d.FkidEmpresaSis)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("CONSTRAINT_FK_Usuario_Empresa");
        });

        modelBuilder.Entity<UsuarioSucursal>(entity =>
        {
            entity.HasKey(e => new { e.FkidUsuarioSis, e.FkidSucursalSis }).HasName("CONSTRAINT_PK_UsuarioSucursal");

            entity.ToTable("UsuarioSucursal", "SIS");

            entity.HasIndex(e => e.FkidDepartamentoSis, "IX_UsuarioSucursal_Departamento").HasFilter("([Activo]=(1))");

            entity.HasIndex(e => e.FkidSucursalSis, "IX_UsuarioSucursal_Sucursal").HasFilter("([Activo]=(1))");

            entity.HasIndex(e => new { e.FkidUsuarioSis, e.PuedeAcceder }, "IX_UsuarioSucursal_UsuarioAcceso").HasFilter("([Activo]=(1))");

            entity.Property(e => e.FkidUsuarioSis).HasColumnName("FKIdUsuario_SIS");
            entity.Property(e => e.FkidSucursalSis).HasColumnName("FKIdSucursal_SIS");
            entity.Property(e => e.Activo).HasDefaultValue(true);
            entity.Property(e => e.FechaAsignacion).HasDefaultValueSql("(sysdatetime())");
            entity.Property(e => e.FechaCreacion).HasDefaultValueSql("(sysdatetime())");
            entity.Property(e => e.FkidDepartamentoSis).HasColumnName("FKIdDepartamento_SIS");
            entity.Property(e => e.PuedeAcceder).HasDefaultValue(true);
            entity.Property(e => e.PuedeOperar).HasDefaultValue(true);
            entity.Property(e => e.UsuarioCreacion).HasMaxLength(100);
            entity.Property(e => e.UsuarioModificacion).HasMaxLength(100);

            entity.HasOne(d => d.FkidDepartamentoSisNavigation).WithMany(p => p.UsuarioSucursals)
                .HasForeignKey(d => d.FkidDepartamentoSis)
                .HasConstraintName("CONSTRAINT_FK_UsuarioSucursal_Departamento");

            entity.HasOne(d => d.FkidSucursalSisNavigation).WithMany(p => p.UsuarioSucursals)
                .HasForeignKey(d => d.FkidSucursalSis)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("CONSTRAINT_FK_UsuarioSucursal_Sucursal");

            entity.HasOne(d => d.FkidUsuarioSisNavigation).WithMany(p => p.UsuarioSucursals)
                .HasForeignKey(d => d.FkidUsuarioSis)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("CONSTRAINT_FK_UsuarioSucursal_Usuario");
        });

        modelBuilder.Entity<VwEmpresaDepartamanto>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("VW_EmpresaDepartamanto", "SIS");

            entity.Property(e => e.DepartamentoNombre)
                .IsRequired()
                .HasMaxLength(128);
            entity.Property(e => e.EmpresaNombre)
                .IsRequired()
                .HasMaxLength(128);
            entity.Property(e => e.PkidDepartamento).HasColumnName("PKIdDepartamento");
            entity.Property(e => e.PkidEmpresa).HasColumnName("PKIdEmpresa");
            entity.Property(e => e.Rfc)
                .IsRequired()
                .HasMaxLength(13)
                .HasColumnName("RFC");
        });

        modelBuilder.Entity<VwEstadoEmpresa>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("VW_EstadoEmpresa", "SIS");

            entity.Property(e => e.EmpresaNombre)
                .IsRequired()
                .HasMaxLength(128);
            entity.Property(e => e.EstadoNombre)
                .IsRequired()
                .HasMaxLength(64)
                .IsUnicode(false);
            entity.Property(e => e.PkidEmpresa).HasColumnName("PKIdEmpresa");
            entity.Property(e => e.PkidEstado).HasColumnName("PKIdEstado");
            entity.Property(e => e.Rfc)
                .IsRequired()
                .HasMaxLength(13)
                .HasColumnName("RFC");
        });

        modelBuilder.Entity<VwMenu>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("vw_Menu", "SIS");

            entity.Property(e => e.CreatedDateTime).HasColumnType("datetime");
            entity.Property(e => e.Estado)
                .IsRequired()
                .HasMaxLength(8)
                .IsUnicode(false);
            entity.Property(e => e.FkidMenuSis).HasColumnName("FKIdMenu_SIS");
            entity.Property(e => e.ImageUrl).HasMaxLength(120);
            entity.Property(e => e.LegacyName).HasMaxLength(80);
            entity.Property(e => e.Lenguaje)
                .IsRequired()
                .HasMaxLength(3)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.ModifiedDateTime).HasColumnType("datetime");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(150);
            entity.Property(e => e.NombreMenuPadre).HasMaxLength(150);
            entity.Property(e => e.PkidMenu).HasColumnName("PKIdMenu");
            entity.Property(e => e.Ruta).HasMaxLength(200);
            entity.Property(e => e.RutaCompleta).HasMaxLength(303);
            entity.Property(e => e.TipoDescripcion)
                .IsRequired()
                .HasMaxLength(27)
                .IsUnicode(false);
            entity.Property(e => e.TipoMenuPadreDescripcion)
                .IsRequired()
                .HasMaxLength(11)
                .IsUnicode(false);
            entity.Property(e => e.ValidacionEstructura)
                .IsRequired()
                .HasMaxLength(46)
                .IsUnicode(false);
        });

        modelBuilder.Entity<VwUsuarioSucursal>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("VW_UsuarioSucursal", "SIS");

            entity.Property(e => e.ApellidoMaterno)
                .IsRequired()
                .HasMaxLength(64);
            entity.Property(e => e.ApellidoPaterno)
                .IsRequired()
                .HasMaxLength(64);
            entity.Property(e => e.CodigoPostalUsuario).HasMaxLength(9);
            entity.Property(e => e.Direccion1)
                .IsRequired()
                .HasMaxLength(128);
            entity.Property(e => e.Direccion2)
                .IsRequired()
                .HasMaxLength(64);
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(60);
            entity.Property(e => e.Gafete)
                .IsRequired()
                .HasMaxLength(11);
            entity.Property(e => e.Iniciales)
                .IsRequired()
                .HasMaxLength(3);
            entity.Property(e => e.NombreCompleto)
                .IsRequired()
                .HasMaxLength(194);
            entity.Property(e => e.NombreEmpresa)
                .IsRequired()
                .HasMaxLength(128);
            entity.Property(e => e.NombreUsuario)
                .IsRequired()
                .HasMaxLength(64);
            entity.Property(e => e.NumeroSocial)
                .IsRequired()
                .HasMaxLength(12);
            entity.Property(e => e.PayrollId)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("PayrollID");
            entity.Property(e => e.RfcEmpresa)
                .IsRequired()
                .HasMaxLength(13);
            entity.Property(e => e.SexoDescripcion)
                .IsRequired()
                .HasMaxLength(9)
                .IsUnicode(false);
            entity.Property(e => e.TelefonoUsuario)
                .IsRequired()
                .HasMaxLength(16);
        });

        modelBuilder.Entity<VwUsuarioSucursalSimplificadum>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("VW_UsuarioSucursal_Simplificada", "SIS");

            entity.Property(e => e.Ciudad).HasMaxLength(100);
            entity.Property(e => e.CodigoSucursal)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.DepartamentoNombre).HasMaxLength(128);
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(60);
            entity.Property(e => e.EmpresaNombre)
                .IsRequired()
                .HasMaxLength(128);
            entity.Property(e => e.EmpresaRfc)
                .IsRequired()
                .HasMaxLength(13);
            entity.Property(e => e.Estado)
                .IsRequired()
                .HasMaxLength(64)
                .IsUnicode(false);
            entity.Property(e => e.Gafete)
                .IsRequired()
                .HasMaxLength(11);
            entity.Property(e => e.Iniciales)
                .IsRequired()
                .HasMaxLength(3);
            entity.Property(e => e.PayrollId)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("PayrollID");
            entity.Property(e => e.PkidSucursal).HasColumnName("PKIdSucursal");
            entity.Property(e => e.SucursalAlias).HasMaxLength(50);
            entity.Property(e => e.SucursalNombre)
                .IsRequired()
                .HasMaxLength(128);
            entity.Property(e => e.TipoSucursal).HasMaxLength(50);
            entity.Property(e => e.UsuarioNombre)
                .IsRequired()
                .HasMaxLength(194);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}