// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using EG.Infraestructure.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace EG.Infraestructure.Models
{
    public partial class EGestionContext
    {
        private IEGestionContextProcedures _procedures;

        public virtual IEGestionContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new EGestionContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IEGestionContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class EGestionContextProcedures : IEGestionContextProcedures
    {
        private readonly EGestionContext _context;

        public EGestionContextProcedures(EGestionContext context)
        {
            _context = context;
        }

        public virtual async Task<List<LoginInformationEmployeeResult>> LoginInformationEmployeeAsync(string payrollID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "PayrollID",
                    Size = 120,
                    Value = payrollID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<LoginInformationEmployeeResult>("EXEC @returnValue = [SIS].[LoginInformationEmployee] @PayrollID = @PayrollID", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<SP_CargaInicialConteoResult>> SP_CargaInicialConteoAsync(int? p_Partida, int? p_Periodo, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "P_Partida",
                    Value = p_Partida ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "P_Periodo",
                    Value = p_Periodo ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SP_CargaInicialConteoResult>("EXEC @returnValue = [ALMA].[SP_CargaInicialConteo] @P_Partida = @P_Partida, @P_Periodo = @P_Periodo", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> SP_CREATE_ClavePolizaAsync(int? fK_IdAnio__SIS, int? fK_IdMesConta__SIS, int? fK_IdTipoPolizaConta__SIS, int? cT_ModifiedBy, OutputParameter<string> clavePoliza, OutputParameter<string> error, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterClavePoliza = new SqlParameter
            {
                ParameterName = "ClavePoliza",
                Size = 20,
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = clavePoliza?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.NVarChar,
            };
            var parameterError = new SqlParameter
            {
                ParameterName = "Error",
                Size = -1,
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = error?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.NVarChar,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "FK_IdAnio__SIS",
                    Value = fK_IdAnio__SIS ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "FK_IdMesConta__SIS",
                    Value = fK_IdMesConta__SIS ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "FK_IdTipoPolizaConta__SIS",
                    Value = fK_IdTipoPolizaConta__SIS ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "CT_ModifiedBy",
                    Value = cT_ModifiedBy ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterClavePoliza,
                parameterError,
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [CONTA].[SP_CREATE_ClavePoliza] @FK_IdAnio__SIS = @FK_IdAnio__SIS, @FK_IdMesConta__SIS = @FK_IdMesConta__SIS, @FK_IdTipoPolizaConta__SIS = @FK_IdTipoPolizaConta__SIS, @CT_ModifiedBy = @CT_ModifiedBy, @ClavePoliza = @ClavePoliza OUTPUT, @Error = @Error OUTPUT", sqlParameters, cancellationToken);

            clavePoliza?.SetValue(parameterClavePoliza.Value);
            error?.SetValue(parameterError.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<SP_MantenimientoPolizaResult>> SP_MantenimientoPolizaAsync(int? action, int? pKIdPoliza, int? fKIdAnio_SIS, int? fKIdMes_SIS, int? fKIdTipoPoliza_SIS, string nombrePoliza, DateTime? fechaPoliza, bool? estaBalanceado, bool? permitirModificar, int? fKIdAccionAutorizar_SIS, bool? autorizado, DateTime? fechaSolicitud, DateTime? fechaAutorizacion, int? idUser, OutputParameter<int?> id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterId = new SqlParameter
            {
                ParameterName = "Id",
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = id?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.Int,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "Action",
                    Value = action ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "PKIdPoliza",
                    Value = pKIdPoliza ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "FKIdAnio_SIS",
                    Value = fKIdAnio_SIS ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "FKIdMes_SIS",
                    Value = fKIdMes_SIS ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "FKIdTipoPoliza_SIS",
                    Value = fKIdTipoPoliza_SIS ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "NombrePoliza",
                    Size = 2000,
                    Value = nombrePoliza ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "FechaPoliza",
                    Value = fechaPoliza ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.DateTime,
                },
                new SqlParameter
                {
                    ParameterName = "EstaBalanceado",
                    Value = estaBalanceado ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Bit,
                },
                new SqlParameter
                {
                    ParameterName = "PermitirModificar",
                    Value = permitirModificar ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Bit,
                },
                new SqlParameter
                {
                    ParameterName = "FKIdAccionAutorizar_SIS",
                    Value = fKIdAccionAutorizar_SIS ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "Autorizado",
                    Value = autorizado ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Bit,
                },
                new SqlParameter
                {
                    ParameterName = "FechaSolicitud",
                    Value = fechaSolicitud ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.DateTime,
                },
                new SqlParameter
                {
                    ParameterName = "FechaAutorizacion",
                    Value = fechaAutorizacion ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.DateTime,
                },
                new SqlParameter
                {
                    ParameterName = "IdUser",
                    Value = idUser ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterId,
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SP_MantenimientoPolizaResult>("EXEC @returnValue = [CONTA].[SP_MantenimientoPoliza] @Action = @Action, @PKIdPoliza = @PKIdPoliza, @FKIdAnio_SIS = @FKIdAnio_SIS, @FKIdMes_SIS = @FKIdMes_SIS, @FKIdTipoPoliza_SIS = @FKIdTipoPoliza_SIS, @NombrePoliza = @NombrePoliza, @FechaPoliza = @FechaPoliza, @EstaBalanceado = @EstaBalanceado, @PermitirModificar = @PermitirModificar, @FKIdAccionAutorizar_SIS = @FKIdAccionAutorizar_SIS, @Autorizado = @Autorizado, @FechaSolicitud = @FechaSolicitud, @FechaAutorizacion = @FechaAutorizacion, @IdUser = @IdUser, @Id = @Id OUTPUT", sqlParameters, cancellationToken);

            id?.SetValue(parameterId.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<SP_MantenimientoTipoBienResult>> SP_MantenimientoTipoBienAsync(int? action, int? pKIdTipoBien, int? fKIdGrupoBien_ALMA, int? fKIdNivel_ALMA, int? fKIdPartida_CONTA, int? fKIdCuentaContable_CONTA, int? fKIdUnidades_ALMA, int? fKIdLocalizacion_ALMA, int? fKIdUnidades_Equivalente, string codigoClave, string descripcion, decimal? depreciacionAnual, int? consecutivo, string cABMS, string identificador, decimal? existenciaMinima, decimal? existenciaMaxima, int? tiempoVida, int? pk_IdTratadoInt, decimal? cuota, bool? proveeduriaNac, bool? catalogoBasico, string cUCOP_PLUS, int? cantidad_Equivalente, int? idUser, OutputParameter<int?> id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterId = new SqlParameter
            {
                ParameterName = "Id",
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = id?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.Int,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "Action",
                    Value = action ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "PKIdTipoBien",
                    Value = pKIdTipoBien ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "FKIdGrupoBien_ALMA",
                    Value = fKIdGrupoBien_ALMA ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "FKIdNivel_ALMA",
                    Value = fKIdNivel_ALMA ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "FKIdPartida_CONTA",
                    Value = fKIdPartida_CONTA ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "FKIdCuentaContable_CONTA",
                    Value = fKIdCuentaContable_CONTA ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "FKIdUnidades_ALMA",
                    Value = fKIdUnidades_ALMA ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "FKIdLocalizacion_ALMA",
                    Value = fKIdLocalizacion_ALMA ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "FKIdUnidades_Equivalente",
                    Value = fKIdUnidades_Equivalente ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "CodigoClave",
                    Size = 400,
                    Value = codigoClave ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Descripcion",
                    Size = 2400,
                    Value = descripcion ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "DepreciacionAnual",
                    Precision = 18,
                    Scale = 4,
                    Value = depreciacionAnual ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Decimal,
                },
                new SqlParameter
                {
                    ParameterName = "Consecutivo",
                    Value = consecutivo ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "CABMS",
                    Size = 100,
                    Value = cABMS ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Identificador",
                    Size = 100,
                    Value = identificador ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "ExistenciaMinima",
                    Precision = 18,
                    Scale = 4,
                    Value = existenciaMinima ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Decimal,
                },
                new SqlParameter
                {
                    ParameterName = "ExistenciaMaxima",
                    Precision = 18,
                    Scale = 4,
                    Value = existenciaMaxima ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Decimal,
                },
                new SqlParameter
                {
                    ParameterName = "TiempoVida",
                    Value = tiempoVida ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "Pk_IdTratadoInt",
                    Value = pk_IdTratadoInt ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "Cuota",
                    Precision = 8,
                    Scale = 2,
                    Value = cuota ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Decimal,
                },
                new SqlParameter
                {
                    ParameterName = "ProveeduriaNac",
                    Value = proveeduriaNac ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Bit,
                },
                new SqlParameter
                {
                    ParameterName = "CatalogoBasico",
                    Value = catalogoBasico ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Bit,
                },
                new SqlParameter
                {
                    ParameterName = "CUCOP_PLUS",
                    Size = 25,
                    Value = cUCOP_PLUS ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Cantidad_Equivalente",
                    Value = cantidad_Equivalente ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "IdUser",
                    Value = idUser ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterId,
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SP_MantenimientoTipoBienResult>("EXEC @returnValue = [ALMA].[SP_MantenimientoTipoBien] @Action = @Action, @PKIdTipoBien = @PKIdTipoBien, @FKIdGrupoBien_ALMA = @FKIdGrupoBien_ALMA, @FKIdNivel_ALMA = @FKIdNivel_ALMA, @FKIdPartida_CONTA = @FKIdPartida_CONTA, @FKIdCuentaContable_CONTA = @FKIdCuentaContable_CONTA, @FKIdUnidades_ALMA = @FKIdUnidades_ALMA, @FKIdLocalizacion_ALMA = @FKIdLocalizacion_ALMA, @FKIdUnidades_Equivalente = @FKIdUnidades_Equivalente, @CodigoClave = @CodigoClave, @Descripcion = @Descripcion, @DepreciacionAnual = @DepreciacionAnual, @Consecutivo = @Consecutivo, @CABMS = @CABMS, @Identificador = @Identificador, @ExistenciaMinima = @ExistenciaMinima, @ExistenciaMaxima = @ExistenciaMaxima, @TiempoVida = @TiempoVida, @Pk_IdTratadoInt = @Pk_IdTratadoInt, @Cuota = @Cuota, @ProveeduriaNac = @ProveeduriaNac, @CatalogoBasico = @CatalogoBasico, @CUCOP_PLUS = @CUCOP_PLUS, @Cantidad_Equivalente = @Cantidad_Equivalente, @IdUser = @IdUser, @Id = @Id OUTPUT", sqlParameters, cancellationToken);

            id?.SetValue(parameterId.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> sp_RegistrarEntidadAsync(string grupo, string subGrupo, string nombreMenu, string ruta, string menuPadreNombre, string icono, int? orden, string descripcion, string codigo, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "Grupo",
                    Size = 200,
                    Value = grupo ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "SubGrupo",
                    Size = 200,
                    Value = subGrupo ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "NombreMenu",
                    Size = 300,
                    Value = nombreMenu ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Ruta",
                    Size = 400,
                    Value = ruta ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "MenuPadreNombre",
                    Size = 300,
                    Value = menuPadreNombre ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Icono",
                    Size = 240,
                    Value = icono ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Orden",
                    Value = orden ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "Descripcion",
                    Size = 400,
                    Value = descripcion ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Codigo",
                    Size = 20,
                    Value = codigo ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[sp_RegistrarEntidad] @Grupo = @Grupo, @SubGrupo = @SubGrupo, @NombreMenu = @NombreMenu, @Ruta = @Ruta, @MenuPadreNombre = @MenuPadreNombre, @Icono = @Icono, @Orden = @Orden, @Descripcion = @Descripcion, @Codigo = @Codigo", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<spAutorizarEgresoProyectadoResult>> spAutorizarEgresoProyectadoAsync(int? pKIdEgresoProyectado, int? usuarioAutorizacion, int? fKIdPoliza_CONTA, string descripcion, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "PKIdEgresoProyectado",
                    Value = pKIdEgresoProyectado ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "UsuarioAutorizacion",
                    Value = usuarioAutorizacion ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "FKIdPoliza_CONTA",
                    Value = fKIdPoliza_CONTA ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "Descripcion",
                    Size = 500,
                    Value = descripcion ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<spAutorizarEgresoProyectadoResult>("EXEC @returnValue = [PRES].[spAutorizarEgresoProyectado] @PKIdEgresoProyectado = @PKIdEgresoProyectado, @UsuarioAutorizacion = @UsuarioAutorizacion, @FKIdPoliza_CONTA = @FKIdPoliza_CONTA, @Descripcion = @Descripcion", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<spConfiguracionDeRolYClaimsResult>> spConfiguracionDeRolYClaimsAsync(string group, string subgroup, string code, string values, string description, string rolName, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "group",
                    Size = 200,
                    Value = group ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "subgroup",
                    Size = 200,
                    Value = subgroup ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "code",
                    Size = 20,
                    Value = code ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "values",
                    Size = -1,
                    Value = values ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "description",
                    Size = 400,
                    Value = description ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "rolName",
                    Size = 512,
                    Value = rolName ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<spConfiguracionDeRolYClaimsResult>("EXEC @returnValue = [dbo].[spConfiguracionDeRolYClaims] @group = @group, @subgroup = @subgroup, @code = @code, @values = @values, @description = @description, @rolName = @rolName", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<spEliminarUsuarioSucursalResult>> spEliminarUsuarioSucursalAsync(int? fkidUsuarioSis, int? fkidSucursalSis, string usuarioModificacion, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "FkidUsuarioSis",
                    Value = fkidUsuarioSis ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "FkidSucursalSis",
                    Value = fkidSucursalSis ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "UsuarioModificacion",
                    Size = 100,
                    Value = usuarioModificacion ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<spEliminarUsuarioSucursalResult>("EXEC @returnValue = [SIS].[spEliminarUsuarioSucursal] @FkidUsuarioSis = @FkidUsuarioSis, @FkidSucursalSis = @FkidSucursalSis, @UsuarioModificacion = @UsuarioModificacion", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<spGetClaimsByUserResult>> spGetClaimsByUserAsync(int? pkIdUser, bool? esParaLogin, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "PkIdUser",
                    Value = pkIdUser ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "EsParaLogin",
                    Value = esParaLogin ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Bit,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<spGetClaimsByUserResult>("EXEC @returnValue = [SIS].[spGetClaimsByUser] @PkIdUser = @PkIdUser, @EsParaLogin = @EsParaLogin", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<spNodeMenuResult>> spNodeMenuAsync(int? noEmploye, string lenguaje, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "NoEmploye",
                    Value = noEmploye ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "Lenguaje",
                    Size = 3,
                    Value = lenguaje ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Char,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<spNodeMenuResult>("EXEC @returnValue = [SIS].[spNodeMenu] @NoEmploye = @NoEmploye, @Lenguaje = @Lenguaje", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> WriteSystemLogAsync(string fK_IdOrigenLogMessage__SIS, string date, string _Type, string progName, string employeeNo, string category, string iPClient, string hostName, string thread, string level, string logger, string message, string exception, string context, string methodName, string parameters, string executionTime, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "FK_IdOrigenLogMessage__SIS",
                    Size = 48,
                    Value = fK_IdOrigenLogMessage__SIS ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Date",
                    Size = 48,
                    Value = date ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "_Type",
                    Size = 48,
                    Value = _Type ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "ProgName",
                    Size = 512,
                    Value = progName ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "EmployeeNo",
                    Size = 48,
                    Value = employeeNo ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Category",
                    Size = 48,
                    Value = category ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "IPClient",
                    Size = 48,
                    Value = iPClient ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "HostName",
                    Size = 64,
                    Value = hostName ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Thread",
                    Size = 510,
                    Value = thread ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Level",
                    Size = 40,
                    Value = level ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Logger",
                    Size = 510,
                    Value = logger ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Message",
                    Size = 8000,
                    Value = message ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Exception",
                    Size = 8000,
                    Value = exception ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Context",
                    Size = 20,
                    Value = context ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "MethodName",
                    Size = 400,
                    Value = methodName ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Parameters",
                    Size = 8000,
                    Value = parameters ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "ExecutionTime",
                    Size = 64,
                    Value = executionTime ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [SIS].[WriteSystemLog] @FK_IdOrigenLogMessage__SIS = @FK_IdOrigenLogMessage__SIS, @Date = @Date, @_Type = @_Type, @ProgName = @ProgName, @EmployeeNo = @EmployeeNo, @Category = @Category, @IPClient = @IPClient, @HostName = @HostName, @Thread = @Thread, @Level = @Level, @Logger = @Logger, @Message = @Message, @Exception = @Exception, @Context = @Context, @MethodName = @MethodName, @Parameters = @Parameters, @ExecutionTime = @ExecutionTime", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
