// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class EjercicioGasto
{
    public int PkidEjercicioGasto { get; set; }

    public int FkidPartidaGastoPbr { get; set; }

    public int Trimestre { get; set; }

    public decimal MontoEjercido { get; set; }

    public DateTime FechaCreacion { get; set; }
}