// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class EmpresaNomina
{
    public int PkidEmpresaNomina { get; set; }

    public string RazonSocial { get; set; }

    public string RegImss { get; set; }

    public string RegInfonavit { get; set; }

    public string CedEmpadronam { get; set; }

    public string NoFonacot { get; set; }

    public string UsAdmin { get; set; }

    public string EmailAdmin { get; set; }

    public int? FkidPeriodoPagoSis { get; set; }

    public decimal? PrimaRiesgoImss { get; set; }

    public bool UsaSueldoTabular { get; set; }

    public int? FkidTipoPagoNom { get; set; }

    public int? UsuarioCreacion { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public int? UsuarioModificacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public bool Activo { get; set; }

    public virtual ICollection<ContratoLaboral> ContratoLaborals { get; set; } = new List<ContratoLaboral>();

    public virtual ICollection<Persona> Personas { get; set; } = new List<Persona>();
}