// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class EstatusSolicitudSalidum
{
    public int PkidEstatusSolicitudSalida { get; set; }

    public string Descripcion { get; set; }

    public string Color { get; set; }

    public int Orden { get; set; }

    public bool EsFinal { get; set; }

    public bool Activo { get; set; }

    public DateTime FechaCreacion { get; set; }

    public int UsuarioCreacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public int? UsuarioModificacion { get; set; }

    public virtual ICollection<SolicitudSalidum> SolicitudSalida { get; set; } = new List<SolicitudSalidum>();
}