// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class EstadoBien
{
    public int PkidEstadoBien { get; set; }

    public string DescripcionGeneral { get; set; }

    public string DescripcionEspecifica { get; set; }

    public string DescripcionCorta { get; set; }

    public bool Activo { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public int UsuarioCreacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public int? UsuarioModificacion { get; set; }

    public virtual ICollection<Baja> BajaFkidEstadoBienAnteriorAlmaNavigations { get; set; } = new List<Baja>();

    public virtual ICollection<Baja> BajaFkidEstadoBienDestinoAlmaNavigations { get; set; } = new List<Baja>();

    public virtual ICollection<Bien> Biens { get; set; } = new List<Bien>();

    public virtual ICollection<ResguardoDetalle> ResguardoDetalles { get; set; } = new List<ResguardoDetalle>();

    public virtual ICollection<TipoBaja> TipoBajas { get; set; } = new List<TipoBaja>();

    public virtual Usuario UsuarioCreacionNavigation { get; set; }

    public virtual Usuario UsuarioModificacionNavigation { get; set; }
}