// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class EvaluacionConsistenciaPreguntum
{
    public int PkidPregunta { get; set; }

    public int Seccion { get; set; }

    public string SeccionNombre { get; set; }

    public int Numero { get; set; }

    public string Pregunta { get; set; }

    public string TipoRespuesta { get; set; }

    public decimal Peso { get; set; }

    public bool Activa { get; set; }

    public int Orden { get; set; }
}