// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class Factura
{
    public int PkidFactura { get; set; }

    public int FkidEmpresaSis { get; set; }

    public int FkidContratoPres { get; set; }

    public int FkidPolizaConta { get; set; }

    public string NumFactura { get; set; }

    public string SerieFactura { get; set; }

    public DateOnly FechaEmision { get; set; }

    public DateOnly? FechaRecepcion { get; set; }

    public decimal? Subtotal { get; set; }

    public decimal? Iva { get; set; }

    public decimal? Retencion { get; set; }

    public decimal Total { get; set; }

    public string Uuid { get; set; }

    public string FlDocto { get; set; }

    public string Observaciones { get; set; }

    public int Estatus { get; set; }

    public bool Activo { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public int UsuarioCreacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public int? UsuarioModificacion { get; set; }

    public byte[] RowVersion { get; set; }

    public virtual ICollection<Clcfactura> Clcfacturas { get; set; } = new List<Clcfactura>();

    public virtual ICollection<FacturaDetalle> FacturaDetalles { get; set; } = new List<FacturaDetalle>();

    public virtual Contrato1 FkidContratoPresNavigation { get; set; }

    public virtual Empresa FkidEmpresaSisNavigation { get; set; }

    public virtual Poliza FkidPolizaContaNavigation { get; set; }

    public virtual Usuario UsuarioCreacionNavigation { get; set; }

    public virtual Usuario UsuarioModificacionNavigation { get; set; }
}