// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class FuenteFinanciamiento
{
    public int PkidFuenteFinanciamiento { get; set; }

    public string Clave { get; set; }

    public string Descripcion { get; set; }

    public string Ff { get; set; }

    public string Fg { get; set; }

    public string Fe { get; set; }

    public string Ad { get; set; }

    public string Ori { get; set; }

    public bool Activo { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public int UsuarioCreacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public int? UsuarioModificacion { get; set; }

    public virtual ICollection<EgresoAutorizado> EgresoAutorizados { get; set; } = new List<EgresoAutorizado>();

    public virtual ICollection<EgresoProyectado> EgresoProyectados { get; set; } = new List<EgresoProyectado>();

    public virtual ICollection<Paaa> Paaas { get; set; } = new List<Paaa>();

    public virtual ICollection<Requisicion> Requisicions { get; set; } = new List<Requisicion>();

    public virtual Usuario UsuarioCreacionNavigation { get; set; }

    public virtual Usuario UsuarioModificacionNavigation { get; set; }
}