// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class FundamentoProcedimiento
{
    public long PkidFundamentoProcedimiento { get; set; }

    public int FkidProcedimientoContratacionOrco { get; set; }

    public int FkidNormaJuridicaVersionSis { get; set; }

    public string Articulo { get; set; }

    public string Fraccion { get; set; }

    public string Fundamento { get; set; }

    public string Motivacion { get; set; }

    public bool EsExcepcion { get; set; }

    public bool Activo { get; set; }

    public DateTime FechaCreacion { get; set; }

    public int UsuarioCreacion { get; set; }

    public virtual NormaJuridicaVersion FkidNormaJuridicaVersionSisNavigation { get; set; }
}