// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class GrupoBien
{
    public int PkidGrupoBien { get; set; }

    public int FkidFamiliaAlma { get; set; }

    public string Descripcion { get; set; }

    public int? Clave { get; set; }

    public string ClaveAn { get; set; }

    public string CabmAct { get; set; }

    public string ClaveCucop { get; set; }

    public string Medida { get; set; }

    public bool Activo { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public int UsuarioCreacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public int? UsuarioModificacion { get; set; }

    public virtual Familium FkidFamiliaAlmaNavigation { get; set; }

    public virtual ICollection<TipoBien> TipoBiens { get; set; } = new List<TipoBien>();
}