// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class HistorialEstatusArticulo
{
    public int PkidHistorial { get; set; }

    public int FkidArticuloConteoAlma { get; set; }

    public int? FkidEstatusAnteriorAlma { get; set; }

    public int FkidEstatusNuevoAlma { get; set; }

    public int? FkidRegistroConteoAlma { get; set; }

    public string Observaciones { get; set; }

    public int FkidUsuarioSis { get; set; }

    public DateTime? FechaCambio { get; set; }

    public virtual ArticuloConteo FkidArticuloConteoAlmaNavigation { get; set; }

    public virtual EstatusArticuloConteo FkidEstatusAnteriorAlmaNavigation { get; set; }

    public virtual EstatusArticuloConteo FkidEstatusNuevoAlmaNavigation { get; set; }

    public virtual RegistroConteo FkidRegistroConteoAlmaNavigation { get; set; }

    public virtual Usuario FkidUsuarioSisNavigation { get; set; }
}