// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class HistSaldoMensual
{
    public int PkidHistSaldoMensual { get; set; }

    public int? FkidCuenta { get; set; }

    public int? FkidAnioSis { get; set; }

    public int? FkidMesSis { get; set; }

    public int? Anio { get; set; }

    public string Mes { get; set; }

    public string Cuentastr { get; set; }

    public string NombreCta { get; set; }

    public string CuentastrEsp { get; set; }

    public string NombreCtaEsp { get; set; }

    public decimal? SaldoInicial { get; set; }

    public decimal? Cargos { get; set; }

    public decimal? Abonos { get; set; }

    public decimal? SaldoFinal { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public int? Nivel { get; set; }
}