// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using EG.Infraestructure.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace EG.Infraestructure.Models
{
    public partial interface IEGestionContextProcedures
    {
        Task<List<LoginInformationEmployeeResult>> LoginInformationEmployeeAsync(string payrollID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_CargaInicialConteoResult>> SP_CargaInicialConteoAsync(int? p_Partida, int? p_Periodo, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_MantenimientoTipoBienResult>> SP_MantenimientoTipoBienAsync(int? action, int? pKIdTipoBien, int? fKIdGrupoBien_ALMA, int? fKIdNivel_ALMA, int? fKIdPartida_CONTA, int? fKIdCuentaContable_CONTA, int? fKIdUnidades_ALMA, int? fKIdLocalizacion_ALMA, int? fKIdUnidades_Equivalente, string codigoClave, string descripcion, decimal? depreciacionAnual, int? consecutivo, string cABMS, string identificador, decimal? existenciaMinima, decimal? existenciaMaxima, int? tiempoVida, int? pk_IdTratadoInt, decimal? cuota, bool? proveeduriaNac, bool? catalogoBasico, string cUCOP_PLUS, int? cantidad_Equivalente, int? idC, int? idUser, OutputParameter<int?> id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> sp_RegistrarEntidadAsync(string grupo, string subGrupo, string nombreMenu, string ruta, string menuPadreNombre, string icono, int? orden, string descripcion, string codigo, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spAutorizarEgresoProyectadoResult>> spAutorizarEgresoProyectadoAsync(int? pKIdEgresoProyectado, int? usuarioAutorizacion, int? fKIdPoliza_CONTA, string descripcion, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spConfiguracionDeRolYClaimsResult>> spConfiguracionDeRolYClaimsAsync(string group, string subgroup, string code, string values, string description, string rolName, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spEliminarUsuarioSucursalResult>> spEliminarUsuarioSucursalAsync(int? fkidUsuarioSis, int? fkidSucursalSis, string usuarioModificacion, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetClaimsByUserResult>> spGetClaimsByUserAsync(int? pkIdUser, bool? esParaLogin, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spNodeMenuResult>> spNodeMenuAsync(int? noEmploye, string lenguaje, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> WriteSystemLogAsync(string fK_IdOrigenLogMessage__SIS, string date, string _Type, string progName, string employeeNo, string category, string iPClient, string hostName, string thread, string level, string logger, string message, string exception, string context, string methodName, string parameters, string executionTime, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
