// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class Incidencium
{
    public int PkidIncidencia { get; set; }

    public int FkidPersonaNom { get; set; }

    public int? FkidTipoIncidenciaNom { get; set; }

    public DateOnly? Fecha { get; set; }

    public string Comentario { get; set; }

    public int? FkidTipoJustificacionNom { get; set; }

    public bool? AplicaDescuento { get; set; }

    public string ComentarioJustificacion { get; set; }

    public int? FkidPeriodoQuincenalSis { get; set; }

    public int? UsuarioCreacion { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public int? UsuarioModificacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public bool Activo { get; set; }

    public virtual Persona FkidPersonaNomNavigation { get; set; }

    public virtual CatalogoSimple FkidTipoIncidenciaNomNavigation { get; set; }

    public virtual CatalogoSimple FkidTipoJustificacionNomNavigation { get; set; }
}