// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class Infonavit
{
    public int PkidInfonavit { get; set; }

    public int FkidPersonaNom { get; set; }

    public int FkidUnidadInfonavitNom { get; set; }

    public string MotivoInfonavit { get; set; }

    public decimal ImporteInfonavit { get; set; }

    public decimal TasaInteres { get; set; }

    public int NumeroPagos { get; set; }

    public int FkidPeriodoInicial { get; set; }

    public decimal ImportePago { get; set; }

    public int? UsuarioCreacion { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public int? UsuarioModificacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public bool Activo { get; set; }

    public int? FkidPeriodoFinal { get; set; }

    public DateOnly FechaInicial { get; set; }

    public DateOnly FechaFinal { get; set; }
}