// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class Instrumento
{
    public int PkidInstrumento { get; set; }

    public int FkidEmpresaSis { get; set; }

    public int FkidTipoInversionTes { get; set; }

    public int FkidIntermediarioFinancieroTes { get; set; }

    public int? FkidTipoPlazoTes { get; set; }

    public int FkidTipoMonedaTes { get; set; }

    public string Nombre { get; set; }

    public decimal? TasaInteres { get; set; }

    public int? PlazoOriginal { get; set; }

    public DateOnly? FechaEmision { get; set; }

    public DateOnly? FechaVencimiento { get; set; }

    public decimal? MontoMinimo { get; set; }

    public string Observaciones { get; set; }

    public bool Activo { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public int UsuarioCreacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public int? UsuarioModificacion { get; set; }

    public virtual Empresa FkidEmpresaSisNavigation { get; set; }

    public virtual IntermediarioFinanciero FkidIntermediarioFinancieroTesNavigation { get; set; }

    public virtual TipoInversion FkidTipoInversionTesNavigation { get; set; }

    public virtual TipoMonedum FkidTipoMonedaTesNavigation { get; set; }

    public virtual TipoPlazo FkidTipoPlazoTesNavigation { get; set; }

    public virtual ICollection<Inversion> Inversions { get; set; } = new List<Inversion>();

    public virtual Usuario UsuarioCreacionNavigation { get; set; }

    public virtual Usuario UsuarioModificacionNavigation { get; set; }
}