// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class InventarioDetHist
{
    public int PkidInventarioDetalleHist { get; set; }

    public int FkidInventarioDetalleAlma { get; set; }

    public int FkidInventarioAlma { get; set; }

    public int FkidBienAlma { get; set; }

    public string AccionHist { get; set; }

    public string ClaveBien { get; set; }

    public string DescripcionBien { get; set; }

    public string Serie { get; set; }

    public string UbicacionSistema { get; set; }

    public string UbicacionFisica { get; set; }

    public bool? Localizado { get; set; }

    public bool? TieneDiferencia { get; set; }

    public string Observaciones { get; set; }

    public bool Activo { get; set; }

    public DateTime FechaHist { get; set; }

    public int UsuarioHist { get; set; }
}