// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class MatrizIngreso
{
    public int PkIdMatrizIngreso { get; set; }

    public int? FkIdPrograma { get; set; }

    public int? FkIdOrigen { get; set; }

    public int? FkIdCuentaContableAutorizado { get; set; }

    public int? FkIdCuentaContablePorEjercer { get; set; }

    public int? FkIdCuentaContableModificado { get; set; }

    public int? FkIdCuentaContableDevengado { get; set; }

    public int? FkIdCuentaContableRecaudado { get; set; }

    public int? FkIdCuentaContableDeposito { get; set; }

    public int? FkIdAnioSis { get; set; }

    public bool Activo { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public int UsuarioCreacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public int? UsuarioModificacion { get; set; }

    public virtual Anio FkIdAnioSisNavigation { get; set; }

    public virtual CuentaContable FkIdCuentaContableAutorizadoNavigation { get; set; }

    public virtual CuentaContable FkIdCuentaContableDepositoNavigation { get; set; }

    public virtual CuentaContable FkIdCuentaContableDevengadoNavigation { get; set; }

    public virtual CuentaContable FkIdCuentaContableModificadoNavigation { get; set; }

    public virtual CuentaContable FkIdCuentaContablePorEjercerNavigation { get; set; }

    public virtual CuentaContable FkIdCuentaContableRecaudadoNavigation { get; set; }

    public virtual Origen FkIdOrigenNavigation { get; set; }

    public virtual Programa FkIdProgramaNavigation { get; set; }

    public virtual Usuario UsuarioCreacionNavigation { get; set; }

    public virtual Usuario UsuarioModificacionNavigation { get; set; }
}