// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class MatrizConversion
{
    public int PkidMatrizConversion { get; set; }

    public int FkidAnioSis { get; set; }

    public int FkidProgramaPres { get; set; }

    public int FkidPartidaSis { get; set; }

    public int FkidTipoGastoPres { get; set; }

    public int FkidCuentaContableAprobado { get; set; }

    public int FkidCuentaContablePorEjercer { get; set; }

    public int FkidCuentaContableModificado { get; set; }

    public int FkidCuentaContableComprometido { get; set; }

    public int FkidCuentaContableDevengado { get; set; }

    public int FkidCuentaContableEjercido { get; set; }

    public int FkidCuentaContablePagado { get; set; }

    public int FkidCuentaContableGasto { get; set; }

    public bool Activo { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public int UsuarioCreacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public int? UsuarioModificacion { get; set; }

    public virtual Anio FkidAnioSisNavigation { get; set; }

    public virtual CuentaContable FkidCuentaContableAprobadoNavigation { get; set; }

    public virtual CuentaContable FkidCuentaContableComprometidoNavigation { get; set; }

    public virtual CuentaContable FkidCuentaContableDevengadoNavigation { get; set; }

    public virtual CuentaContable FkidCuentaContableEjercidoNavigation { get; set; }

    public virtual CuentaContable FkidCuentaContableGastoNavigation { get; set; }

    public virtual CuentaContable FkidCuentaContableModificadoNavigation { get; set; }

    public virtual CuentaContable FkidCuentaContablePagadoNavigation { get; set; }

    public virtual CuentaContable FkidCuentaContablePorEjercerNavigation { get; set; }

    public virtual Partidum1 FkidPartidaSisNavigation { get; set; }

    public virtual Programa FkidProgramaPresNavigation { get; set; }

    public virtual TipoGasto FkidTipoGastoPresNavigation { get; set; }

    public virtual Usuario UsuarioCreacionNavigation { get; set; }

    public virtual Usuario UsuarioModificacionNavigation { get; set; }
}
