// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class MirNivel
{
    public int PkidMirNivel { get; set; }

    public int FkidProgramaPresupuestarioPbr { get; set; }

    public string Nivel { get; set; }

    public string Objetivo { get; set; }

    public string Descripcion { get; set; }

    public int Orden { get; set; }

    public DateTime FechaCreacion { get; set; }

    public DateTime? FechaModificacion { get; set; }
}