// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class MirVersion
{
    public int PkidMirVersion { get; set; }

    public int FkidProgramaPresupuestarioPbr { get; set; }

    public int Version { get; set; }

    public string Snapshot { get; set; }

    public int FkidUsuarioPbr { get; set; }

    public string Comentario { get; set; }

    public DateTime FechaCreacion { get; set; }
}