// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class MotivoMovimiento
{
    public int PkidMotivoMovimiento { get; set; }

    public int? FkidMovimientoRh { get; set; }

    public int? FkidClaseMovimientoRh { get; set; }

    public string ClaseMovimiento { get; set; }

    public int? Clave { get; set; }

    public int? Motivo { get; set; }

    public string Descripcion { get; set; }

    public int? UsuarioCreacion { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public int? UsuarioModificacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public bool Activo { get; set; }
}