// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EG.Infraestructure.Models
{
    public partial class NOM_SP_Pension_Quincenal_INVEAResult
    {
        public int PKIdPension { get; set; }
        public int FKIdPersona_NOM { get; set; }
        [StringLength(150)]
        public string NombreBeneficiario { get; set; }
        [StringLength(50)]
        public string Documento { get; set; }
        public DateOnly? FechaDocumento { get; set; }
        [Column("Porcentaje", TypeName = "decimal(9,4)")]
        public decimal? Porcentaje { get; set; }
        public int? FKIdTipoPension_NOM { get; set; }
        public DateTime? FechaInicio { get; set; }
        public DateTime? FechaFin { get; set; }
        [StringLength(50)]
        public string Banco { get; set; }
        [StringLength(50)]
        public string CuentaBancaria { get; set; }
        [StringLength(50)]
        public string Clabe { get; set; }
        [StringLength(50)]
        public string FormaPago { get; set; }
        public int? FKIdCuentaContable_SIS { get; set; }
        public int? UsuarioCreacion { get; set; }
        public DateTime? FechaCreacion { get; set; }
        public int? UsuarioModificacion { get; set; }
        public DateTime? FechaModificacion { get; set; }
        public bool Activo { get; set; }
        [StringLength(15)]
        public string ClavePersona { get; set; }
        [StringLength(152)]
        public string NombreCompleto { get; set; }
        [StringLength(15)]
        public string RFC { get; set; }
        [StringLength(18)]
        public string CURP { get; set; }
        [StringLength(32)]
        public string TipoPensionDescripcion { get; set; }
        public bool? TipoPensionActivo { get; set; }
        [StringLength(5)]
        public string CuentaContable { get; set; }
        [StringLength(5)]
        public string SubCuentaContable { get; set; }
        [StringLength(5)]
        public string SubSubCuentaContable { get; set; }
        [StringLength(5)]
        public string SubSubSubCuentaContable { get; set; }
        [StringLength(5)]
        public string SubSubSubSubCuentaContable { get; set; }
        [StringLength(250)]
        public string CuentaContableDescripcion { get; set; }
        public bool? CuentaContableActivo { get; set; }
    }
}
