// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EG.Infraestructure.Models
{
    public partial class NOM_SBC_ActualXEmpresaResult
    {
        public int Fk_IdContrato { get; set; }
        public int Fk_IdEmpresa__EMP { get; set; }
        public int Fk_IdPersona__RH { get; set; }
        public int? Fk_IdPeriodo { get; set; }
        [Column("SueldoMensual", TypeName = "decimal(18,2)")]
        public decimal SueldoMensual { get; set; }
        [Column("SalarioDiario", TypeName = "decimal(19,4)")]
        public decimal? SalarioDiario { get; set; }
        [Column("SBC", TypeName = "decimal(19,4)")]
        public decimal? SBC { get; set; }
        public bool Activo { get; set; }
    }
}
