// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EG.Infraestructure.Models
{
    public partial class NOM_SD_ISR_LiqFiniqResult
    {
        public int? Fk_IdContrato { get; set; }
        public int? Fk_IdConcepto__NOM { get; set; }
        public DateOnly? FechaFinContrato { get; set; }
        [Column("BaseGravable", TypeName = "decimal(19,4)")]
        public decimal? BaseGravable { get; set; }
        [Column("ISR_Estimado", TypeName = "decimal(19,4)")]
        public decimal? ISR_Estimado { get; set; }
        [StringLength(65)]
        public string Observaciones { get; set; }
    }
}
