// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EG.Infraestructure.Models
{
    public partial class NOM_SP_Credito_QuincenalResult
    {
        public int PKIdCredito { get; set; }
        public int? EmpresaId { get; set; }
        [StringLength(128)]
        public string EmpresaNombre { get; set; }
        public int PersonaId { get; set; }
        [StringLength(170)]
        public string PersonaClaveNombre { get; set; }
        public int ContratoTerceroId { get; set; }
        [StringLength(80)]
        public string NombreContrato { get; set; }
        [StringLength(80)]
        public string MotivoCredito { get; set; }
        [Column("ImporteCredito", TypeName = "decimal(19,4)")]
        public decimal? ImporteCredito { get; set; }
        [Column("TasaInteres", TypeName = "decimal(19,4)")]
        public decimal? TasaInteres { get; set; }
        public int NumeroPagos { get; set; }
        public int PeriodoInicialId { get; set; }
        [Column("ImportePago", TypeName = "decimal(19,4)")]
        public decimal? ImportePago { get; set; }
        public int? PagosRegistrados { get; set; }
        public int? PagosDescontados { get; set; }
        [Column("SaldoEstimado", TypeName = "decimal(19,4)")]
        public decimal? SaldoEstimado { get; set; }
        public bool Activo { get; set; }
        public DateTime? FechaCreacion { get; set; }
        public int? UsuarioCreacion { get; set; }
        public DateTime? FechaModificacion { get; set; }
        public int? UsuarioModificacion { get; set; }
    }
}
