// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class NormaJuridicaVersion
{
    public int PkidNormaJuridicaVersion { get; set; }

    public int FkidNormaJuridicaSis { get; set; }

    public string IdentificadorVersion { get; set; }

    public DateOnly Publicacion { get; set; }

    public DateOnly VigenciaDesde { get; set; }

    public DateOnly? VigenciaHasta { get; set; }

    public string UrlFuenteOficial { get; set; }

    public string HuellaDocumento { get; set; }

    public bool Activo { get; set; }

    public DateTime FechaCreacion { get; set; }

    public int UsuarioCreacion { get; set; }

    public virtual NormaJuridica FkidNormaJuridicaSisNavigation { get; set; }

    public virtual ICollection<FundamentoProcedimiento> FundamentoProcedimientos { get; set; } = new List<FundamentoProcedimiento>();
}