// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class NotificacionTipo
{
    public int PkIdNotificacionTipo { get; set; }

    public string Clave { get; set; }

    public string Descripcion { get; set; }

    public bool Activo { get; set; }

    public virtual ICollection<Notificacion> Notificacions { get; set; } = new List<Notificacion>();
}