// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class OrdenCompraPartidum
{
    public int PkidOrdenCompraPartida { get; set; }

    public int FkidOrdenCompraOrco { get; set; }

    public int FkidPartidaConta { get; set; }

    public int? FkidFuenteFinanciamientoPres { get; set; }

    public decimal Importe { get; set; }

    public string Observaciones { get; set; }

    public bool Activo { get; set; }

    public DateTime FechaCreacion { get; set; }

    public int UsuarioCreacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public int? UsuarioModificacion { get; set; }

    public virtual FuenteFinanciamiento FkidFuenteFinanciamientoPresNavigation { get; set; }

    public virtual OrdenCompra FkidOrdenCompraOrcoNavigation { get; set; }

    public virtual Partidum FkidPartidaContaNavigation { get; set; }
}