// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class Paaa
{
    public int PkidPaaas { get; set; }

    public int FkidEmpresaSis { get; set; }

    public int FkidAnioSis { get; set; }

    public int FkidAreaSis { get; set; }

    public int FkidPersonaNom { get; set; }

    public string Descripcion { get; set; }

    public string Observaciones { get; set; }

    public DateTime Fecha { get; set; }

    public int? FkidProyectoOrco { get; set; }

    public int? FkidProgramaPres { get; set; }

    public int? FkidFuenteFinanciamientoPres { get; set; }

    public bool Activo { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public int UsuarioCreacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public int? UsuarioModificacion { get; set; }

    public virtual Anio FkidAnioSisNavigation { get; set; }

    public virtual Area FkidAreaSisNavigation { get; set; }

    public virtual Empresa FkidEmpresaSisNavigation { get; set; }

    public virtual FuenteFinanciamiento FkidFuenteFinanciamientoPresNavigation { get; set; }

    public virtual Persona FkidPersonaNomNavigation { get; set; }

    public virtual Programa FkidProgramaPresNavigation { get; set; }

    public virtual Proyecto FkidProyectoOrcoNavigation { get; set; }

    public virtual ICollection<Paaaspartidum> Paaaspartida { get; set; } = new List<Paaaspartidum>();

    public virtual Usuario UsuarioCreacionNavigation { get; set; }

    public virtual Usuario UsuarioModificacionNavigation { get; set; }
}