// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class Paaasdetalle
{
    public int PkidPaaasdetalle { get; set; }

    public int FkidEmpresaSis { get; set; }

    public int FkidPaaaspartidaOrco { get; set; }

    public int FkidTipoBienAlma { get; set; }

    public int? FkidUnidadesAlma { get; set; }

    public decimal Cantidad { get; set; }

    public string Observaciones { get; set; }

    public string LugarEntrega { get; set; }

    public bool Activo { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public int UsuarioCreacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public int? UsuarioModificacion { get; set; }

    public virtual ICollection<EstudioMercadoDetalle> EstudioMercadoDetalles { get; set; } = new List<EstudioMercadoDetalle>();

    public virtual Empresa FkidEmpresaSisNavigation { get; set; }

    public virtual Paaaspartidum FkidPaaaspartidaOrcoNavigation { get; set; }

    public virtual TipoBien FkidTipoBienAlmaNavigation { get; set; }

    public virtual Unidade FkidUnidadesAlmaNavigation { get; set; }
}