// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class Persona
{
    public int PkidPersona { get; set; }

    public string Clave { get; set; }

    public string Iniciales { get; set; }

    public string Nombre { get; set; }

    public string Paterno { get; set; }

    public string Materno { get; set; }

    public string Sexo { get; set; }

    public DateTime FechaNacimiento { get; set; }

    public string EstadoCivil { get; set; }

    public string Rfc { get; set; }

    public string Curp { get; set; }

    public string RegImss { get; set; }

    public string NoCartilla { get; set; }

    public string NoLicencia { get; set; }

    public string NoPasaporte { get; set; }

    public string NoCredencialElector { get; set; }

    public string Gafete { get; set; }

    public string CorreoElectronico { get; set; }

    public string TelefonoParticular { get; set; }

    public string TelefonoMovil { get; set; }

    public string Calle { get; set; }

    public string NumExterior { get; set; }

    public string NumInterior { get; set; }

    public string Colonia { get; set; }

    public string Cp { get; set; }

    public string Municipio { get; set; }

    public string Estado { get; set; }

    public DateTime FechaDeInicio { get; set; }

    public DateTime? FechaFin { get; set; }

    public string TipoContratacion { get; set; }

    public string Puesto { get; set; }

    public double? SueldoBase { get; set; }

    public double? CompensacionGarantizada { get; set; }

    public string Banco { get; set; }

    public string NumeroCuenta { get; set; }

    public string Clabe { get; set; }

    public bool Activo { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public int UsuarioCreacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public int? UsuarioModificacion { get; set; }

    public virtual ICollection<ConteoDetalleEscaneo> ConteoDetalleEscaneos { get; set; } = new List<ConteoDetalleEscaneo>();

    public virtual ICollection<ConteoDetalle> ConteoDetalles { get; set; } = new List<ConteoDetalle>();

    public virtual ICollection<EstudioMercado> EstudioMercados { get; set; } = new List<EstudioMercado>();

    public virtual ICollection<Paaa> Paaas { get; set; } = new List<Paaa>();

    public virtual ICollection<PersonaArea> PersonaAreas { get; set; } = new List<PersonaArea>();

    public virtual ICollection<Requisicion> RequisicionFkidAutorizoNomNavigations { get; set; } = new List<Requisicion>();

    public virtual ICollection<Requisicion> RequisicionFkidJefeAlmacenNomNavigations { get; set; } = new List<Requisicion>();

    public virtual ICollection<Requisicion> RequisicionFkidPautorizoNomNavigations { get; set; } = new List<Requisicion>();

    public virtual ICollection<Requisicion> RequisicionFkidPersonaNomNavigations { get; set; } = new List<Requisicion>();

    public virtual ICollection<Requisicion> RequisicionFkidPjefeAlmacenNomNavigations { get; set; } = new List<Requisicion>();

    public virtual ICollection<Requisicion> RequisicionFkidPsolicitaNomNavigations { get; set; } = new List<Requisicion>();

    public virtual ICollection<Requisicion> RequisicionFkidPsuficienciaNomNavigations { get; set; } = new List<Requisicion>();

    public virtual ICollection<Requisicion> RequisicionFkidPsupervisoNomNavigations { get; set; } = new List<Requisicion>();

    public virtual ICollection<Requisicion> RequisicionFkidSupervisoNomNavigations { get; set; } = new List<Requisicion>();

    public virtual Usuario UsuarioCreacionNavigation { get; set; }

    public virtual Usuario UsuarioModificacionNavigation { get; set; }

    public virtual ICollection<Usuario> Usuarios { get; set; } = new List<Usuario>();
}