// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class PivotBien
{
    public string Clave { get; set; }

    public string ClaveAnt { get; set; }

    public string GrupoBien { get; set; }

    public string TipoBien { get; set; }

    public string Area { get; set; }

    public string Descripcion { get; set; }

    public string Marca { get; set; }

    public string Modelo { get; set; }

    public string Factura { get; set; }

    public string Requisicion { get; set; }

    public string Proveedor { get; set; }

    public decimal? Costo { get; set; }

    public string Estadobien { get; set; }

    public DateTime? FechaAdq { get; set; }

    public string Referencia { get; set; }

    public string Notas { get; set; }

    public string Persona { get; set; }

    public string Serie { get; set; }

    public string Ubicacion { get; set; }

    public string TipoPatrimonio { get; set; }

    public string Aadquisicion { get; set; }

    public string Material { get; set; }

    public string Color { get; set; }

    public string Frente { get; set; }

    public string Fondo { get; set; }

    public string Altura { get; set; }

    public string Diametro { get; set; }

    public int VerificacionesDias { get; set; }

    public int MantenimientoDias { get; set; }

    public bool Mantenimiento { get; set; }

    public bool Calibracion { get; set; }

    public string Rango { get; set; }

    public string Resolucion { get; set; }

    public int? FkIdAreaUltSis { get; set; }

    public DateTime? FechaUltInv { get; set; }

    public string Partida { get; set; }

    public string TipoAdq { get; set; }

    public DateTime? FechaReqscn { get; set; }

    public string Caracteristicas { get; set; }

    public int? Resguardo { get; set; }

    public int? ResguardoAnterior { get; set; }

    public int? RelId { get; set; }

    public decimal? ValorRescate { get; set; }

    public decimal? ValorActual { get; set; }

    public string Antiguedad { get; set; }

    public int? Progresivo { get; set; }

    public int? Consecutivo { get; set; }

    public decimal? DetaOrdenCompra { get; set; }

    public string ClaveHist { get; set; }

    public DateTime? FechaResguardado { get; set; }

    public string EstaResguardado { get; set; }

    public int PkIdBien { get; set; }
}