// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class PlazaAutorizadum1
{
    public int PkIdPlazaAutorizada { get; set; }

    public int? FkIdPuestoRhct { get; set; }

    public int? FkIdPuestoRh { get; set; }

    public int? FkIdAreaSis { get; set; }

    public int? FkIdSituacionPlazaRh { get; set; }

    public int? Plaza { get; set; }

    public DateTime? FechaInicio { get; set; }

    public DateTime? FechaFin { get; set; }

    public int? TipoPlaza { get; set; }

    public string Documento { get; set; }

    public DateTime? FechaDocumento { get; set; }

    public string Descripcion { get; set; }

    public int? FkIdEmpresaEmp { get; set; }

    public int? UsuarioCreacion { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public int? UsuarioModificacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public bool Activo { get; set; }

    public int? CtCreatedBy { get; set; }

    public DateTime? CtCreatedDate { get; set; }

    public int? CtModifiedBy { get; set; }

    public DateTime? CtModifiedDate { get; set; }

    public bool CtLive { get; set; }
}