// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class PlazaAutorizadum
{
    public int PkidPlazaAutorizada { get; set; }

    public int? FkidPuestoNom { get; set; }

    public int? FkidAreaSis { get; set; }

    public int? FkidSituacionPlazaRh { get; set; }

    public string SituacionPlaza { get; set; }

    public int? Plaza { get; set; }

    public DateTime? FechaInicio { get; set; }

    public DateTime? FechaFin { get; set; }

    public int? TipoPlaza { get; set; }

    public string Documento { get; set; }

    public DateTime? FechaDocumento { get; set; }

    public string Descripcion { get; set; }

    public int? FkidEmpresaSis { get; set; }

    public int? UsuarioCreacion { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public int? UsuarioModificacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public bool Activo { get; set; }

    public virtual Empresa FkidEmpresaSisNavigation { get; set; }
}