// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class ProveedorCumplimiento
{
    public long PkidProveedorCumplimiento { get; set; }

    public int FkidProveedorOrco { get; set; }

    public DateTime FechaVerificacion { get; set; }

    public DateTime? VigenteHasta { get; set; }

    public bool CumplimientoFiscal { get; set; }

    public bool Inhabilitado { get; set; }

    public bool ConflictoInteres { get; set; }

    public bool DeclaracionIntegridad { get; set; }

    public string FuenteConsulta { get; set; }

    public string FolioEvidencia { get; set; }

    public string HuellaEvidencia { get; set; }

    public string Observaciones { get; set; }

    public bool Activo { get; set; }

    public int UsuarioCreacion { get; set; }

    public virtual Proveedor FkidProveedorOrcoNavigation { get; set; }
}