// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class Proveedor
{
    public int PkidProveedor { get; set; }

    public int? FkIdTipoProveedorSis { get; set; }

    public int? FkidEstatusProveedorSis { get; set; }

    public int? FkidCuentaContableSis { get; set; }

    public int FkidMunicipioSis { get; set; }

    public int FkidEstadoSis { get; set; }

    public int FkidPaisSis { get; set; }

    public int? FkidResponsableSis { get; set; }

    public int? FkidAesectorSis { get; set; }

    public int? FkidAedivisionSis { get; set; }

    public int? FkidAegrupoSis { get; set; }

    public int? FkidAeclaseSis { get; set; }

    public string Nombre { get; set; }

    public string Rfc { get; set; }

    public string Colonia { get; set; }

    public string Cp { get; set; }

    public string Ciudad { get; set; }

    public string Email { get; set; }

    public string Clave { get; set; }

    public string Calle { get; set; }

    public string Numero { get; set; }

    public DateTime? FechaAlta { get; set; }

    public string TelefonoInstitucional { get; set; }

    public string Notas { get; set; }

    public string PaginaWeb { get; set; }

    public string NumeroInt { get; set; }

    public string Curp { get; set; }

    public bool Activo { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public int UsuarioCreacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public int? UsuarioModificacion { get; set; }

    public virtual ICollection<Bien> Biens { get; set; } = new List<Bien>();

    public virtual TipoProveedor FkIdTipoProveedorSisNavigation { get; set; }

    public virtual CuentaContable FkidCuentaContableSisNavigation { get; set; }

    public virtual Estado FkidEstadoSisNavigation { get; set; }

    public virtual EstatusProveedor FkidEstatusProveedorSisNavigation { get; set; }

    public virtual Municipio FkidMunicipioSisNavigation { get; set; }

    public virtual Paise FkidPaisSisNavigation { get; set; }
}