// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class Puesto1
{
    public int PkIdPuesto { get; set; }

    public int? FkIdPuestoRh { get; set; }

    public int FkIdEmpresaEmp { get; set; }

    public string Nombre { get; set; }

    public int? FkIdNivelRh { get; set; }

    public int? FkIdClasePuestoRh { get; set; }

    public string Descripcion1 { get; set; }

    public string Descripcion2 { get; set; }

    public int? Orden { get; set; }

    public int? UsuarioCreacion { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public int? UsuarioModificacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public bool Activo { get; set; }

    public int? CtCreatedBy { get; set; }

    public DateTime? CtCreatedDate { get; set; }

    public int? CtModifiedBy { get; set; }

    public DateTime? CtModifiedDate { get; set; }

    public bool CtLive { get; set; }
}