// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class Py
{
    public int PkidPy { get; set; }

    public string Clave { get; set; }

    public string Descripcion { get; set; }

    public string NombreProyecto { get; set; }

    public DateOnly? InicioProyecto { get; set; }

    public DateOnly? FinProyecto { get; set; }

    public bool? Plurianual { get; set; }

    public bool? TieneTics { get; set; }

    public bool? EsPat { get; set; }

    public bool? AnexosTransversales { get; set; }

    public string ProgramaPresupuestario { get; set; }

    public bool? ProyectoInversion { get; set; }

    public bool? RecursosAdicionales { get; set; }

    public short? Prioridad { get; set; }

    public string FuenteFinanciamiento { get; set; }

    public string DescripcionProyecto { get; set; }

    public string ResponsableProyecto { get; set; }

    public string ObjetivoProyecto { get; set; }

    public string LineaEstrategica { get; set; }

    public string LineaAccionRegulatoria { get; set; }

    public string TemaAccionRegulatoria { get; set; }

    public string FundamentoLegal { get; set; }

    public string Justificacion { get; set; }

    public string Beneficios { get; set; }

    public string Indicador { get; set; }

    public string Meta { get; set; }

    public bool Activo { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public int UsuarioCreacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public int? UsuarioModificacion { get; set; }

    public virtual ICollection<EgresoAutorizado> EgresoAutorizados { get; set; } = new List<EgresoAutorizado>();

    public virtual ICollection<EgresoProyectado> EgresoProyectados { get; set; } = new List<EgresoProyectado>();

    public virtual Usuario UsuarioCreacionNavigation { get; set; }

    public virtual Usuario UsuarioModificacionNavigation { get; set; }
}