// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class RegistroConteo
{
    public int PkidRegistroConteo { get; set; }

    public int FkidArticuloConteoAlma { get; set; }

    public int FkidPeriodoConteoAlma { get; set; }

    public int FkidSucursalSis { get; set; }

    public int NumeroConteo { get; set; }

    public decimal CantidadContada { get; set; }

    public DateTime FechaConteo { get; set; }

    public int FkidUsuarioSis { get; set; }

    public string Observaciones { get; set; }

    public bool EsReconteo { get; set; }

    public string FotoPath { get; set; }

    public decimal? Latitud { get; set; }

    public decimal? Longitud { get; set; }

    public bool Activo { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public virtual ArticuloConteo FkidArticuloConteoAlmaNavigation { get; set; }

    public virtual PeriodoConteo FkidPeriodoConteoAlmaNavigation { get; set; }

    public virtual Sucursal FkidSucursalSisNavigation { get; set; }

    public virtual Usuario FkidUsuarioSisNavigation { get; set; }

    public virtual ICollection<HistorialEstatusArticulo> HistorialEstatusArticulos { get; set; } = new List<HistorialEstatusArticulo>();
}