// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class RegresoChequeSuficienciaPoliza
{
    public int PkidRegresoChequeSuficienciaPoliza { get; set; }

    public int FkidRegresoChequeSuficienciaPres { get; set; }

    public int FkidPolizaOriginalConta { get; set; }

    public int FkidPolizaReversionConta { get; set; }

    public string Etapas { get; set; }

    public bool Activo { get; set; }

    public DateTime FechaCreacion { get; set; }

    public int UsuarioCreacion { get; set; }

    public virtual Poliza FkidPolizaOriginalContaNavigation { get; set; }

    public virtual Poliza FkidPolizaReversionContaNavigation { get; set; }

    public virtual RegresoChequeSuficiencium FkidRegresoChequeSuficienciaPresNavigation { get; set; }

    public virtual Usuario UsuarioCreacionNavigation { get; set; }
}