// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class RegresoChequeSuficiencium
{
    public int PkidRegresoChequeSuficiencia { get; set; }

    public int FkidEmpresaSis { get; set; }

    public int FkidChequePres { get; set; }

    public int FkidSolicitudSuficienciaPres { get; set; }

    public string Motivo { get; set; }

    public DateTime FechaRegreso { get; set; }

    public bool Activo { get; set; }

    public DateTime FechaCreacion { get; set; }

    public int UsuarioCreacion { get; set; }

    public virtual Cheque FkidChequePresNavigation { get; set; }

    public virtual Empresa FkidEmpresaSisNavigation { get; set; }

    public virtual SolicitudSuficiencium FkidSolicitudSuficienciaPresNavigation { get; set; }

    public virtual ICollection<RegresoChequeSuficienciaPoliza> RegresoChequeSuficienciaPolizas { get; set; } = new List<RegresoChequeSuficienciaPoliza>();

    public virtual Usuario UsuarioCreacionNavigation { get; set; }
}