// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class RequisicionPartidum
{
    public int PkidRequisicionPartida { get; set; }

    public int FkidEmpresaSis { get; set; }

    public int FkidRequisicionOrco { get; set; }

    public int FkidPartidaConta { get; set; }

    public int? FkidEgresoAutorizadoPres { get; set; }

    public decimal? Monto { get; set; }

    public string Observaciones { get; set; }

    public bool Activo { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public int UsuarioCreacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public int? UsuarioModificacion { get; set; }

    public virtual Empresa FkidEmpresaSisNavigation { get; set; }

    public virtual Partidum FkidPartidaContaNavigation { get; set; }

    public virtual Requisicion FkidRequisicionOrcoNavigation { get; set; }

    public virtual Usuario UsuarioCreacionNavigation { get; set; }

    public virtual Usuario UsuarioModificacionNavigation { get; set; }
}
