// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class ResguardoDetalle
{
    public int PkidResguardoDetalle { get; set; }

    public int FkidResguardoAlma { get; set; }

    public int FkidBienAlma { get; set; }

    public int Consecutivo { get; set; }

    public DateTime FechaAsignacion { get; set; }

    public DateTime? FechaLiberacion { get; set; }

    public bool ImprimeEtiqueta { get; set; }

    public int? FkidEstadoBienAlma { get; set; }

    public string Observaciones { get; set; }

    public bool Activo { get; set; }

    public DateTime FechaCreacion { get; set; }

    public int UsuarioCreacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public int? UsuarioModificacion { get; set; }

    public virtual Bien FkidBienAlmaNavigation { get; set; }

    public virtual EstadoBien FkidEstadoBienAlmaNavigation { get; set; }

    public virtual Resguardo FkidResguardoAlmaNavigation { get; set; }

    public virtual ICollection<ResguardoMovimiento> ResguardoMovimientos { get; set; } = new List<ResguardoMovimiento>();
}