// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class SaldoMensual
{
    public int PkidSaldoMensual { get; set; }

    public int FkidAnioSis { get; set; }

    public int FkidMesSis { get; set; }

    public int FkidCuentaContable { get; set; }

    public decimal? SaldoInicial { get; set; }

    public decimal? Cargos { get; set; }

    public decimal? Abonos { get; set; }

    public decimal? SaldoFinal { get; set; }

    public int UsuarioCreacion { get; set; }

    public DateTime FechaCreacion { get; set; }

    public int? UsuarioModificacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public bool Activo { get; set; }
}