// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EG.Infraestructure.Models
{
    public partial class SP_MantenimientoChequeResult
    {
        public int PKIdCheque { get; set; }
        public int FKIdEmpresa_SIS { get; set; }
        [StringLength(128)]
        public string EmpresaNombre { get; set; }
        public int FKIdCLC_PRES { get; set; }
        [StringLength(20)]
        public string NumCLC { get; set; }
        public int FKIdContrato_PRES { get; set; }
        [StringLength(50)]
        public string NumeroContrato { get; set; }
        public int FKIdCuentaBancaria_TES { get; set; }
        public int FKIdPoliza_CONTA { get; set; }
        [StringLength(10)]
        public string ClavePoliza { get; set; }
        public DateOnly FechaEmision { get; set; }
        [StringLength(50)]
        public string NumeroCheque { get; set; }
        [StringLength(150)]
        public string Concepto { get; set; }
        [Column("ImporteTotal", TypeName = "decimal(20,4)")]
        public decimal ImporteTotal { get; set; }
        [StringLength(500)]
        public string Observaciones { get; set; }
        public int Estatus { get; set; }
        [StringLength(11)]
        public string EstatusDescripcion { get; set; }
        public bool Activo { get; set; }
        public DateTime? FechaCreacion { get; set; }
        public int UsuarioCreacion { get; set; }
        public DateTime? FechaModificacion { get; set; }
        public int? UsuarioModificacion { get; set; }
    }
}
