// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EG.Infraestructure.Models
{
    public partial class SP_MantenimientoDepositoResult
    {
        public int PKIdDeposito { get; set; }
        public int FKIdEmpresa_SIS { get; set; }
        [StringLength(128)]
        public string EmpresaNombre { get; set; }
        public int? FKIdIngresoAutorizado_PRES { get; set; }
        [StringLength(250)]
        public string IngresoAutorizadoDescripcion { get; set; }
        public DateOnly? IngresoAutorizadoFecha { get; set; }
        public int? FKIdPrograma_PRES { get; set; }
        [StringLength(50)]
        public string ProgramaClave { get; set; }
        [StringLength(255)]
        public string ProgramaDescripcion { get; set; }
        [StringLength(308)]
        public string ProgramaClaveNombre { get; set; }
        public int? FKIdOrigen_PRES { get; set; }
        public int? OrigenClave { get; set; }
        [StringLength(50)]
        public string OrigenDescripcion { get; set; }
        [StringLength(65)]
        public string OrigenClaveNombre { get; set; }
        public int FKIdTipoDoctoPago_CONTA { get; set; }
        [StringLength(50)]
        public string TipoDoctoPagoDescripcion { get; set; }
        [Column("Importe", TypeName = "decimal(18,2)")]
        public decimal Importe { get; set; }
        [StringLength(50)]
        public string NumeroReferencia { get; set; }
        [StringLength(150)]
        public string ConceptoCheque { get; set; }
        public DateOnly FechaEmision { get; set; }
        [StringLength(500)]
        public string NombreAportante { get; set; }
        public int FKIdCuentaCargo_CONTA { get; set; }
        [StringLength(50)]
        public string CuentaCargoClave { get; set; }
        [StringLength(250)]
        public string CuentaCargoDescripcion { get; set; }
        public int FKIdCuentaAbono_CONTA { get; set; }
        [StringLength(50)]
        public string CuentaAbonoClave { get; set; }
        [StringLength(250)]
        public string CuentaAbonoDescripcion { get; set; }
        public int? FKIdCLCFactura_PRES { get; set; }
        public DateOnly? CLCFacturaFecha { get; set; }
        public int FKIdPoliza_CONTA { get; set; }
        [StringLength(10)]
        public string ClavePoliza { get; set; }
        [StringLength(1000)]
        public string NombrePoliza { get; set; }
        [Column("Enero", TypeName = "decimal(18,2)")]
        public decimal Enero { get; set; }
        [Column("Febrero", TypeName = "decimal(18,2)")]
        public decimal Febrero { get; set; }
        [Column("Marzo", TypeName = "decimal(18,2)")]
        public decimal Marzo { get; set; }
        [Column("Abril", TypeName = "decimal(18,2)")]
        public decimal Abril { get; set; }
        [Column("Mayo", TypeName = "decimal(18,2)")]
        public decimal Mayo { get; set; }
        [Column("Junio", TypeName = "decimal(18,2)")]
        public decimal Junio { get; set; }
        [Column("Julio", TypeName = "decimal(18,2)")]
        public decimal Julio { get; set; }
        [Column("Agosto", TypeName = "decimal(18,2)")]
        public decimal Agosto { get; set; }
        [Column("Septiembre", TypeName = "decimal(18,2)")]
        public decimal Septiembre { get; set; }
        [Column("Octubre", TypeName = "decimal(18,2)")]
        public decimal Octubre { get; set; }
        [Column("Noviembre", TypeName = "decimal(18,2)")]
        public decimal Noviembre { get; set; }
        [Column("Diciembre", TypeName = "decimal(18,2)")]
        public decimal Diciembre { get; set; }
        [Column("Total", TypeName = "decimal(29,2)")]
        public decimal? Total { get; set; }
        [StringLength(500)]
        public string Observaciones { get; set; }
        public bool Activo { get; set; }
        public DateTime? FechaCreacion { get; set; }
        public int UsuarioCreacion { get; set; }
        public DateTime? FechaModificacion { get; set; }
        public int? UsuarioModificacion { get; set; }
    }
}
