// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EG.Infraestructure.Models
{
    public partial class SP_MantenimientoContratoResult
    {
        public int PKIdContrato { get; set; }
        public int FKIdEmpresa_SIS { get; set; }
        [StringLength(128)]
        public string EmpresaNombre { get; set; }
        public int FKIdAutorizacionSuficiencia_PRES { get; set; }
        public int FKIdSolicitudSuficiencia_PRES { get; set; }
        public int? FKIdRequisicion_ORCO { get; set; }
        [StringLength(100)]
        public string RequisicionDescripcion { get; set; }
        public int FKIdProveedor_SIS { get; set; }
        [StringLength(10)]
        public string ProveedorClave { get; set; }
        [StringLength(500)]
        public string ProveedorNombre { get; set; }
        [StringLength(50)]
        public string ProveedorRFC { get; set; }
        public int? FKIdPoliza_CONTA { get; set; }
        [StringLength(10)]
        public string ClavePoliza { get; set; }
        [StringLength(50)]
        public string NumeroContrato { get; set; }
        [StringLength(500)]
        public string Descripcion { get; set; }
        public DateOnly FechaContrato { get; set; }
        public DateOnly? FechaInicioVigencia { get; set; }
        public DateOnly? FechaFinVigencia { get; set; }
        [Column("MontoTotal", TypeName = "decimal(20,4)")]
        public decimal MontoTotal { get; set; }
        [StringLength(100)]
        public string PlazoEjecucion { get; set; }
        [StringLength(2147483647)]
        public string Observaciones { get; set; }
        public int Estatus { get; set; }
        [StringLength(11)]
        public string EstatusDescripcion { get; set; }
        public bool Activo { get; set; }
        public DateTime? FechaCreacion { get; set; }
        public int UsuarioCreacion { get; set; }
        public DateTime? FechaModificacion { get; set; }
        public int? UsuarioModificacion { get; set; }
    }
}
