// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EG.Infraestructure.Models
{
    public partial class SP_ReporteSolicitudSalidaResult
    {
        public int PKIdSolicitudSalida { get; set; }
        public int FKIdEmpresa_SIS { get; set; }
        [StringLength(128)]
        public string EmpresaNombre { get; set; }
        public int? FKIdAreaSolicita_SIS { get; set; }
        [StringLength(200)]
        public string AreaSolicitaNombre { get; set; }
        public int? FKIdAreaEntrega_SIS { get; set; }
        [StringLength(200)]
        public string AreaEntregaNombre { get; set; }
        public int FKIdEstatusSolicitudSalida_ALMA { get; set; }
        [StringLength(80)]
        public string EstatusDescripcion { get; set; }
        [StringLength(20)]
        public string EstatusColor { get; set; }
        [StringLength(30)]
        public string Folio { get; set; }
        public DateOnly FechaSolicitud { get; set; }
        public DateOnly? FechaRequerida { get; set; }
        [StringLength(250)]
        public string Solicitante { get; set; }
        [StringLength(1000)]
        public string Justificacion { get; set; }
        [StringLength(1000)]
        public string Observaciones { get; set; }
        public bool Autorizado { get; set; }
        public DateTime? FechaAutorizacion { get; set; }
        public int? UsuarioAutorizacion { get; set; }
        public bool Activo { get; set; }
        public DateTime FechaCreacion { get; set; }
        public int UsuarioCreacion { get; set; }
        public DateTime? FechaModificacion { get; set; }
        public int? UsuarioModificacion { get; set; }
        public int? DetallePKIdDetalleSolicitudSalida { get; set; }
        public int? DetalleFKIdSolicitudSalida_ALMA { get; set; }
        [StringLength(30)]
        public string DetalleSolicitudFolio { get; set; }
        public int? DetalleFKIdAlmacen_ALMA { get; set; }
        [StringLength(30)]
        public string DetalleAlmacenClave { get; set; }
        public int? DetalleFKIdTipoBien_ALMA { get; set; }
        [StringLength(200)]
        public string DetalleTipoBienClave { get; set; }
        [StringLength(1200)]
        public string DetalleTipoBienDescripcion { get; set; }
        public int? DetalleFKIdUnidades_ALMA { get; set; }
        [StringLength(50)]
        public string DetalleUnidadDescripcion { get; set; }
        [Column("DetalleCantidadSolicitada", TypeName = "decimal(20,4)")]
        public decimal? DetalleCantidadSolicitada { get; set; }
        [Column("DetalleCantidadAutorizada", TypeName = "decimal(20,4)")]
        public decimal? DetalleCantidadAutorizada { get; set; }
        [Column("DetalleCantidadEntregada", TypeName = "decimal(20,4)")]
        public decimal? DetalleCantidadEntregada { get; set; }
        [Column("DetalleCantidadPendiente", TypeName = "decimal(20,4)")]
        public decimal? DetalleCantidadPendiente { get; set; }
        [StringLength(1000)]
        public string DetalleObservaciones { get; set; }
        public bool? DetalleActivo { get; set; }
        public DateTime? DetalleFechaCreacion { get; set; }
        public int? DetalleUsuarioCreacion { get; set; }
        public DateTime? DetalleFechaModificacion { get; set; }
        public int? DetalleUsuarioModificacion { get; set; }
    }
}
