// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EG.Infraestructure.Models
{
    public partial class SP_ReporteInventarioResult
    {
        public int PKIdInventario { get; set; }
        public int FKIdEmpresa_SIS { get; set; }
        [StringLength(128)]
        public string EmpresaNombre { get; set; }
        public int? FKIdCalendarioInventario_ALMA { get; set; }
        [StringLength(30)]
        public string CalendarioFolio { get; set; }
        public int? FKIdArea_SIS { get; set; }
        [StringLength(200)]
        public string AreaNombre { get; set; }
        public int FKIdEstatusInventario_ALMA { get; set; }
        [StringLength(80)]
        public string EstatusDescripcion { get; set; }
        [StringLength(20)]
        public string EstatusColor { get; set; }
        [StringLength(30)]
        public string Folio { get; set; }
        public DateOnly FechaInventario { get; set; }
        [StringLength(250)]
        public string Responsable { get; set; }
        [StringLength(1000)]
        public string Observaciones { get; set; }
        public int TotalBienes { get; set; }
        public int TotalLocalizados { get; set; }
        public int TotalDiferencias { get; set; }
        public bool Autorizado { get; set; }
        public DateTime? FechaAutorizacion { get; set; }
        public int? UsuarioAutorizacion { get; set; }
        public bool Activo { get; set; }
        public DateTime FechaCreacion { get; set; }
        public int UsuarioCreacion { get; set; }
        public DateTime? FechaModificacion { get; set; }
        public int? UsuarioModificacion { get; set; }
        public int? DetallePKIdInventarioDetalle { get; set; }
        public int? DetalleFKIdInventario_ALMA { get; set; }
        [StringLength(30)]
        public string DetalleInventarioFolio { get; set; }
        public int? DetalleFKIdBien_ALMA { get; set; }
        [StringLength(50)]
        public string DetalleBienClave { get; set; }
        [StringLength(1000)]
        public string DetalleBienDescripcion { get; set; }
        [StringLength(50)]
        public string DetalleModelo { get; set; }
        [StringLength(1000)]
        public string DetalleSerie { get; set; }
        [Column("DetalleValorActual", TypeName = "decimal(20,4)")]
        public decimal? DetalleValorActual { get; set; }
        [StringLength(50)]
        public string DetalleClaveBien { get; set; }
        [StringLength(1000)]
        public string DetalleDescripcionBien { get; set; }
        [StringLength(1000)]
        public string DetalleSerieCapturada { get; set; }
        [StringLength(250)]
        public string DetalleUbicacionSistema { get; set; }
        [StringLength(250)]
        public string DetalleUbicacionFisica { get; set; }
        public bool? DetalleLocalizado { get; set; }
        public bool? DetalleTieneDiferencia { get; set; }
        [StringLength(1000)]
        public string DetalleObservaciones { get; set; }
        public bool? DetalleActivo { get; set; }
        public DateTime? DetalleFechaCreacion { get; set; }
        public int? DetalleUsuarioCreacion { get; set; }
        public DateTime? DetalleFechaModificacion { get; set; }
        public int? DetalleUsuarioModificacion { get; set; }
    }
}
