// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EG.Infraestructure.Models
{
    public partial class SP_ReporteBajaResult
    {
        public int PKIdBaja { get; set; }
        [StringLength(30)]
        public string Folio { get; set; }
        public int FKIdEmpresa_SIS { get; set; }
        [StringLength(128)]
        public string EmpresaNombre { get; set; }
        public int? FKIdArea_SIS { get; set; }
        [StringLength(15)]
        public string AreaClave { get; set; }
        [StringLength(200)]
        public string AreaNombre { get; set; }
        public int FKIdBien_ALMA { get; set; }
        [StringLength(50)]
        public string BienClave { get; set; }
        [StringLength(50)]
        public string BienClaveAnterior { get; set; }
        [StringLength(1000)]
        public string BienDescripcion { get; set; }
        [StringLength(50)]
        public string Modelo { get; set; }
        [StringLength(1000)]
        public string Serie { get; set; }
        [StringLength(50)]
        public string Factura { get; set; }
        [Column("ValorActual", TypeName = "decimal(20,4)")]
        public decimal? ValorActual { get; set; }
        public int FKIdTipoBien_ALMA { get; set; }
        [StringLength(200)]
        public string TipoBienCodigoClave { get; set; }
        [StringLength(1200)]
        public string TipoBienDescripcion { get; set; }
        public int FKIdTipoBaja_ALMA { get; set; }
        [StringLength(20)]
        public string TipoBajaClave { get; set; }
        [StringLength(150)]
        public string TipoBajaDescripcion { get; set; }
        public int FKIdEstatusBaja_ALMA { get; set; }
        [StringLength(80)]
        public string EstatusDescripcion { get; set; }
        [StringLength(20)]
        public string EstatusColor { get; set; }
        public int? FKIdEstadoBienAnterior_ALMA { get; set; }
        [StringLength(100)]
        public string EstadoAnterior { get; set; }
        public int? FKIdEstadoBienDestino_ALMA { get; set; }
        [StringLength(100)]
        public string EstadoDestino { get; set; }
        public DateOnly FechaSolicitud { get; set; }
        public DateOnly? FechaBaja { get; set; }
        [StringLength(200)]
        public string Referencia { get; set; }
        public DateOnly? FechaReferencia { get; set; }
        [StringLength(250)]
        public string Destinatario { get; set; }
        [StringLength(100)]
        public string Recibo { get; set; }
        [Column("Cantidad", TypeName = "decimal(20,4)")]
        public decimal? Cantidad { get; set; }
        [StringLength(1000)]
        public string Motivo { get; set; }
        [StringLength(1000)]
        public string Dictamen { get; set; }
        [StringLength(1000)]
        public string Observaciones { get; set; }
        public int? FKIdPoliza_CONTA { get; set; }
        [StringLength(10)]
        public string ClavePoliza { get; set; }
        public int? SolicitadoPor_NOM { get; set; }
        public int? AutorizadoPor_NOM { get; set; }
        public DateTime? FechaAutorizacion { get; set; }
        public bool Activo { get; set; }
        public DateTime FechaCreacion { get; set; }
        public int UsuarioCreacion { get; set; }
        public DateTime? FechaModificacion { get; set; }
        public int? UsuarioModificacion { get; set; }
    }
}
