// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EG.Infraestructure.Models
{
    public partial class SP_ReportePolizaResult
    {
        [StringLength(10)]
        public string ClavePoliza { get; set; }
        [StringLength(10)]
        public string FechaPoliza { get; set; }
        [StringLength(1000)]
        public string NombrePoliza { get; set; }
        [StringLength(25)]
        public string Descripcion { get; set; }
        [Column("ImporteDebe", TypeName = "decimal(20,4)")]
        public decimal? ImporteDebe { get; set; }
        [Column("ImporteHaber", TypeName = "decimal(20,4)")]
        public decimal? ImporteHaber { get; set; }
        [StringLength(600)]
        public string DDetalle { get; set; }
        [StringLength(50)]
        public string ClaveOrd { get; set; }
        [StringLength(40)]
        public string ClaveNombre { get; set; }
        [StringLength(250)]
        public string DescCuenta { get; set; }
        public int PKIdPoliza { get; set; }
    }
}
