// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EG.Infraestructure.Models
{
    public partial class spConceptoConfiguracion_ListResult
    {
        public int IdConfiguracion { get; set; }
        [StringLength(8)]
        public string TipoConfiguracion { get; set; }
        public int EmpresaId { get; set; }
        [StringLength(255)]
        public string EmpresaNombre { get; set; }
        public int? PersonaId { get; set; }
        [StringLength(600)]
        public string PersonaClaveNombre { get; set; }
        public int? PuestoId { get; set; }
        public int? PeriodoId { get; set; }
        public int ConceptoId { get; set; }
        [StringLength(20)]
        public string ConceptoClave { get; set; }
        [StringLength(500)]
        public string ConceptoNombre { get; set; }
        [StringLength(523)]
        public string ConceptoClaveNombre { get; set; }
        [Column("Importe", TypeName = "decimal(19,4)")]
        public decimal? Importe { get; set; }
        public DateOnly? FechaInicio { get; set; }
        public DateOnly? FechaFin { get; set; }
        public bool? Vigente { get; set; }
        public bool Activo { get; set; }
        public DateTime? FechaCreacion { get; set; }
        public int? UsuarioCreacion { get; set; }
        public DateTime? FechaModificacion { get; set; }
        public int? UsuarioModificacion { get; set; }
        public int? TotalCount { get; set; }
    }
}
