// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EG.Infraestructure.Models
{
    public partial class spConceptos_ListResult
    {
        public int PKIdConcepto { get; set; }
        [StringLength(20)]
        public string Clave { get; set; }
        [StringLength(20)]
        public string SubClave { get; set; }
        [StringLength(5)]
        public string PerDed { get; set; }
        [StringLength(10)]
        public string TipoMovimiento { get; set; }
        [StringLength(500)]
        public string Nombre { get; set; }
        [StringLength(523)]
        public string ClaveNombre { get; set; }
        public int FormaCalculoId { get; set; }
        public int? EmpresaId { get; set; }
        [StringLength(250)]
        public string EmpresaNombre { get; set; }
        public bool Activo { get; set; }
        public int? UsuarioCreacion { get; set; }
        public DateTime? FechaCreacion { get; set; }
        public int? UsuarioModificacion { get; set; }
        public DateTime? FechaModificacion { get; set; }
        public int? TotalCount { get; set; }
    }
}
