// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EG.Infraestructure.Models
{
    public partial class spConceptosTabulares_ListResult
    {
        public int PKIdConceptoTabulador { get; set; }
        public int EmpresaId { get; set; }
        [StringLength(255)]
        public string EmpresaNombre { get; set; }
        public int ConceptoId { get; set; }
        [StringLength(20)]
        public string ConceptoClave { get; set; }
        [StringLength(500)]
        public string ConceptoNombre { get; set; }
        [StringLength(523)]
        public string ConceptoClaveNombre { get; set; }
        public int PuestoId { get; set; }
        [StringLength(150)]
        public string PuestoNombre { get; set; }
        [StringLength(179)]
        public string PuestoClaveNombre { get; set; }
        public int? NivelId { get; set; }
        [StringLength(5)]
        public string NivelClave { get; set; }
        public int? UniversoId { get; set; }
        [StringLength(2)]
        public string UniversoDescripcion { get; set; }
        public int? ClasePuestoId { get; set; }
        [StringLength(64)]
        public string ClasePuestoDescripcion { get; set; }
        [Column("ImporteMensual", TypeName = "decimal(19,4)")]
        public decimal? ImporteMensual { get; set; }
        public DateOnly? FechaInicio { get; set; }
        public DateOnly? FechaFin { get; set; }
        public bool? Vigente { get; set; }
        public bool Activo { get; set; }
        public int? UsuarioCreacion { get; set; }
        public DateTime? FechaCreacion { get; set; }
        public int? UsuarioModificacion { get; set; }
        public DateTime? FechaModificacion { get; set; }
        public int? TotalCount { get; set; }
    }
}
