// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EG.Infraestructure.Models
{
    public partial class spDocumentoObtenerPorEntidadResult
    {
        public long PkidDocumento { get; set; }
        [StringLength(120)]
        public string Modulo { get; set; }
        [StringLength(120)]
        public string SubModulo { get; set; }
        [StringLength(160)]
        public string Controlador { get; set; }
        [StringLength(160)]
        public string Servicio { get; set; }
        public long EntidadId { get; set; }
        public int? FkidEmpresaSis { get; set; }
        [StringLength(250)]
        public string Titulo { get; set; }
        [StringLength(2147483647)]
        public string Descripcion { get; set; }
        [StringLength(260)]
        public string NombreOriginal { get; set; }
        [StringLength(260)]
        public string NombreAlmacenado { get; set; }
        [StringLength(16)]
        public string Extension { get; set; }
        [StringLength(120)]
        public string TipoMime { get; set; }
        public long TamanoBytes { get; set; }
        [StringLength(20)]
        public string ModoAlmacenamiento { get; set; }
        [StringLength(700)]
        public string RutaRelativa { get; set; }
        [StringLength(64)]
        public string HashSha256Hex { get; set; }
        public int VersionDocumento { get; set; }
        public bool EsImagen { get; set; }
        public bool EsPdf { get; set; }
        public bool Activo { get; set; }
        public int CT_CreatedBy { get; set; }
        public DateTime CT_CreatedDate { get; set; }
        public int? CT_ModifiedBy { get; set; }
        public DateTime? CT_ModifiedDate { get; set; }
    }
}
