// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EG.Infraestructure.Models
{
    public partial class spDocumentoObtenerContenidoResult
    {
        public long PkidDocumento { get; set; }
        [StringLength(260)]
        public string NombreOriginal { get; set; }
        [StringLength(260)]
        public string NombreAlmacenado { get; set; }
        [StringLength(16)]
        public string Extension { get; set; }
        [StringLength(120)]
        public string TipoMime { get; set; }
        public long TamanoBytes { get; set; }
        [StringLength(20)]
        public string ModoAlmacenamiento { get; set; }
        public byte[] ContenidoArchivo { get; set; }
        [StringLength(700)]
        public string RutaRelativa { get; set; }
    }
}
