// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EG.Infraestructure.Models
{
    public partial class spEliminarUsuarioSucursalResult3
    {
        public int Success { get; set; }
        [StringLength(4000)]
        public string Message { get; set; }
        [StringLength(5)]
        public string Code { get; set; }
    }
}
