// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EG.Infraestructure.Models
{
    public partial class spPeriodosActivos_ListResult
    {
        public int PKIdPeriodoActivo { get; set; }
        public int EmpresaId { get; set; }
        [StringLength(128)]
        public string EmpresaNombre { get; set; }
        public int PeriodoId { get; set; }
        public bool EstaCerrado { get; set; }
        public bool? EstaComprometido { get; set; }
        public bool? EstaDevengado { get; set; }
        public bool? EstaEjercido { get; set; }
        public long? TotalMovimientos { get; set; }
        [Column("TotalPercepcion", TypeName = "decimal(19,4)")]
        public decimal? TotalPercepcion { get; set; }
        [Column("TotalDeduccion", TypeName = "decimal(19,4)")]
        public decimal? TotalDeduccion { get; set; }
        [Column("TotalAportacion", TypeName = "decimal(19,4)")]
        public decimal? TotalAportacion { get; set; }
        [Column("TotalNeto", TypeName = "decimal(19,4)")]
        public decimal? TotalNeto { get; set; }
        public bool Activo { get; set; }
        public DateTime? FechaCreacion { get; set; }
        public int? UsuarioCreacion { get; set; }
        public DateTime? FechaModificacion { get; set; }
        public int? UsuarioModificacion { get; set; }
        public int? TotalCount { get; set; }
    }
}
