// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EG.Infraestructure.Models
{
    public partial class SPR_LibroDiarioResult
    {
        [StringLength(30)]
        public string Fecha { get; set; }
        public long? NumEvento { get; set; }
        [StringLength(10)]
        public string Asiento { get; set; }
        [StringLength(13)]
        public string DocumentoFuente { get; set; }
        [StringLength(50)]
        public string ContableCodigo { get; set; }
        [StringLength(250)]
        public string ContableNombre { get; set; }
        [StringLength(50)]
        public string PresupuestalCodigo { get; set; }
        [StringLength(250)]
        public string PresupuestalNombre { get; set; }
        [StringLength(600)]
        public string Descripcion { get; set; }
        [StringLength(4000)]
        public string ImporteDebe { get; set; }
        [StringLength(4000)]
        public string ImporteHaber { get; set; }
        [StringLength(4000)]
        public string Titulo { get; set; }
    }
}
