// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EG.Infraestructure.Models
{
    public partial class SPR_EstadoSituacionFinancieraComparativo_DevExResult
    {
        [StringLength(100)]
        public string Periodo { get; set; }
        public int? AnioActual { get; set; }
        public int? AnioAnterior { get; set; }
        [StringLength(4000)]
        public string A_1110000000 { get; set; }
        [StringLength(4000)]
        public string A_1120000000 { get; set; }
        [StringLength(4000)]
        public string A_1130000000 { get; set; }
        [StringLength(4000)]
        public string A_1140000000 { get; set; }
        [StringLength(4000)]
        public string A_1150000000 { get; set; }
        [StringLength(4000)]
        public string A_1160000000 { get; set; }
        [StringLength(4000)]
        public string A_1170000000 { get; set; }
        [StringLength(4000)]
        public string SubTotalActivosCirculantes { get; set; }
        [StringLength(4000)]
        public string A_2110000000 { get; set; }
        [StringLength(4000)]
        public string A_2120000000 { get; set; }
        [StringLength(4000)]
        public string A_2130000000 { get; set; }
        [StringLength(4000)]
        public string A_2140000000 { get; set; }
        [StringLength(4000)]
        public string A_2150000000 { get; set; }
        [StringLength(4000)]
        public string A_2160000000 { get; set; }
        [StringLength(4000)]
        public string A_2170000000 { get; set; }
        [StringLength(4000)]
        public string A_2180000000 { get; set; }
        [StringLength(4000)]
        public string SubTotalPasivoCirculantes { get; set; }
        [StringLength(4000)]
        public string A_1210000000 { get; set; }
        [StringLength(4000)]
        public string A_1220000000 { get; set; }
        [StringLength(4000)]
        public string A_1230000000 { get; set; }
        [StringLength(4000)]
        public string A_1240000000 { get; set; }
        [StringLength(4000)]
        public string A_1250000000 { get; set; }
        [StringLength(4000)]
        public string A_1260000000 { get; set; }
        [StringLength(4000)]
        public string A_1270000000 { get; set; }
        [StringLength(4000)]
        public string A_1280000000 { get; set; }
        [StringLength(4000)]
        public string A_1290000000 { get; set; }
        [StringLength(4000)]
        public string SubTotalActivosNoCirculantes { get; set; }
        [StringLength(4000)]
        public string A_2210000000 { get; set; }
        [StringLength(4000)]
        public string A_2220000000 { get; set; }
        [StringLength(4000)]
        public string A_2230000000 { get; set; }
        [StringLength(4000)]
        public string A_2240000000 { get; set; }
        [StringLength(4000)]
        public string A_2250000000 { get; set; }
        [StringLength(4000)]
        public string A_2260000000 { get; set; }
        [StringLength(4000)]
        public string SubTotalPasivoNoCirculantes { get; set; }
        [StringLength(4000)]
        public string A_3122300000 { get; set; }
        [StringLength(4000)]
        public string A_3122200000 { get; set; }
        [StringLength(4000)]
        public string A_3122100000 { get; set; }
        [StringLength(4000)]
        public string SubTotalPatrimonioContribuido { get; set; }
        [StringLength(4000)]
        public string A_3210000000 { get; set; }
        [StringLength(4000)]
        public string A_3220000000 { get; set; }
        [StringLength(4000)]
        public string A_3230000000 { get; set; }
        [StringLength(4000)]
        public string A_3240000000 { get; set; }
        [StringLength(4000)]
        public string A_3250000000 { get; set; }
        [StringLength(4000)]
        public string SubTotalPatrimonioGenerado { get; set; }
        [StringLength(4000)]
        public string A_Exc01 { get; set; }
        [StringLength(4000)]
        public string A_Exc02 { get; set; }
        [StringLength(4000)]
        public string B_1110000000 { get; set; }
        [StringLength(4000)]
        public string B_1120000000 { get; set; }
        [StringLength(4000)]
        public string B_1130000000 { get; set; }
        [StringLength(4000)]
        public string B_1140000000 { get; set; }
        [StringLength(4000)]
        public string B_1150000000 { get; set; }
        [StringLength(4000)]
        public string B_1160000000 { get; set; }
        [StringLength(4000)]
        public string B_1170000000 { get; set; }
        [StringLength(4000)]
        public string SubTotalActivoCirculanteAnterior { get; set; }
        [StringLength(4000)]
        public string B_2110000000 { get; set; }
        [StringLength(4000)]
        public string B_2120000000 { get; set; }
        [StringLength(4000)]
        public string B_2130000000 { get; set; }
        [StringLength(4000)]
        public string B_2140000000 { get; set; }
        [StringLength(4000)]
        public string B_2150000000 { get; set; }
        [StringLength(4000)]
        public string B_2160000000 { get; set; }
        [StringLength(4000)]
        public string B_2170000000 { get; set; }
        [StringLength(4000)]
        public string B_2180000000 { get; set; }
        [StringLength(4000)]
        public string SubTotalPasivoCirculanteAnterior { get; set; }
        [StringLength(4000)]
        public string B_1210000000 { get; set; }
        [StringLength(4000)]
        public string B_1220000000 { get; set; }
        [StringLength(4000)]
        public string B_1230000000 { get; set; }
        [StringLength(4000)]
        public string B_1240000000 { get; set; }
        [StringLength(4000)]
        public string B_1250000000 { get; set; }
        [StringLength(4000)]
        public string B_1260000000 { get; set; }
        [StringLength(4000)]
        public string B_1270000000 { get; set; }
        [StringLength(4000)]
        public string B_1280000000 { get; set; }
        [StringLength(4000)]
        public string B_1290000000 { get; set; }
        [StringLength(4000)]
        public string SubTotalActivoNoCirculanteAnterior { get; set; }
        [StringLength(4000)]
        public string B_2210000000 { get; set; }
        [StringLength(4000)]
        public string B_2220000000 { get; set; }
        [StringLength(4000)]
        public string B_2230000000 { get; set; }
        [StringLength(4000)]
        public string B_2240000000 { get; set; }
        [StringLength(4000)]
        public string B_2250000000 { get; set; }
        [StringLength(4000)]
        public string B_2260000000 { get; set; }
        [StringLength(4000)]
        public string SubTotalPasivoNoCirculanteAnterior { get; set; }
        [StringLength(4000)]
        public string B_3122300000 { get; set; }
        [StringLength(4000)]
        public string B_3122200000 { get; set; }
        [StringLength(4000)]
        public string B_3122100000 { get; set; }
        [StringLength(4000)]
        public string SubTotalPatrimoniContribuidoAnterior { get; set; }
        [StringLength(4000)]
        public string B_3210000000 { get; set; }
        [StringLength(4000)]
        public string B_3220000000 { get; set; }
        [StringLength(4000)]
        public string B_3230000000 { get; set; }
        [StringLength(4000)]
        public string B_3240000000 { get; set; }
        [StringLength(4000)]
        public string B_3250000000 { get; set; }
        [StringLength(4000)]
        public string SubTotalPatrimonioGeneradoAnterior { get; set; }
        [StringLength(4000)]
        public string B_Exc01 { get; set; }
        [StringLength(4000)]
        public string B_Exc02 { get; set; }
        [StringLength(4000)]
        public string V_1110000000 { get; set; }
        [StringLength(4000)]
        public string V_1120000000 { get; set; }
        [StringLength(4000)]
        public string V_1130000000 { get; set; }
        [StringLength(4000)]
        public string V_1140000000 { get; set; }
        [StringLength(4000)]
        public string V_1150000000 { get; set; }
        [StringLength(4000)]
        public string V_1160000000 { get; set; }
        [StringLength(4000)]
        public string V_1170000000 { get; set; }
        [StringLength(4000)]
        public string SubTotal_V_Activo { get; set; }
        [StringLength(4000)]
        public string V_2110000000 { get; set; }
        [StringLength(4000)]
        public string V_2120000000 { get; set; }
        [StringLength(4000)]
        public string V_2130000000 { get; set; }
        [StringLength(4000)]
        public string V_2140000000 { get; set; }
        [StringLength(4000)]
        public string V_2150000000 { get; set; }
        [StringLength(4000)]
        public string V_2160000000 { get; set; }
        [StringLength(4000)]
        public string V_2170000000 { get; set; }
        [StringLength(4000)]
        public string V_2180000000 { get; set; }
        [StringLength(4000)]
        public string SubTotal_V_Pasivo { get; set; }
        [StringLength(4000)]
        public string V_1210000000 { get; set; }
        [StringLength(4000)]
        public string V_1220000000 { get; set; }
        [StringLength(4000)]
        public string V_1230000000 { get; set; }
        [StringLength(4000)]
        public string V_1240000000 { get; set; }
        [StringLength(4000)]
        public string V_1250000000 { get; set; }
        [StringLength(4000)]
        public string V_1260000000 { get; set; }
        [StringLength(4000)]
        public string V_1270000000 { get; set; }
        [StringLength(4000)]
        public string V_1280000000 { get; set; }
        [StringLength(4000)]
        public string V_1290000000 { get; set; }
        [StringLength(4000)]
        public string SubTotal_V_Activo_No_C { get; set; }
        [StringLength(4000)]
        public string V_2210000000 { get; set; }
        [StringLength(4000)]
        public string V_2220000000 { get; set; }
        [StringLength(4000)]
        public string V_2230000000 { get; set; }
        [StringLength(4000)]
        public string V_2240000000 { get; set; }
        [StringLength(4000)]
        public string V_2250000000 { get; set; }
        [StringLength(4000)]
        public string V_2260000000 { get; set; }
        [StringLength(4000)]
        public string SubTotal_V_Pasivo_No_C { get; set; }
        [StringLength(4000)]
        public string V_3122300000 { get; set; }
        [StringLength(4000)]
        public string V_3122200000 { get; set; }
        [StringLength(4000)]
        public string V_3122100000 { get; set; }
        [StringLength(4000)]
        public string SubTotal_V_PatrimonioContribuido { get; set; }
        [StringLength(4000)]
        public string V_3210000000 { get; set; }
        [StringLength(4000)]
        public string V_3220000000 { get; set; }
        [StringLength(4000)]
        public string V_3230000000 { get; set; }
        [StringLength(4000)]
        public string V_3240000000 { get; set; }
        [StringLength(4000)]
        public string V_3250000000 { get; set; }
        [StringLength(4000)]
        public string SubTotal_V_PatrimonioGenerado { get; set; }
        [StringLength(4000)]
        public string V_Exc01 { get; set; }
        [StringLength(4000)]
        public string V_Exc02 { get; set; }
        [StringLength(4000)]
        public string P_1110000000 { get; set; }
        [StringLength(4000)]
        public string P_1120000000 { get; set; }
        [StringLength(4000)]
        public string P_1130000000 { get; set; }
        [StringLength(4000)]
        public string P_1140000000 { get; set; }
        [StringLength(4000)]
        public string P_1150000000 { get; set; }
        [StringLength(4000)]
        public string P_1160000000 { get; set; }
        [StringLength(4000)]
        public string P_1170000000 { get; set; }
        [StringLength(4000)]
        public string P_2110000000 { get; set; }
        [StringLength(4000)]
        public string P_2120000000 { get; set; }
        [StringLength(4000)]
        public string P_2130000000 { get; set; }
        [StringLength(4000)]
        public string P_2140000000 { get; set; }
        [StringLength(4000)]
        public string P_2150000000 { get; set; }
        [StringLength(4000)]
        public string P_2160000000 { get; set; }
        [StringLength(4000)]
        public string P_2170000000 { get; set; }
        [StringLength(4000)]
        public string P_2180000000 { get; set; }
        [StringLength(4000)]
        public string P_1210000000 { get; set; }
        [StringLength(4000)]
        public string P_1220000000 { get; set; }
        [StringLength(4000)]
        public string P_1230000000 { get; set; }
        [StringLength(4000)]
        public string P_1240000000 { get; set; }
        [StringLength(4000)]
        public string P_1250000000 { get; set; }
        [StringLength(4000)]
        public string P_1260000000 { get; set; }
        [StringLength(4000)]
        public string P_1270000000 { get; set; }
        [StringLength(4000)]
        public string P_1280000000 { get; set; }
        [StringLength(4000)]
        public string P_1290000000 { get; set; }
        [StringLength(4000)]
        public string P_2210000000 { get; set; }
        [StringLength(4000)]
        public string P_2220000000 { get; set; }
        [StringLength(4000)]
        public string P_2230000000 { get; set; }
        [StringLength(4000)]
        public string P_2240000000 { get; set; }
        [StringLength(4000)]
        public string P_2250000000 { get; set; }
        [StringLength(4000)]
        public string P_2260000000 { get; set; }
        [StringLength(4000)]
        public string P_3122300000 { get; set; }
        [StringLength(4000)]
        public string P_3122200000 { get; set; }
        [StringLength(4000)]
        public string P_3122100000 { get; set; }
        [StringLength(4000)]
        public string P_3210000000 { get; set; }
        [StringLength(4000)]
        public string P_3220000000 { get; set; }
        [StringLength(4000)]
        public string P_3230000000 { get; set; }
        [StringLength(4000)]
        public string P_3240000000 { get; set; }
        [StringLength(4000)]
        public string P_3250000000 { get; set; }
        [StringLength(4000)]
        public string P_Exc01 { get; set; }
        [StringLength(4000)]
        public string P_Exc02 { get; set; }
        [StringLength(4000)]
        public string SubTotal_P_Activo { get; set; }
        [StringLength(4000)]
        public string SubTotal_P_Activo_No_C { get; set; }
        [StringLength(4000)]
        public string TOTAL_P_ACTIVO { get; set; }
        [StringLength(4000)]
        public string SubTotal_P_Pasivo { get; set; }
        [StringLength(4000)]
        public string SubTotal_P_Pasivo_No_C { get; set; }
        [StringLength(4000)]
        public string TOTAL_P_PASIVO { get; set; }
        [StringLength(4000)]
        public string SubTotal_P_PatrimonioContibuido { get; set; }
        [StringLength(4000)]
        public string SubTotal_P_PatrimonioGenerado { get; set; }
        [StringLength(4000)]
        public string TOTAL_P_HACIENDA { get; set; }
        [StringLength(4000)]
        public string TOTAL_ACTIVOS { get; set; }
        [StringLength(4000)]
        public string TOTAL_ACTIVO_ANTERIOR { get; set; }
        [StringLength(4000)]
        public string TOTAL_PASIVOnoCIRCULANTE { get; set; }
        [StringLength(4000)]
        public string TOTAL_PASIVO_CIRCULANTE_ANTERIOR { get; set; }
        [StringLength(4000)]
        public string TOTAL_PASIVO_CIRCULANTE { get; set; }
        [StringLength(4000)]
        public string TOTAL_PASIVO_CIRCULANTE_ANTERIOR_2 { get; set; }
        [StringLength(4000)]
        public string TOTAL_HACIENDA { get; set; }
        [StringLength(4000)]
        public string TOTAL_HACIENDA_HACIENDA { get; set; }
        [StringLength(4000)]
        public string TOTAL_V_ACTIVO { get; set; }
        [StringLength(4000)]
        public string TOTAL_V_PASIVO { get; set; }
        [StringLength(4000)]
        public string TOTAL_V_HACIENDA { get; set; }
        [StringLength(4000)]
        public string TOTAL { get; set; }
        [StringLength(4000)]
        public string TOTAL_ANTERIOR { get; set; }
        [StringLength(4000)]
        public string TOTAL_VARIACION { get; set; }
        [StringLength(4000)]
        public string TOTAL_PORCENTAJE { get; set; }
    }
}
