// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EG.Infraestructure.Models
{
    public partial class SPR_RepActFijosResult
    {
        [StringLength(50)]
        public string Codigo { get; set; }
        [StringLength(1000)]
        public string Descripcion { get; set; }
        [Column("Valor", TypeName = "decimal(20,4)")]
        public decimal? Valor { get; set; }
        [StringLength(64)]
        public string Funcion1 { get; set; }
        [StringLength(64)]
        public string Funcion2 { get; set; }
        [StringLength(64)]
        public string Funcion3 { get; set; }
        [StringLength(254)]
        public string Nombre1 { get; set; }
        [StringLength(254)]
        public string Nombre2 { get; set; }
        [StringLength(254)]
        public string Nombre3 { get; set; }
        [StringLength(254)]
        public string Puesto1 { get; set; }
        [StringLength(254)]
        public string Puesto2 { get; set; }
        [StringLength(254)]
        public string Puesto3 { get; set; }
        [StringLength(128)]
        public string Titulo { get; set; }
    }
}
