// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EG.Infraestructure.Models
{
    public partial class SPR_EstadoActividadResult
    {
        public int id { get; set; }
        [StringLength(500)]
        public string Concepto { get; set; }
        [Column("20XN")]
        public int _20XN { get; set; }
        [Column("20XN1")]
        public int _20XN1 { get; set; }
        [StringLength(6)]
        public string Firma1 { get; set; }
        [StringLength(2)]
        public string Firma2 { get; set; }
        [StringLength(7)]
        public string Firma3 { get; set; }
    }
}
