// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EG.Infraestructure.Models
{
    public partial class SPR_LibroAlmacenSuministros_DevExResult
    {
        [StringLength(30)]
        public string ClavePersona { get; set; }
        [StringLength(250)]
        public string Persona { get; set; }
        [StringLength(50)]
        public string NombreAutoriza { get; set; }
        [StringLength(100)]
        public string PuestoAutoriza { get; set; }
        [StringLength(100)]
        public string PuestoSolicita { get; set; }
        [StringLength(1000)]
        public string DescripcionSolicitud { get; set; }
        [StringLength(2)]
        public string Dia { get; set; }
        [StringLength(30)]
        public string Mes { get; set; }
        public int? Anio { get; set; }
        public long? Consecutivo { get; set; }
        [StringLength(10)]
        public string FechaSolicitud { get; set; }
        [StringLength(15)]
        public string ClaveArea { get; set; }
        [StringLength(200)]
        public string Area { get; set; }
        [StringLength(30)]
        public string NumeroVale { get; set; }
        [StringLength(200)]
        public string ClaveArticulo { get; set; }
        [StringLength(4)]
        public string Partida { get; set; }
        [StringLength(800)]
        public string Subcuenta { get; set; }
        [StringLength(8)]
        public string Programa { get; set; }
        [Column("Cantidad", TypeName = "decimal(20,4)")]
        public decimal? Cantidad { get; set; }
        [StringLength(50)]
        public string Unidad { get; set; }
        [StringLength(1200)]
        public string DesArticulo { get; set; }
        [Column("Salidas", TypeName = "decimal(20,4)")]
        public decimal? Salidas { get; set; }
        [Column("CostoUnitario", TypeName = "decimal(20,4)")]
        public decimal CostoUnitario { get; set; }
        [Column("Monto", TypeName = "decimal(38,6)")]
        public decimal? Monto { get; set; }
    }
}
