// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EG.Infraestructure.Models
{
    public partial class SPR_AlmacendeMaterialesResult
    {
        public int id { get; set; }
        [StringLength(301)]
        public string CODIGO { get; set; }
        [Column("S/PG")]
        [StringLength(1200)]
        public string SPG { get; set; }
        public int? CANTIDAD { get; set; }
        [StringLength(50)]
        public string UM { get; set; }
        [Column("CU", TypeName = "decimal(38,6)")]
        public decimal CU { get; set; }
        [Column("MONTO", TypeName = "decimal(38,6)")]
        public decimal? MONTO { get; set; }
        [StringLength(64)]
        public string Funcion1 { get; set; }
        [StringLength(64)]
        public string Funcion2 { get; set; }
        [StringLength(64)]
        public string Funcion3 { get; set; }
        [StringLength(254)]
        public string Nombre1 { get; set; }
        [StringLength(254)]
        public string Nombre2 { get; set; }
        [StringLength(254)]
        public string Nombre3 { get; set; }
        [StringLength(254)]
        public string Puesto1 { get; set; }
        [StringLength(254)]
        public string Puesto2 { get; set; }
        [StringLength(254)]
        public string Puesto3 { get; set; }
        [StringLength(128)]
        public string Titulo { get; set; }
    }
}
