// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EG.Infraestructure.Models
{
    public partial class SPR_RepInformesProgResult
    {
        public int ID { get; set; }
        [StringLength(46)]
        public string CONCEPTO { get; set; }
        [Column("AP", TypeName = "decimal(8,2)")]
        public decimal AP { get; set; }
        [Column("AMPREC", TypeName = "decimal(8,2)")]
        public decimal AMPREC { get; set; }
        [Column("MOD", TypeName = "decimal(8,2)")]
        public decimal MOD { get; set; }
        [Column("DEV", TypeName = "decimal(7,2)")]
        public decimal DEV { get; set; }
        [Column("PAG", TypeName = "decimal(7,2)")]
        public decimal PAG { get; set; }
        [Column("SUBEJE", TypeName = "decimal(7,2)")]
        public decimal SUBEJE { get; set; }
        [StringLength(64)]
        public string Funcion1 { get; set; }
        [StringLength(64)]
        public string Funcion2 { get; set; }
        [StringLength(64)]
        public string Funcion3 { get; set; }
        [StringLength(254)]
        public string Nombre1 { get; set; }
        [StringLength(254)]
        public string Nombre2 { get; set; }
        [StringLength(254)]
        public string Nombre3 { get; set; }
        [StringLength(254)]
        public string Puesto1 { get; set; }
        [StringLength(254)]
        public string Puesto2 { get; set; }
        [StringLength(254)]
        public string Puesto3 { get; set; }
        [StringLength(128)]
        public string Titulo { get; set; }
    }
}
