// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EG.Infraestructure.Models
{
    public partial class SPR_EstadoAnaliticoDeudaPasivosResult
    {
        public int id { get; set; }
        [StringLength(500)]
        public string DD { get; set; }
        [StringLength(1)]
        public string MC { get; set; }
        [StringLength(1)]
        public string I { get; set; }
        [StringLength(1)]
        public string SI { get; set; }
        [StringLength(1)]
        public string SF { get; set; }
        [StringLength(64)]
        public string Funcion1 { get; set; }
        [StringLength(64)]
        public string Funcion2 { get; set; }
        [StringLength(64)]
        public string Funcion3 { get; set; }
        [StringLength(254)]
        public string Nombre1 { get; set; }
        [StringLength(254)]
        public string Nombre2 { get; set; }
        [StringLength(254)]
        public string Nombre3 { get; set; }
        [StringLength(254)]
        public string Puesto1 { get; set; }
        [StringLength(254)]
        public string Puesto2 { get; set; }
        [StringLength(254)]
        public string Puesto3 { get; set; }
        [StringLength(128)]
        public string Titulo { get; set; }
    }
}
