// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EG.Infraestructure.Models
{
    public partial class SPR_Entrada_AResult
    {
        [StringLength(50)]
        public string Clave { get; set; }
        [StringLength(1000)]
        public string Descripcion { get; set; }
        [StringLength(50)]
        public string Marca { get; set; }
        [StringLength(50)]
        public string Modelo { get; set; }
        [StringLength(1000)]
        public string Serie { get; set; }
        [StringLength(50)]
        public string Factura { get; set; }
        [Column("ValorActual", TypeName = "decimal(20,4)")]
        public decimal? ValorActual { get; set; }
    }
}
