// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EG.Infraestructure.Models
{
    public partial class SPR_LibroInventarioBienes_DevExResult
    {
        [StringLength(3)]
        public string URG { get; set; }
        [StringLength(50)]
        public string Codigo { get; set; }
        [StringLength(800)]
        public string Descripcion { get; set; }
        [StringLength(50)]
        public string Clave { get; set; }
        [StringLength(1200)]
        public string TipoBien { get; set; }
        [StringLength(1)]
        public string cantidad { get; set; }
        [Column("Costo", TypeName = "decimal(20,4)")]
        public decimal? Costo { get; set; }
        [StringLength(3)]
        public string unidad { get; set; }
        [Column("Monto", TypeName = "decimal(20,4)")]
        public decimal? Monto { get; set; }
    }
}
