// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EG.Infraestructure.Models
{
    public partial class SPR_InventariosdeMateriasResult
    {
        public int id { get; set; }
        [StringLength(301)]
        public string CODIGO { get; set; }
        [Column("S/PG")]
        [StringLength(1200)]
        public string SPG { get; set; }
        public int? CANTIDAD { get; set; }
        [StringLength(50)]
        public string UM { get; set; }
        [Column("CU", TypeName = "decimal(38,6)")]
        public decimal CU { get; set; }
        [Column("MONTO", TypeName = "decimal(38,6)")]
        public decimal? MONTO { get; set; }
        [StringLength(60)]
        public string titulo { get; set; }
    }
}
