// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EG.Infraestructure.Models
{
    public partial class SPR_EstadoActividadesResult
    {
        [StringLength(124)]
        public string Fecha { get; set; }
        public int? Anio { get; set; }
        [StringLength(60)]
        public string IOB_4212000000 { get; set; }
        [StringLength(60)]
        public string IOB_OtrosIngresos { get; set; }
        [StringLength(60)]
        public string T_PATASYOA { get; set; }
        [StringLength(60)]
        public string T_OIYB { get; set; }
        [StringLength(60)]
        public string SubTotalIngresosOtrosBeneficios { get; set; }
        [StringLength(60)]
        public string GOP_5110000000 { get; set; }
        [StringLength(60)]
        public string GOP_5120000000 { get; set; }
        [StringLength(60)]
        public string GOP_5130000000 { get; set; }
        [StringLength(60)]
        public string T_GDF { get; set; }
        [StringLength(60)]
        public string TASYOA_5212200000 { get; set; }
        [StringLength(60)]
        public string TASYOA_5080000000 { get; set; }
        [StringLength(60)]
        public string T_TASYOA { get; set; }
        [StringLength(60)]
        public string GOP_5500000000 { get; set; }
        [StringLength(60)]
        public string GOP_5590000000 { get; set; }
        [StringLength(60)]
        public string T_OGYPE { get; set; }
        [StringLength(60)]
        public string SubtotalGastosYOtrasPerdidas { get; set; }
        [StringLength(60)]
        public string TotalAhorroYDesahorro { get; set; }
    }
}
