// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EG.Infraestructure.Models
{
    public partial class SPR_RepEndeudamientoNetoResult
    {
        public int ID { get; set; }
        [StringLength(6)]
        public string IDEN { get; set; }
        [Column("CONCOL", TypeName = "decimal(9,2)")]
        public decimal CONCOL { get; set; }
        [Column("AM", TypeName = "decimal(8,2)")]
        public decimal AM { get; set; }
        [Column("ENDENETO", TypeName = "decimal(9,2)")]
        public decimal ENDENETO { get; set; }
        [StringLength(64)]
        public string Funcion1 { get; set; }
        [StringLength(64)]
        public string Funcion2 { get; set; }
        [StringLength(64)]
        public string Funcion3 { get; set; }
        [StringLength(254)]
        public string Nombre1 { get; set; }
        [StringLength(254)]
        public string Nombre2 { get; set; }
        [StringLength(254)]
        public string Nombre3 { get; set; }
        [StringLength(254)]
        public string Puesto1 { get; set; }
        [StringLength(254)]
        public string Puesto2 { get; set; }
        [StringLength(254)]
        public string Puesto3 { get; set; }
        [StringLength(128)]
        public string Titulo { get; set; }
    }
}
