// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EG.Infraestructure.Models
{
    public partial class SPR_CambiosSituacionFinancieraResult
    {
        [StringLength(65)]
        public string Fecha { get; set; }
        public int? Anio { get; set; }
        [StringLength(60)]
        public string R_1110000000 { get; set; }
        [StringLength(60)]
        public string R_1120000000 { get; set; }
        [StringLength(60)]
        public string R_1150000000 { get; set; }
        [StringLength(60)]
        public string R_1240000000 { get; set; }
        [StringLength(60)]
        public string R_1250000000 { get; set; }
        [StringLength(62)]
        public string R_1260000000 { get; set; }
        [StringLength(60)]
        public string R_2110000000 { get; set; }
        [StringLength(60)]
        public string R_2160000000 { get; set; }
        [StringLength(60)]
        public string R_3122300000 { get; set; }
        [StringLength(60)]
        public string R_3122200000 { get; set; }
        [StringLength(60)]
        public string R_3210000000 { get; set; }
        [StringLength(60)]
        public string R_3220000000 { get; set; }
        [StringLength(60)]
        public string R_3250000000 { get; set; }
        [StringLength(60)]
        public string R_T_ORIGEN { get; set; }
        [StringLength(60)]
        public string R_T_APLICACION { get; set; }
    }
}
