// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EG.Infraestructure.Models
{
    public partial class spRhExpediente_ListResult
    {
        [StringLength(11)]
        public string Entidad { get; set; }
        public int Id { get; set; }
        public int PersonaId { get; set; }
        public int? EmpresaId { get; set; }
        [StringLength(100)]
        public string Empresa { get; set; }
        [StringLength(152)]
        public string Persona { get; set; }
        [StringLength(15)]
        public string Empleado { get; set; }
        [StringLength(50)]
        public string Clave { get; set; }
        [StringLength(300)]
        public string Titulo { get; set; }
        [StringLength(1000)]
        public string Descripcion { get; set; }
        [StringLength(250)]
        public string Tipo { get; set; }
        [StringLength(19)]
        public string Estatus { get; set; }
        public DateTime? Fecha { get; set; }
        public DateTime? FechaInicio { get; set; }
        public DateTime? FechaFin { get; set; }
        [Column("Importe", TypeName = "decimal(18,2)")]
        public decimal? Importe { get; set; }
        [Column("Porcentaje", TypeName = "decimal(18,4)")]
        public decimal? Porcentaje { get; set; }
        [StringLength(1000)]
        public string Documento { get; set; }
        [StringLength(250)]
        public string Referencia { get; set; }
        [StringLength(2000)]
        public string Observaciones { get; set; }
        public bool Activo { get; set; }
        public int? UsuarioCreacion { get; set; }
        public DateTime? FechaCreacion { get; set; }
        public int? UsuarioModificacion { get; set; }
        public DateTime? FechaModificacion { get; set; }
        public int? TotalCount { get; set; }
    }
}
