// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class Sucursal
{
    public int PkidSucursal { get; set; }

    public int FkidEmpresaSis { get; set; }

    public int FkidEstadoSis { get; set; }

    public string Nombre { get; set; }

    public string CodigoSucursal { get; set; }

    public string Alias { get; set; }

    public int FkidTipoSucursal { get; set; }

    public int? FkidMonedaLocalSis { get; set; }

    public string Direccion { get; set; }

    public string Colonia { get; set; }

    public string Ciudad { get; set; }

    public string CodigoPostal { get; set; }

    public string TelefonoPrincipal { get; set; }

    public string TelefonoSecundario { get; set; }

    public string Email { get; set; }

    public TimeOnly? HorarioApertura { get; set; }

    public TimeOnly? HorarioCierre { get; set; }

    public bool EsMatriz { get; set; }

    public bool EsActiva { get; set; }

    public decimal? Latitud { get; set; }

    public decimal? Longitud { get; set; }

    public bool Activo { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public int UsuarioCreacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public int? UsuarioModificacion { get; set; }

    public virtual ICollection<ArticuloConteo> ArticuloConteos { get; set; } = new List<ArticuloConteo>();

    public virtual ICollection<Departamento> Departamentos { get; set; } = new List<Departamento>();

    public virtual Empresa FkidEmpresaSisNavigation { get; set; }

    public virtual Estado FkidEstadoSisNavigation { get; set; }

    public virtual Monedum FkidMonedaLocalSisNavigation { get; set; }

    public virtual CatTipoSucursal FkidTipoSucursalNavigation { get; set; }

    public virtual ICollection<PeriodoConteo> PeriodoConteos { get; set; } = new List<PeriodoConteo>();

    public virtual ICollection<RegistroConteo> RegistroConteos { get; set; } = new List<RegistroConteo>();

    public virtual ICollection<UsuarioSucursal> UsuarioSucursals { get; set; } = new List<UsuarioSucursal>();
}