// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class TipoContratacion
{
    public int PkidTipoContratacion { get; set; }

    public string Tipo { get; set; }

    public string Descripcion { get; set; }

    public string Explicacion { get; set; }

    public string DoctoComprobacion { get; set; }

    public string Normatividad { get; set; }

    public string Deducciones { get; set; }

    public string DoctoComprob { get; set; }

    public string RelacionLaboral { get; set; }

    public bool Activo { get; set; }

    public DateTime FechaCreacion { get; set; }

    public int UsuarioCreacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public int? UsuarioModificacion { get; set; }

    public virtual Usuario UsuarioCreacionNavigation { get; set; }

    public virtual Usuario UsuarioModificacionNavigation { get; set; }
}