// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class TipoConteo
{
    public int PkidTipoConteo { get; set; }

    public string Nombre { get; set; }

    public string Descripcion { get; set; }

    public bool Activo { get; set; }

    public virtual ICollection<PeriodoConteo> PeriodoConteos { get; set; } = new List<PeriodoConteo>();
}