// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class TipoPatrimonio1
{
    public int PkIdTipoPatrimonio { get; set; }

    public string Descripcion { get; set; }

    public bool Activo { get; set; }

    public int CtCreatedBy { get; set; }

    public DateTime? CtCreatedDate { get; set; }

    public int? CtModifiedBy { get; set; }

    public DateTime? CtModifiedDate { get; set; }

    public bool CtLive { get; set; }
}