// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class TipoBien
{
    public int PkidTipoBien { get; set; }

    public int? FkidGrupoBienAlma { get; set; }

    public int? FkidNivelAlma { get; set; }

    public int? FkidPartidaConta { get; set; }

    public int? FkidCuentaContableConta { get; set; }

    public int? FkidUnidadesAlma { get; set; }

    public int? FkidLocalizacionAlma { get; set; }

    public string CodigoClave { get; set; }

    public string Descripcion { get; set; }

    public decimal? DepreciacionAnual { get; set; }

    public int? Consecutivo { get; set; }

    public string Cabms { get; set; }

    public string Identificador { get; set; }

    public decimal? ExistenciaMinima { get; set; }

    public decimal? ExistenciaMaxima { get; set; }

    public int? TiempoVida { get; set; }

    public int? PkIdTratadoInt { get; set; }

    public decimal? Cuota { get; set; }

    public bool? ProveeduriaNac { get; set; }

    public bool? CatalogoBasico { get; set; }

    public string CucopPlus { get; set; }

    public bool Activo { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public int UsuarioCreacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public int? UsuarioModificacion { get; set; }

    public int? FkidUnidadesEquivalente { get; set; }

    public int? CantidadEquivalente { get; set; }

    public virtual ICollection<ArticuloConteo> ArticuloConteos { get; set; } = new List<ArticuloConteo>();

    public virtual ICollection<Bien> Biens { get; set; } = new List<Bien>();

    public virtual CuentaContable FkidCuentaContableContaNavigation { get; set; }

    public virtual GrupoBien FkidGrupoBienAlmaNavigation { get; set; }

    public virtual Nivel FkidNivelAlmaNavigation { get; set; }

    public virtual Partidum FkidPartidaContaNavigation { get; set; }

    public virtual Unidade FkidUnidadesAlmaNavigation { get; set; }

    public virtual Unidade FkidUnidadesEquivalenteNavigation { get; set; }
}