// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class Unidade
{
    public int PkidUnidades { get; set; }

    public string Descripcion { get; set; }

    public bool Activo { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public int UsuarioCreacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public int? UsuarioModificacion { get; set; }

    public virtual ICollection<TipoBien> TipoBienFkidUnidadesAlmaNavigations { get; set; } = new List<TipoBien>();

    public virtual ICollection<TipoBien> TipoBienFkidUnidadesEquivalenteNavigations { get; set; } = new List<TipoBien>();
}