// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class Usuario
{
    public int PkIdUsuario { get; set; }

    public int FkidEmpresaSis { get; set; }

    public string AspNetUserId { get; set; }

    public string Nombre { get; set; }

    public string ApellidoPaterno { get; set; }

    public string ApellidoMaterno { get; set; }

    public string Iniciales { get; set; }

    public string PayrollId { get; set; }

    public string CodigoPostal { get; set; }

    public string Telefono { get; set; }

    public string Direccion1 { get; set; }

    public string Direccion2 { get; set; }

    public string Email { get; set; }

    public string NumeroSocial { get; set; }

    public string Gafete { get; set; }

    public bool Sexo { get; set; }

    public DateOnly? FechaIngreso { get; set; }

    public int? FkidIdiomaPreferidoSis { get; set; }

    public int? FkidMonedaPreferidaSis { get; set; }

    public bool EsAdministrador { get; set; }

    public bool Activo { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public int UsuarioCreacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public int? UsuarioModificacion { get; set; }

    public virtual ICollection<Anio> AnioUsuarioCreacionNavigations { get; set; } = new List<Anio>();

    public virtual ICollection<Anio> AnioUsuarioModificacionNavigations { get; set; } = new List<Anio>();

    public virtual ICollection<Articulo> ArticuloUsuarioCreacionNavigations { get; set; } = new List<Articulo>();

    public virtual ICollection<Articulo> ArticuloUsuarioModificacionNavigations { get; set; } = new List<Articulo>();

    public virtual ICollection<AspNetUser> AspNetUsers { get; set; } = new List<AspNetUser>();

    public virtual ICollection<ConteoDetalleEscaneo> ConteoDetalleEscaneoUsuarioCreacionNavigations { get; set; } = new List<ConteoDetalleEscaneo>();

    public virtual ICollection<ConteoDetalleEscaneo> ConteoDetalleEscaneoUsuarioModificacionNavigations { get; set; } = new List<ConteoDetalleEscaneo>();

    public virtual ICollection<ConteoDetalle> ConteoDetalleUsuarioCreacionNavigations { get; set; } = new List<ConteoDetalle>();

    public virtual ICollection<ConteoDetalle> ConteoDetalleUsuarioModificacionNavigations { get; set; } = new List<ConteoDetalle>();

    public virtual ICollection<Conteo> ConteoUsuarioCreacionNavigations { get; set; } = new List<Conteo>();

    public virtual ICollection<Conteo> ConteoUsuarioModificacionNavigations { get; set; } = new List<Conteo>();

    public virtual ICollection<Departamento> DepartamentoUsuarioCreacionNavigations { get; set; } = new List<Departamento>();

    public virtual ICollection<Departamento> DepartamentoUsuarioModificacionNavigations { get; set; } = new List<Departamento>();

    public virtual ICollection<DestinoGasto> DestinoGastoUsuarioCreacionNavigations { get; set; } = new List<DestinoGasto>();

    public virtual ICollection<DestinoGasto> DestinoGastoUsuarioModificacionNavigations { get; set; } = new List<DestinoGasto>();

    public virtual ICollection<DetalleRequisicion> DetalleRequisicionUsuarioCreacionNavigations { get; set; } = new List<DetalleRequisicion>();

    public virtual ICollection<DetalleRequisicion> DetalleRequisicionUsuarioModificacionNavigations { get; set; } = new List<DetalleRequisicion>();

    public virtual ICollection<DigitoIdentificador> DigitoIdentificadorUsuarioCreacionNavigations { get; set; } = new List<DigitoIdentificador>();

    public virtual ICollection<DigitoIdentificador> DigitoIdentificadorUsuarioModificacionNavigations { get; set; } = new List<DigitoIdentificador>();

    public virtual ICollection<EgresoAutorizado> EgresoAutorizadoUsuarioCreacionNavigations { get; set; } = new List<EgresoAutorizado>();

    public virtual ICollection<EgresoAutorizado> EgresoAutorizadoUsuarioModificacionNavigations { get; set; } = new List<EgresoAutorizado>();

    public virtual ICollection<Empresa> EmpresaUsuarioCreacionNavigations { get; set; } = new List<Empresa>();

    public virtual ICollection<Empresa> EmpresaUsuarioModificacionNavigations { get; set; } = new List<Empresa>();

    public virtual ICollection<EstatusRequisicion> EstatusRequisicionUsuarioCreacionNavigations { get; set; } = new List<EstatusRequisicion>();

    public virtual ICollection<EstatusRequisicion> EstatusRequisicionUsuarioModificacionNavigations { get; set; } = new List<EstatusRequisicion>();

    public virtual Empresa FkidEmpresaSisNavigation { get; set; }

    public virtual Idioma FkidIdiomaPreferidoSisNavigation { get; set; }

    public virtual Monedum FkidMonedaPreferidaSisNavigation { get; set; }

    public virtual ICollection<Fraccion> FraccionUsuarioCreacionNavigations { get; set; } = new List<Fraccion>();

    public virtual ICollection<Fraccion> FraccionUsuarioModificacionNavigations { get; set; } = new List<Fraccion>();

    public virtual ICollection<FuenteFinanciamiento> FuenteFinanciamientoUsuarioCreacionNavigations { get; set; } = new List<FuenteFinanciamiento>();

    public virtual ICollection<FuenteFinanciamiento> FuenteFinanciamientoUsuarioModificacionNavigations { get; set; } = new List<FuenteFinanciamiento>();

    public virtual ICollection<Usuario> InverseUsuarioCreacionNavigation { get; set; } = new List<Usuario>();

    public virtual ICollection<Usuario> InverseUsuarioModificacionNavigation { get; set; } = new List<Usuario>();

    public virtual ICollection<Modalidad> ModalidadUsuarioCreacionNavigations { get; set; } = new List<Modalidad>();

    public virtual ICollection<Modalidad> ModalidadUsuarioModificacionNavigations { get; set; } = new List<Modalidad>();

    public virtual ICollection<OrigenLogMessage> OrigenLogMessageUsuarioCreacionNavigations { get; set; } = new List<OrigenLogMessage>();

    public virtual ICollection<OrigenLogMessage> OrigenLogMessageUsuarioModificacionNavigations { get; set; } = new List<OrigenLogMessage>();

    public virtual PerfilUsuario PerfilUsuarioFkidUsuarioSisNavigation { get; set; }

    public virtual ICollection<PerfilUsuario> PerfilUsuarioUsuarioCreacionNavigations { get; set; } = new List<PerfilUsuario>();

    public virtual ICollection<PerfilUsuario> PerfilUsuarioUsuarioModificacionNavigations { get; set; } = new List<PerfilUsuario>();

    public virtual ICollection<PeriodoConteo> PeriodoConteoFkidResponsableSisNavigations { get; set; } = new List<PeriodoConteo>();

    public virtual ICollection<PeriodoConteo> PeriodoConteoFkidSupervisorSisNavigations { get; set; } = new List<PeriodoConteo>();

    public virtual ICollection<ProcedimientoContratacion> ProcedimientoContratacionUsuarioCreacionNavigations { get; set; } = new List<ProcedimientoContratacion>();

    public virtual ICollection<ProcedimientoContratacion> ProcedimientoContratacionUsuarioModificacionNavigations { get; set; } = new List<ProcedimientoContratacion>();

    public virtual ICollection<Programa> ProgramaUsuarioCreacionNavigations { get; set; } = new List<Programa>();

    public virtual ICollection<Programa> ProgramaUsuarioModificacionNavigations { get; set; } = new List<Programa>();

    public virtual ICollection<Proyecto> ProyectoUsuarioCreacionNavigations { get; set; } = new List<Proyecto>();

    public virtual ICollection<Proyecto> ProyectoUsuarioModificacionNavigations { get; set; } = new List<Proyecto>();

    public virtual ICollection<RequisicionPartidum> RequisicionPartidumUsuarioCreacionNavigations { get; set; } = new List<RequisicionPartidum>();

    public virtual ICollection<RequisicionPartidum> RequisicionPartidumUsuarioModificacionNavigations { get; set; } = new List<RequisicionPartidum>();

    public virtual ICollection<Requisicion> RequisicionUsuarioCreacionNavigations { get; set; } = new List<Requisicion>();

    public virtual ICollection<Requisicion> RequisicionUsuarioModificacionNavigations { get; set; } = new List<Requisicion>();

    public virtual ICollection<Sucursal> SucursalUsuarioCreacionNavigations { get; set; } = new List<Sucursal>();

    public virtual ICollection<Sucursal> SucursalUsuarioModificacionNavigations { get; set; } = new List<Sucursal>();

    public virtual ICollection<Suficiencium> SuficienciumUsuarioCreacionNavigations { get; set; } = new List<Suficiencium>();

    public virtual ICollection<Suficiencium> SuficienciumUsuarioModificacionNavigations { get; set; } = new List<Suficiencium>();

    public virtual ICollection<SystemParamCatalog> SystemParamCatalogUsuarioCreacionNavigations { get; set; } = new List<SystemParamCatalog>();

    public virtual ICollection<SystemParamCatalog> SystemParamCatalogUsuarioModificacionNavigations { get; set; } = new List<SystemParamCatalog>();

    public virtual ICollection<SystemParamValue> SystemParamValueUsuarioCreacionNavigations { get; set; } = new List<SystemParamValue>();

    public virtual ICollection<SystemParamValue> SystemParamValueUsuarioModificacionNavigations { get; set; } = new List<SystemParamValue>();

    public virtual ICollection<TipoContrato> TipoContratoUsuarioCreacionNavigations { get; set; } = new List<TipoContrato>();

    public virtual ICollection<TipoContrato> TipoContratoUsuarioModificacionNavigations { get; set; } = new List<TipoContrato>();

    public virtual ICollection<TipoDocumento> TipoDocumentoUsuarioCreacionNavigations { get; set; } = new List<TipoDocumento>();

    public virtual ICollection<TipoDocumento> TipoDocumentoUsuarioModificacionNavigations { get; set; } = new List<TipoDocumento>();

    public virtual ICollection<TipoGarantium> TipoGarantiumUsuarioCreacionNavigations { get; set; } = new List<TipoGarantium>();

    public virtual ICollection<TipoGarantium> TipoGarantiumUsuarioModificacionNavigations { get; set; } = new List<TipoGarantium>();

    public virtual ICollection<TipoGasto> TipoGastoUsuarioCreacionNavigations { get; set; } = new List<TipoGasto>();

    public virtual ICollection<TipoGasto> TipoGastoUsuarioModificacionNavigations { get; set; } = new List<TipoGasto>();

    public virtual Usuario UsuarioCreacionNavigation { get; set; }

    public virtual ICollection<UsuarioDepartamento> UsuarioDepartamentoFkidUsuarioSisNavigations { get; set; } = new List<UsuarioDepartamento>();

    public virtual ICollection<UsuarioDepartamento> UsuarioDepartamentoUsuarioCreacionNavigations { get; set; } = new List<UsuarioDepartamento>();

    public virtual ICollection<UsuarioDepartamento> UsuarioDepartamentoUsuarioModificacionNavigations { get; set; } = new List<UsuarioDepartamento>();

    public virtual Usuario UsuarioModificacionNavigation { get; set; }

    public virtual ICollection<UsuarioSucursal> UsuarioSucursalFkidUsuarioSisNavigations { get; set; } = new List<UsuarioSucursal>();

    public virtual ICollection<UsuarioSucursal> UsuarioSucursalUsuarioCreacionNavigations { get; set; } = new List<UsuarioSucursal>();

    public virtual ICollection<UsuarioSucursal> UsuarioSucursalUsuarioModificacionNavigations { get; set; } = new List<UsuarioSucursal>();
}