// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class Usuario
{
    public int PkIdUsuario { get; set; }

    public int FkidEmpresaSis { get; set; }

    public string AspNetUserId { get; set; }

    public string Nombre { get; set; }

    public string ApellidoPaterno { get; set; }

    public string ApellidoMaterno { get; set; }

    public string Iniciales { get; set; }

    public string PayrollId { get; set; }

    public string CodigoPostal { get; set; }

    public string Telefono { get; set; }

    public string Direccion1 { get; set; }

    public string Direccion2 { get; set; }

    public string Email { get; set; }

    public string NumeroSocial { get; set; }

    public string Gafete { get; set; }

    public bool Sexo { get; set; }

    public DateOnly? FechaIngreso { get; set; }

    public int? FkidIdiomaPreferidoSis { get; set; }

    public int? FkidMonedaPreferidaSis { get; set; }

    public bool EsAdministrador { get; set; }

    public bool Activo { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public int UsuarioCreacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public int? UsuarioModificacion { get; set; }

    public virtual ICollection<ArticuloConteo> ArticuloConteos { get; set; } = new List<ArticuloConteo>();

    public virtual ICollection<AspNetUser> AspNetUsers { get; set; } = new List<AspNetUser>();

    public virtual ICollection<DiscrepanciaConteo> DiscrepanciaConteos { get; set; } = new List<DiscrepanciaConteo>();

    public virtual Empresa FkidEmpresaSisNavigation { get; set; }

    public virtual Idioma FkidIdiomaPreferidoSisNavigation { get; set; }

    public virtual Monedum FkidMonedaPreferidaSisNavigation { get; set; }

    public virtual ICollection<HistorialEstatusArticulo> HistorialEstatusArticulos { get; set; } = new List<HistorialEstatusArticulo>();

    public virtual PerfilUsuario PerfilUsuario { get; set; }

    public virtual ICollection<PeriodoConteo> PeriodoConteoFkidResponsableSisNavigations { get; set; } = new List<PeriodoConteo>();

    public virtual ICollection<PeriodoConteo> PeriodoConteoFkidSupervisorSisNavigations { get; set; } = new List<PeriodoConteo>();

    public virtual ICollection<RegistroConteo> RegistroConteos { get; set; } = new List<RegistroConteo>();

    public virtual ICollection<UsuarioDepartamento> UsuarioDepartamentos { get; set; } = new List<UsuarioDepartamento>();

    public virtual ICollection<UsuarioSucursal> UsuarioSucursals { get; set; } = new List<UsuarioSucursal>();
}