// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class VwBaja
{
    public int PkidBaja { get; set; }

    public string Folio { get; set; }

    public int FkidEmpresaSis { get; set; }

    public int? FkidAnioSis { get; set; }

    public string EmpresaNombre { get; set; }

    public int? FkidAreaSis { get; set; }

    public string AreaClave { get; set; }

    public string AreaNombre { get; set; }

    public int FkidBienAlma { get; set; }

    public string BienClave { get; set; }

    public string BienClaveAnterior { get; set; }

    public string BienDescripcion { get; set; }

    public string Modelo { get; set; }

    public string Serie { get; set; }

    public string Factura { get; set; }

    public decimal? ValorActual { get; set; }

    public int FkidTipoBienAlma { get; set; }

    public string TipoBienCodigoClave { get; set; }

    public string TipoBienDescripcion { get; set; }

    public int FkidTipoBajaAlma { get; set; }

    public string TipoBajaClave { get; set; }

    public string TipoBajaDescripcion { get; set; }

    public int FkidEstatusBajaAlma { get; set; }

    public string EstatusDescripcion { get; set; }

    public string EstatusColor { get; set; }

    public int? FkidEstadoBienAnteriorAlma { get; set; }

    public string EstadoAnterior { get; set; }

    public int? FkidEstadoBienDestinoAlma { get; set; }

    public string EstadoDestino { get; set; }

    public DateOnly FechaSolicitud { get; set; }

    public DateOnly? FechaBaja { get; set; }

    public string Referencia { get; set; }

    public DateOnly? FechaReferencia { get; set; }

    public string Destinatario { get; set; }

    public string Recibo { get; set; }

    public decimal? Cantidad { get; set; }

    public string Motivo { get; set; }

    public string Dictamen { get; set; }

    public string Observaciones { get; set; }

    public int? FkidPolizaConta { get; set; }

    public string ClavePoliza { get; set; }

    public int? SolicitadoPorNom { get; set; }

    public int? AutorizadoPorNom { get; set; }

    public DateTime? FechaAutorizacion { get; set; }

    public bool Activo { get; set; }

    public DateTime FechaCreacion { get; set; }

    public int UsuarioCreacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public int? UsuarioModificacion { get; set; }
}