// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class VwCalendarioPresupuesto
{
    public int PkidCalendario { get; set; }

    public int Anio { get; set; }

    public DateTime Fecha { get; set; }

    public DateTime? FechaFin { get; set; }

    public string Titulo { get; set; }

    public string Descripcion { get; set; }

    public string Etapa { get; set; }

    public int? FkidProgramaPresupuestarioPbr { get; set; }

    public string Tipo { get; set; }

    public int Orden { get; set; }

    public string Color { get; set; }

    public DateTime FechaCreacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public int? FkidProgramaPres { get; set; }

    public string ProgramaDescripcion { get; set; }
}