// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class VwCalendarioInventario
{
    public int PkidCalendarioInventario { get; set; }

    public int FkidEmpresaSis { get; set; }

    public string EmpresaNombre { get; set; }

    public int? FkidAreaSis { get; set; }

    public string AreaNombre { get; set; }

    public int Anio { get; set; }

    public string Folio { get; set; }

    public string Descripcion { get; set; }

    public DateOnly FechaInicio { get; set; }

    public DateOnly FechaFin { get; set; }

    public string Observaciones { get; set; }

    public bool Activo { get; set; }

    public DateTime FechaCreacion { get; set; }

    public int UsuarioCreacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public int? UsuarioModificacion { get; set; }
}