// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class VwContratoLaboral
{
    public int PkidContratoLaboral { get; set; }

    public int EmpresaNominaId { get; set; }

    public string EmpresaNominaNombre { get; set; }

    public int PersonaId { get; set; }

    public string PersonaClaveNombre { get; set; }

    public DateOnly FechaInicio { get; set; }

    public DateOnly FechaFin { get; set; }

    public int PuestoId { get; set; }

    public string PuestoNombre { get; set; }

    public string NumeroContrato { get; set; }

    public string Vigencia { get; set; }

    public decimal SueldoMensual { get; set; }

    public int? NombramientoId { get; set; }

    public string NombramientoDescripcion { get; set; }

    public bool? Vigente { get; set; }

    public bool Activo { get; set; }

    public int? UsuarioCreacion { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public int? UsuarioModificacion { get; set; }

    public DateTime? FechaModificacion { get; set; }
}