// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class VwContrato2
{
    public int PkidContrato { get; set; }

    public int FkidEmpresaSis { get; set; }

    public string EmpresaNombre { get; set; }

    public int FkidAutorizacionSuficienciaPres { get; set; }

    public int FkidSolicitudSuficienciaPres { get; set; }

    public int? FkidRequisicionOrco { get; set; }

    public string RequisicionDescripcion { get; set; }

    public int FkidProveedorSis { get; set; }

    public string ProveedorClave { get; set; }

    public string ProveedorNombre { get; set; }

    public string ProveedorRfc { get; set; }

    public int? FkidPolizaConta { get; set; }

    public string ClavePoliza { get; set; }

    public string NumeroContrato { get; set; }

    public string Descripcion { get; set; }

    public DateOnly FechaContrato { get; set; }

    public DateOnly? FechaInicioVigencia { get; set; }

    public DateOnly? FechaFinVigencia { get; set; }

    public decimal MontoTotal { get; set; }

    public string PlazoEjecucion { get; set; }

    public string Observaciones { get; set; }

    public int Estatus { get; set; }

    public string EstatusDescripcion { get; set; }

    public bool Activo { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public int UsuarioCreacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public int? UsuarioModificacion { get; set; }
}