// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class VwConceptoFijo
{
    public int PkidConceptoFijo { get; set; }

    public int EmpresaId { get; set; }

    public string EmpresaNombre { get; set; }

    public int ConceptoId { get; set; }

    public string ConceptoClave { get; set; }

    public string ConceptoNombre { get; set; }

    public string ConceptoClaveNombre { get; set; }

    public int PuestoId { get; set; }

    public string PuestoNombre { get; set; }

    public string PuestoClaveNombre { get; set; }

    public int? NivelId { get; set; }

    public string NivelClave { get; set; }

    public int? UniversoId { get; set; }

    public string UniversoDescripcion { get; set; }

    public int? ClasePuestoId { get; set; }

    public string ClasePuestoDescripcion { get; set; }

    public decimal? ImporteMensualFijo { get; set; }

    public DateOnly? FechaInicio { get; set; }

    public DateOnly? FechaFin { get; set; }

    public bool? Vigente { get; set; }

    public bool Activo { get; set; }

    public int? UsuarioCreacion { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public int? UsuarioModificacion { get; set; }

    public DateTime? FechaModificacion { get; set; }
}