// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class VwConteoDetalle
{
    public int PkidConteo { get; set; }

    public int FkidTipoBienAlma { get; set; }

    public string TipoBienDescripcion { get; set; }

    public decimal CantidadInventarioInicial { get; set; }

    public string ConteoDescripcion { get; set; }

    public DateTime FechaInicio { get; set; }

    public DateTime? FechaFin { get; set; }

    public bool ConteoActivo { get; set; }

    public DateTime? ConteoFechaCreacion { get; set; }

    public int ConteoUsuarioCreacion { get; set; }

    public DateTime? ConteoFechaModificacion { get; set; }

    public int? ConteoUsuarioModificacion { get; set; }

    public int PkidDetalleConteo { get; set; }

    public int FkidConteoAlma { get; set; }

    public int FkidNumeroConteoAlma { get; set; }

    public int FkidPersonaNom { get; set; }

    public string PersonaNombre { get; set; }

    public string PersonaPaterno { get; set; }

    public string PersonaMaterno { get; set; }

    public decimal CantidadContada { get; set; }

    public DateTime FechaConteo { get; set; }

    public bool DetalleActivo { get; set; }

    public DateTime? DetalleFechaCreacion { get; set; }

    public int DetalleUsuarioCreacion { get; set; }

    public DateTime? DetalleFechaModificacion { get; set; }

    public int? DetalleUsuarioModificacion { get; set; }
}