// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class VwCredito
{
    public int PkidCredito { get; set; }

    public int? EmpresaId { get; set; }

    public string EmpresaNombre { get; set; }

    public int PersonaId { get; set; }

    public string PersonaClaveNombre { get; set; }

    public int ContratoTerceroId { get; set; }

    public string NombreContrato { get; set; }

    public string MotivoCredito { get; set; }

    public decimal? ImporteCredito { get; set; }

    public decimal? TasaInteres { get; set; }

    public int NumeroPagos { get; set; }

    public int PeriodoInicialId { get; set; }

    public decimal? ImportePago { get; set; }

    public int? PagosRegistrados { get; set; }

    public int? PagosDescontados { get; set; }

    public decimal? SaldoEstimado { get; set; }

    public bool Activo { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public int? UsuarioCreacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public int? UsuarioModificacion { get; set; }
}