// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class VwDetalleArticulo
{
    public int PkidArticuloConteo { get; set; }

    public string CodigoPeriodo { get; set; }

    public string Periodo { get; set; }

    public string Sucursal { get; set; }

    public string CodigoArticulo { get; set; }

    public string Articulo { get; set; }

    public decimal ExistenciaSistema { get; set; }

    public decimal? ExistenciaFinal { get; set; }

    public decimal? Diferencia { get; set; }

    public decimal? PorcentajeDiferencia { get; set; }

    public string Estatus { get; set; }

    public int ConteosRealizados { get; set; }

    public int ConteosPendientes { get; set; }

    public DateTime? FechaInicioConteo { get; set; }

    public DateTime? FechaConclusion { get; set; }

    public string ConcluidoPor { get; set; }

    public string HistorialConteos { get; set; }
}