// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class VwDescuentoCredito
{
    public int PkidDescuentoCredito { get; set; }

    public int? EmpresaId { get; set; }

    public string EmpresaNombre { get; set; }

    public int CreditoId { get; set; }

    public string MotivoCredito { get; set; }

    public string PersonaClaveNombre { get; set; }

    public int PeriodoId { get; set; }

    public int NumeroPago { get; set; }

    public bool EstaDescontado { get; set; }

    public DateOnly? FechaDescuento { get; set; }

    public bool Activo { get; set; }

    public int? UsuarioCreacion { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public int? UsuarioModificacion { get; set; }

    public DateTime? FechaModificacion { get; set; }
}