// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class VwDocumentoResumenAnotacion
{
    public long FkidDocumento { get; set; }

    public int? TotalAnotaciones { get; set; }

    public int? TotalComentarios { get; set; }

    public int? TotalResaltados { get; set; }

    public DateTime? UltimaAnotacion { get; set; }
}