// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class VwEgresoAutorizado
{
    public int PkidEgresoAutorizado { get; set; }

    public int FkidEmpresaSis { get; set; }

    public int? FkidEgresoProyectadoPres { get; set; }

    public int? FkidAnioSis { get; set; }

    public int? AnioClave { get; set; }

    public int FkidProgramaPres { get; set; }

    public string ProgramaClave { get; set; }

    public string ProgramaDescripcion { get; set; }

    public string ProgramaClaveNombre { get; set; }

    public int FkidPartidaConta { get; set; }

    public string PartidaClave { get; set; }

    public string PartidaDescripcion { get; set; }

    public string PartidaClaveNombre { get; set; }

    public int FkidAreaSis { get; set; }

    public string AreaClave { get; set; }

    public string AreaNombre { get; set; }

    public string Descripcion { get; set; }

    public DateOnly Fecha { get; set; }

    public int? FkidPolizaConta { get; set; }

    public int? FkidFuenteFinanciamientoPres { get; set; }

    public string FuenteFinanciamientoClave { get; set; }

    public string FuenteFinanciamientoDescripcion { get; set; }

    public string FuenteFinanciamientoClaveNombre { get; set; }

    public int? FkidTipoGastoPres { get; set; }

    public int? TipoGastoClave { get; set; }

    public string TipoGastoDescripcion { get; set; }

    public string TipoGastoClaveNombre { get; set; }

    public int? FkidDigitoIdentificadorPres { get; set; }

    public string DigitoIdentificadorClave { get; set; }

    public string DigitoIdentificadorDescripcion { get; set; }

    public string DigitoIdentificadorClaveNombre { get; set; }

    public int? FkidDestinoGastoPres { get; set; }

    public string DestinoGastoClave { get; set; }

    public string DestinoGastoDescripcion { get; set; }

    public string DestinoGastoClaveNombre { get; set; }

    public int? FkidPyPres { get; set; }

    public string PyClave { get; set; }

    public string PyDescripcion { get; set; }

    public string PyClaveNombre { get; set; }

    public decimal Enero { get; set; }

    public decimal Febrero { get; set; }

    public decimal Marzo { get; set; }

    public decimal Abril { get; set; }

    public decimal Mayo { get; set; }

    public decimal Junio { get; set; }

    public decimal Julio { get; set; }

    public decimal Agosto { get; set; }

    public decimal Septiembre { get; set; }

    public decimal Octubre { get; set; }

    public decimal Noviembre { get; set; }

    public decimal Diciembre { get; set; }

    public decimal? Total { get; set; }

    public DateTime? FechaAutorizacion { get; set; }

    public int? UsuarioAutorizacion { get; set; }

    public bool Activo { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public int UsuarioCreacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public int? UsuarioModificacion { get; set; }
}