// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class VwEgresoAdecuacionDetalle
{
    public int PkidEgreAdecuacionDetalle { get; set; }

    public int FkidEgreAdecuacionPres { get; set; }

    public string EgreAdecuacionClave { get; set; }

    public bool? Autorizado { get; set; }

    public int FkidEmpresaSis { get; set; }

    public int FkidAnioSis { get; set; }

    public int? FkidEgresoAutorizadoPres { get; set; }

    public string EgresoAutorizadoDescripcion { get; set; }

    public int FkidTipoMovimientoPres { get; set; }

    public string TipoMovimientoDescripcion { get; set; }

    public string Justificacion { get; set; }

    public DateOnly Fecha { get; set; }

    public decimal? Enero { get; set; }

    public decimal? Febrero { get; set; }

    public decimal? Marzo { get; set; }

    public decimal? Abril { get; set; }

    public decimal? Mayo { get; set; }

    public decimal? Junio { get; set; }

    public decimal? Julio { get; set; }

    public decimal? Agosto { get; set; }

    public decimal? Septiembre { get; set; }

    public decimal? Octubre { get; set; }

    public decimal? Noviembre { get; set; }

    public decimal? Diciembre { get; set; }

    public decimal? Total { get; set; }

    public bool Activo { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public int UsuarioCreacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public int? UsuarioModificacion { get; set; }
}
