// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class VwEgresoAdecuacion
{
    public int PkidEgreAdecuacion { get; set; }

    public string Clave { get; set; }

    public int FkidTipoAdecuacionPres { get; set; }

    public string TipoAdecuacionDescripcion { get; set; }

    public int FkidEstatusAdecuacionPres { get; set; }

    public string EstatusAdecuacionDescripcion { get; set; }

    public string EstatusAdecuacionColor { get; set; }

    public string Justificacion { get; set; }

    public DateOnly Fecha { get; set; }

    public int? FkidPolizaConta { get; set; }

    public string ClavePoliza { get; set; }

    public int FkidAnioSis { get; set; }

    public int? AnioClave { get; set; }

    public bool? Autorizado { get; set; }

    public int? FkidAccionAdecuacionMasterPres { get; set; }

    public string AccionAdecuacion { get; set; }

    public string AccionComentario { get; set; }

    public DateTime? FechaSolicitud { get; set; }

    public DateTime? FechaAutorizacion { get; set; }

    public bool Activo { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public int UsuarioCreacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public int? UsuarioModificacion { get; set; }

    public string ClaveNombre { get; set; }
}