// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class VwEmpresaNomina
{
    public int PkidEmpresa { get; set; }

    public string RazonSocial { get; set; }

    public string RegImss { get; set; }

    public string RegInfonavit { get; set; }

    public string CedEmpadronam { get; set; }

    public string NoFonacot { get; set; }

    public string UsAdmin { get; set; }

    public string EmailAdmin { get; set; }

    public int? PeriodoPagoId { get; set; }

    public decimal? PrimaRiesgoImss { get; set; }

    public bool UsaSueldoTabular { get; set; }

    public int? TipoPagoId { get; set; }

    public string ClaveNombre { get; set; }

    public bool Activo { get; set; }

    public int? UsuarioCreacion { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public int? UsuarioModificacion { get; set; }

    public DateTime? FechaModificacion { get; set; }
}