// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class VwExistencia
{
    public int PkidTipoBien { get; set; }

    public int? FkidPartidaConta { get; set; }

    public string Cucop { get; set; }

    public string Cabms { get; set; }

    public string CodigoClave { get; set; }

    public string Descripcion { get; set; }

    public int? Existencias { get; set; }

    public string Unidades { get; set; }

    public int FkIdAnioSis { get; set; }

    public string Message { get; set; }

    public int? FkIdUnidadesAlma { get; set; }

    public decimal CostoUnitario { get; set; }

    public decimal CostoPromedio { get; set; }
}