// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class VwFacturasPendientesPago
{
    public int Id { get; set; }

    public string Nocuenta { get; set; }

    public string Nomdeno { get; set; }

    public decimal Saldo { get; set; }

    public DateTime? Fechaemi { get; set; }

    public int? Diasvencidos { get; set; }

    public int? Rango01 { get; set; }

    public int? Rango31 { get; set; }

    public int? Rango61 { get; set; }

    public int? Rango90mas { get; set; }

    public string Motivo { get; set; }
}