// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class VwFraccion
{
    public int PkidFraccion { get; set; }

    public int FkidArticuloOrco { get; set; }

    public string Clave { get; set; }

    public string Descripcion { get; set; }

    public bool Activo { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public int UsuarioCreacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public int? UsuarioModificacion { get; set; }

    public string ArticuloDescripcion { get; set; }

    public string ArticuloClave { get; set; }

    public string ArticuloClaveNombre { get; set; }
}