// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class VwInventario
{
    public int PkidInventario { get; set; }

    public int FkidEmpresaSis { get; set; }

    public string EmpresaNombre { get; set; }

    public int? FkidCalendarioInventarioAlma { get; set; }

    public string CalendarioFolio { get; set; }

    public int? FkidAreaSis { get; set; }

    public string AreaNombre { get; set; }

    public int FkidEstatusInventarioAlma { get; set; }

    public string EstatusDescripcion { get; set; }

    public string EstatusColor { get; set; }

    public string Folio { get; set; }

    public DateOnly FechaInventario { get; set; }

    public string Responsable { get; set; }

    public string Observaciones { get; set; }

    public int TotalBienes { get; set; }

    public int TotalLocalizados { get; set; }

    public int TotalDiferencias { get; set; }

    public bool Autorizado { get; set; }

    public DateTime? FechaAutorizacion { get; set; }

    public int? UsuarioAutorizacion { get; set; }

    public bool Activo { get; set; }

    public DateTime FechaCreacion { get; set; }

    public int UsuarioCreacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public int? UsuarioModificacion { get; set; }
}