// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class VwIndicador
{
    public int PkidIndicador { get; set; }

    public int FkidMirNivelPbr { get; set; }

    public string Nombre { get; set; }

    public string Definicion { get; set; }

    public string Tipo { get; set; }

    public string Dimension { get; set; }

    public string Formula { get; set; }

    public string Algoritmo { get; set; }

    public string Frecuencia { get; set; }

    public string Unidad { get; set; }

    public string LineaBase { get; set; }

    public string Meta { get; set; }

    public string MedioVerificacion { get; set; }

    public string Supuesto { get; set; }

    public string Sentido { get; set; }

    public DateTime FechaCreacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public string Nivel { get; set; }

    public string MirObjetivo { get; set; }

    public int? FkidProgramaPres { get; set; }

    public string ProgramaDescripcion { get; set; }
}