// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class VwIngreXejer
{
    public int PkIdIngresoAutorizado { get; set; }

    public string AreaFuncional { get; set; }

    public string Origen { get; set; }

    public int? FkIdAnioSis { get; set; }

    public int FkIdProgramaPres { get; set; }

    public int FkIdOrigenPres { get; set; }

    public string Descripcion { get; set; }

    public decimal? Ene { get; set; }

    public decimal? Feb { get; set; }

    public decimal? Mar { get; set; }

    public decimal? Abr { get; set; }

    public decimal? May { get; set; }

    public decimal? Jun { get; set; }

    public decimal? Jul { get; set; }

    public decimal? Ago { get; set; }

    public decimal? Sep { get; set; }

    public decimal? Oct { get; set; }

    public decimal? Nov { get; set; }

    public decimal? Dic { get; set; }

    public decimal? Total { get; set; }

    public string Message { get; set; }
}