// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class VwInventarioDetalle
{
    public int PkidInventarioDetalle { get; set; }

    public int FkidInventarioAlma { get; set; }

    public string InventarioFolio { get; set; }

    public int FkidBienAlma { get; set; }

    public string BienClave { get; set; }

    public string BienDescripcion { get; set; }

    public string Modelo { get; set; }

    public string Serie { get; set; }

    public decimal? ValorActual { get; set; }

    public string ClaveBien { get; set; }

    public string DescripcionBien { get; set; }

    public string SerieCapturada { get; set; }

    public string UbicacionSistema { get; set; }

    public string UbicacionFisica { get; set; }

    public bool Localizado { get; set; }

    public bool TieneDiferencia { get; set; }

    public string Observaciones { get; set; }

    public bool Activo { get; set; }

    public DateTime FechaCreacion { get; set; }

    public int UsuarioCreacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public int? UsuarioModificacion { get; set; }
}