// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class VwInversione
{
    public int PkidInversion { get; set; }

    public string CuentaBan { get; set; }

    public string Instrumento { get; set; }

    public decimal Monto { get; set; }

    public DateOnly FechaInversion { get; set; }

    public DateOnly? FechaVencimiento { get; set; }

    public int CtCreatedBy { get; set; }

    public DateTime? CtCreatedDate { get; set; }

    public int? CtModifiedBy { get; set; }

    public DateTime? CtModifiedDate { get; set; }

    public bool CtLive { get; set; }

    public decimal Intereses { get; set; }

    public decimal Retiros { get; set; }

    public decimal? Saldo { get; set; }

    public int FkidInstrumento { get; set; }

    public int FkidCuentaBancaria { get; set; }
}