// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class VwNivel
{
    public int PkidNivel { get; set; }

    public string Clave { get; set; }

    public int? UniversoId { get; set; }

    public string UniversoDescripcion { get; set; }

    public decimal? ImpSdi { get; set; }

    public decimal? ImpImss15 { get; set; }

    public decimal? ImpImss16 { get; set; }

    public string ClaveNombre { get; set; }

    public bool Activo { get; set; }

    public int? UsuarioCreacion { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public int? UsuarioModificacion { get; set; }

    public DateTime? FechaModificacion { get; set; }
}