// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class VwNotificacionUsuario
{
    public long PkIdNotificacionDestino { get; set; }

    public long PkIdNotificacion { get; set; }

    public int? FkIdUsuarioOrigen { get; set; }

    public int FkIdUsuarioDestino { get; set; }

    public string Tipo { get; set; }

    public string Modulo { get; set; }

    public string SubModulo { get; set; }

    public string Evento { get; set; }

    public string Entidad { get; set; }

    public long? FkIdEntidad { get; set; }

    public string Titulo { get; set; }

    public string Mensaje { get; set; }

    public string Url { get; set; }

    public string JsonData { get; set; }

    public string Estado { get; set; }

    public int FkIdNotificacionEstado { get; set; }

    public DateTime? FechaLeido { get; set; }

    public DateTime? FechaAtendido { get; set; }

    public DateTime FechaNotificacion { get; set; }
}