// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class VwOperacionNomina
{
    public string Operacion { get; set; }

    public int Id { get; set; }

    public string Clave { get; set; }

    public string Persona { get; set; }

    public string Empleado { get; set; }

    public string Empresa { get; set; }

    public string Periodo { get; set; }

    public string Tipo { get; set; }

    public string Estatus { get; set; }

    public DateTime? Fecha { get; set; }

    public DateTime? FechaInicio { get; set; }

    public DateTime? FechaFin { get; set; }

    public decimal? Importe { get; set; }

    public decimal? Percepcion { get; set; }

    public decimal? Deduccion { get; set; }

    public decimal? Neto { get; set; }

    public string Documento { get; set; }

    public string Descripcion { get; set; }

    public string Comentario { get; set; }

    public string Observaciones { get; set; }

    public bool Activo { get; set; }
}