// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class VwOrdenCompraFromClasificacionBien
{
    public int PkidOrdenCompra { get; set; }

    public int FkidEmpresaSis { get; set; }

    public int? FkidAnioSis { get; set; }

    public string Requisicion { get; set; }

    public string Proveedor { get; set; }

    public string Justificacion { get; set; }

    public DateOnly FechaOrdenCompra { get; set; }

    public DateOnly? FechaVigencia { get; set; }

    public decimal? Solicitado { get; set; }

    public decimal? Recibido { get; set; }

    public decimal? Faltante { get; set; }

    public string Estado { get; set; }

    public string Numero { get; set; }

    public int? FkidCotizacionOrco { get; set; }

    public int FkidEstatusOrdenCompraOrco { get; set; }

    public int? Color { get; set; }

    public decimal? PrecioUnitario { get; set; }

    public decimal? Total { get; set; }
}