// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class VwPartidaGasto
{
    public int PkidPartidaGasto { get; set; }

    public int FkidPresupuestoProgramaPbr { get; set; }

    public int? FkidCapituloSis { get; set; }

    public int? FkidConceptoSis { get; set; }

    public int? FkidPartidaSis { get; set; }

    public string CapituloClave { get; set; }

    public string Descripcion { get; set; }

    public decimal MontoAnual { get; set; }

    public decimal? MontoModificado { get; set; }

    public int? FkidTipoGastoPres { get; set; }

    public bool Activo { get; set; }

    public DateTime FechaCreacion { get; set; }

    public int UsuarioCreacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public int? UsuarioModificacion { get; set; }

    public int? Anio { get; set; }

    public int? FkidProgramaPres { get; set; }

    public string ProgramaDescripcion { get; set; }

    public string CapituloDescripcion { get; set; }

    public string ConceptoDescripcion { get; set; }

    public string PartidaDescripcion { get; set; }

    public string TipoGastoDescripcion { get; set; }
}