// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class VwPersona
{
    public int PkidPersona { get; set; }

    public string Clave { get; set; }

    public string Nombre { get; set; }

    public string Paterno { get; set; }

    public string Materno { get; set; }

    public string NombreCompleto { get; set; }

    public string ClaveNombre { get; set; }

    public string Rfc { get; set; }

    public string Curp { get; set; }

    public string Puesto { get; set; }

    public decimal? SueldoBase { get; set; }

    public decimal? CompensacionGarantizada { get; set; }

    public int? EmpresaId { get; set; }

    public string EmpresaNombre { get; set; }

    public bool Activo { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public int UsuarioCreacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public int? UsuarioModificacion { get; set; }
}