// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class VwPersonaPension
{
    public int PkidPension { get; set; }

    public int FkidPersonaNom { get; set; }

    public string NombreBeneficiario { get; set; }

    public string Documento { get; set; }

    public DateOnly? FechaDocumento { get; set; }

    public decimal? Porcentaje { get; set; }

    public int? FkidTipoPensionNom { get; set; }

    public DateTime? FechaInicio { get; set; }

    public DateTime? FechaFin { get; set; }

    public string Banco { get; set; }

    public string CuentaBancaria { get; set; }

    public string Clabe { get; set; }

    public string FormaPago { get; set; }

    public int? FkidCuentaContableSis { get; set; }

    public int? UsuarioCreacion { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public int? UsuarioModificacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public bool Activo { get; set; }

    public string ClavePersona { get; set; }

    public string NombreCompleto { get; set; }

    public string Rfc { get; set; }

    public string Curp { get; set; }

    public string TipoPensionDescripcion { get; set; }

    public bool? TipoPensionActivo { get; set; }

    public string CuentaContable { get; set; }

    public string SubCuentaContable { get; set; }

    public string SubSubCuentaContable { get; set; }

    public string SubSubSubCuentaContable { get; set; }

    public string SubSubSubSubCuentaContable { get; set; }

    public string CuentaContableDescripcion { get; set; }

    public bool? CuentaContableActivo { get; set; }
}