// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class VwPersonaArea
{
    public int PkidPersonaArea { get; set; }

    public int PersonaId { get; set; }

    public string PersonaClaveNombre { get; set; }

    public int AreaId { get; set; }

    public string AreaClave { get; set; }

    public string AreaNombre { get; set; }

    public string AreaClaveNombre { get; set; }

    public bool IsAdscrito { get; set; }

    public bool? EsSolicitante { get; set; }

    public bool? EsAutorizador { get; set; }

    public int? EmpresaId { get; set; }

    public string EmpresaNombre { get; set; }

    public bool Activo { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public int UsuarioCreacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public int? UsuarioModificacion { get; set; }
}