// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class VwPeriodoActivo
{
    public int PkidPeriodoActivo { get; set; }

    public int EmpresaId { get; set; }

    public string EmpresaNombre { get; set; }

    public int PeriodoId { get; set; }

    public bool EstaCerrado { get; set; }

    public bool? EstaComprometido { get; set; }

    public bool? EstaDevengado { get; set; }

    public bool? EstaEjercido { get; set; }

    public bool Activo { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public int? UsuarioCreacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public int? UsuarioModificacion { get; set; }
}