// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class VwPrograma1
{
    public int PkidPrograma { get; set; }

    public string Clave { get; set; }

    public string Descripcion { get; set; }

    public string Objetivo { get; set; }

    public string ClaveNombre { get; set; }

    public int FkidUrPres { get; set; }

    public string Urclave { get; set; }

    public string Urdescripcion { get; set; }

    public string UrclaveNombre { get; set; }

    public int FkidGfPres { get; set; }

    public int? Gfclave { get; set; }

    public string Gfdescripcion { get; set; }

    public string GfclaveNombre { get; set; }

    public int FkidFnPres { get; set; }

    public int? Fnclave { get; set; }

    public string Fndescripcion { get; set; }

    public string FnclaveNombre { get; set; }

    public int FkidSfPres { get; set; }

    public int? Sfclave { get; set; }

    public string Sfdescripcion { get; set; }

    public string SfclaveNombre { get; set; }

    public int FkidActividadInstitucionalSis { get; set; }

    public string ActividadInstitucionalClave { get; set; }

    public string ActividadInstitucionalDescripcion { get; set; }

    public string ActividadInstitucionalClaveNombre { get; set; }

    public int? FkidEjePres { get; set; }

    public string EjeClave { get; set; }

    public string EjeDescripcion { get; set; }

    public string EjeClaveNombre { get; set; }

    public int? FkidSubEjePres { get; set; }

    public string SubEjeClave { get; set; }

    public string SubEjeDescripcion { get; set; }

    public string SubEjeClaveNombre { get; set; }

    public int? FkidSubSubEjePres { get; set; }

    public string SubSubEjeClave { get; set; }

    public string SubSubEjeDescripcion { get; set; }

    public string SubSubEjeClaveNombre { get; set; }

    public int? FkidFinalidadPres { get; set; }

    public string FinalidadClave { get; set; }

    public string FinalidadDescripcion { get; set; }

    public string FinalidadClaveNombre { get; set; }

    public int? FkidVertienteGastoPres { get; set; }

    public string VertienteGastoClave { get; set; }

    public string VertienteGastoDescripcion { get; set; }

    public string VertienteGastoClaveNombre { get; set; }

    public int? FkidResultadoPres { get; set; }

    public string ResultadoClave { get; set; }

    public string ResultadoDescripcion { get; set; }

    public string ResultadoClaveNombre { get; set; }

    public int? FkidSubresultadoPres { get; set; }

    public string SubresultadoClave { get; set; }

    public string SubresultadoDescripcion { get; set; }

    public string SubresultadoClaveNombre { get; set; }

    public int? FkidAnioSis { get; set; }

    public int? AnioClave { get; set; }

    public int? FkidSectorPres { get; set; }

    public string SectorClave { get; set; }

    public string SectorDescripcion { get; set; }

    public string SectorClaveNombre { get; set; }

    public int? FkidSubSectorPres { get; set; }

    public string SubSectorClave { get; set; }

    public string SubSectorDescripcion { get; set; }

    public string SubSectorClaveNombre { get; set; }

    public int? FkidTipoRecursoPres { get; set; }

    public string TipoRecursoClave { get; set; }

    public string TipoRecursoDescripcion { get; set; }

    public string TipoRecursoClaveNombre { get; set; }

    public int? FkidFuenteFinanciamientoPres { get; set; }

    public string FuenteFinanciamientoClave { get; set; }

    public string FuenteFinanciamientoDescripcion { get; set; }

    public string Ff { get; set; }

    public string Fg { get; set; }

    public string Fe { get; set; }

    public string Ad { get; set; }

    public string Ori { get; set; }

    public string FuenteFinanciamientoClaveNombre { get; set; }

    public int? FkidPpPres { get; set; }

    public string Ppclave { get; set; }

    public string Ppdescripcion { get; set; }

    public string PpclaveNombre { get; set; }

    public bool Activo { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public int UsuarioCreacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public int? UsuarioModificacion { get; set; }
}