// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class VwResguardo
{
    public int PkidResguardo { get; set; }

    public string Folio { get; set; }

    public int FkidEmpresaSis { get; set; }

    public string EmpresaNombre { get; set; }

    public int? FkidAreaSis { get; set; }

    public string AreaClave { get; set; }

    public string AreaNombre { get; set; }

    public int? FkidPersonaNom { get; set; }

    public string PersonaClave { get; set; }

    public string PersonaNombre { get; set; }

    public DateOnly FechaResguardo { get; set; }

    public string Observaciones { get; set; }

    public int? TotalBienes { get; set; }

    public decimal ValorActualResguardado { get; set; }

    public bool Activo { get; set; }

    public DateTime FechaCreacion { get; set; }

    public int UsuarioCreacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public int? UsuarioModificacion { get; set; }
}