// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class VwRequisicionPartidum
{
    public int PkidRequisicionPartida { get; set; }

    public int FkidEmpresaSis { get; set; }

    public int FkidRequisicionOrco { get; set; }

    public int FkidPartidaConta { get; set; }

    public decimal? Monto { get; set; }

    public string Observaciones { get; set; }

    public bool Activo { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public int UsuarioCreacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public int? UsuarioModificacion { get; set; }

    public string EmpresaNombre { get; set; }

    public string RequisicionDescripcion { get; set; }

    public DateTime? FechaRequisicion { get; set; }

    public decimal? RequisicionImporte { get; set; }

    public string PartidaClave { get; set; }

    public string PartidaDescripcion { get; set; }

    public string ClaveNombre { get; set; }
}