// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class VwResguardoDetalle
{
    public int PkidResguardoDetalle { get; set; }

    public int FkidResguardoAlma { get; set; }

    public string Folio { get; set; }

    public int FkidEmpresaSis { get; set; }

    public int? FkidAreaSis { get; set; }

    public string AreaNombre { get; set; }

    public int? FkidPersonaNom { get; set; }

    public string PersonaNombre { get; set; }

    public int FkidBienAlma { get; set; }

    public string BienClave { get; set; }

    public string BienClaveAnterior { get; set; }

    public string BienDescripcion { get; set; }

    public string Modelo { get; set; }

    public string Serie { get; set; }

    public string Factura { get; set; }

    public decimal? Costo { get; set; }

    public decimal? ValorActual { get; set; }

    public int FkidTipoBienAlma { get; set; }

    public string TipoBienCodigoClave { get; set; }

    public string TipoBienDescripcion { get; set; }

    public int Consecutivo { get; set; }

    public DateTime FechaAsignacion { get; set; }

    public DateTime? FechaLiberacion { get; set; }

    public bool ImprimeEtiqueta { get; set; }

    public int? FkidEstadoBienAlma { get; set; }

    public string EstadoBienDescripcion { get; set; }

    public string Observaciones { get; set; }

    public bool Activo { get; set; }

    public DateTime FechaCreacion { get; set; }

    public int UsuarioCreacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public int? UsuarioModificacion { get; set; }
}