// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class VwReporteBienesProgramaAnual
{
    public int PkidTipoBien { get; set; }

    public string NombreBien { get; set; }

    public string ClaveBien { get; set; }

    public string UnidadMedida { get; set; }

    public int TotalAreasSolicitantes { get; set; }

    public decimal CantidadTotalSolicitada { get; set; }

    public int ProveedoresQueCotizaron { get; set; }

    public int TotalCotizacionesRecibidas { get; set; }

    public decimal? PrecioMinimo { get; set; }

    public decimal? PrecioMaximo { get; set; }

    public decimal? PrecioPromedio { get; set; }

    public DateTime? UltimaCotizacion { get; set; }

    public DateTime? UltimaActualizacionBien { get; set; }

    public string Estatus { get; set; }
}