// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class VwRequisicion
{
    public int PkidRequisicion { get; set; }

    public int FkidEmpresaSis { get; set; }

    public int FkidPersonaNom { get; set; }

    public int FkidAreaSis { get; set; }

    public string Descripcion { get; set; }

    public string Observaciones { get; set; }

    public DateTime FechaRequisicion { get; set; }

    public bool Servicio { get; set; }

    public string FlFoto { get; set; }

    public int? FkidProyectoOrco { get; set; }

    public DateTime? FechaRequiereInicio { get; set; }

    public DateTime? FechaRequiereFin { get; set; }

    public int? FkidProgramaPres { get; set; }

    public decimal? Importe { get; set; }

    public int? FkidJefeAlmacenNom { get; set; }

    public int? FkidSuficienciaPres { get; set; }

    public int? FkidSupervisoNom { get; set; }

    public int? FkidAutorizoNom { get; set; }

    public int? FkidPsolicitaNom { get; set; }

    public int? FkidPjefeAlmacenNom { get; set; }

    public int? FkidPsuficienciaNom { get; set; }

    public int? FkidPsupervisoNom { get; set; }

    public int? FkidPautorizoNom { get; set; }

    public int? FkidFuenteFinanciamientoPres { get; set; }

    public int? FkidAnioSis { get; set; }

    public int? FkidTipoGastoPres { get; set; }

    public int? FkidDigitoIdentificadorPres { get; set; }

    public int? FkidDestinoGastoPres { get; set; }

    public int? FkidEgresoAutorizadoPres { get; set; }

    public string Oficio { get; set; }

    public DateTime? FechaOficio { get; set; }

    public bool? CompraDirecta { get; set; }

    public bool Activo { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public int UsuarioCreacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public int? UsuarioModificacion { get; set; }

    public string EmpresaNombre { get; set; }

    public string EmpresaRfc { get; set; }

    public int? AnioClave { get; set; }

    public string AreaNombre { get; set; }

    public string AreaClave { get; set; }

    public string SolicitanteNombre { get; set; }

    public string SolicitantePaterno { get; set; }

    public string SolicitanteMaterno { get; set; }

    public string SolicitanteCompleto { get; set; }

    public string ProyectoDescripcion { get; set; }

    public string ProgramaClave { get; set; }

    public string ProgramaDescripcion { get; set; }

    public string FuenteFinanciamientoClave { get; set; }

    public string FuenteFinanciamientoDescripcion { get; set; }

    public int? TipoGastoClave { get; set; }

    public string TipoGastoDescripcion { get; set; }

    public string DigitoIdentificadorClave { get; set; }

    public string DigitoIdentificadorDescripcion { get; set; }

    public string DestinoGastoClave { get; set; }

    public string DestinoGastoDescripcion { get; set; }

    public string SuficienciaDescripcion { get; set; }

    public string EgresoAutorizadoDescripcion { get; set; }

    public DateOnly? EgresoAutorizadoFecha { get; set; }

    public string JefeAlmacenNombre { get; set; }

    public string JefeAlmacenPaterno { get; set; }

    public string JefeAlmacenMaterno { get; set; }

    public string JefeAlmacenCompleto { get; set; }

    public string SupervisoNombre { get; set; }

    public string SupervisoPaterno { get; set; }

    public string SupervisoMaterno { get; set; }

    public string SupervisoCompleto { get; set; }

    public string AutorizoNombre { get; set; }

    public string AutorizoPaterno { get; set; }

    public string AutorizoMaterno { get; set; }

    public string AutorizoCompleto { get; set; }

    public string PsolicitaNombre { get; set; }

    public string PsolicitaPaterno { get; set; }

    public string PsolicitaMaterno { get; set; }

    public string PsolicitaCompleto { get; set; }

    public string PjefeAlmacenNombre { get; set; }

    public string PjefeAlmacenPaterno { get; set; }

    public string PjefeAlmacenMaterno { get; set; }

    public string PjefeAlmacenCompleto { get; set; }

    public string PsuficienciaNombre { get; set; }

    public string PsuficienciaPaterno { get; set; }

    public string PsuficienciaMaterno { get; set; }

    public string PsuficienciaCompleto { get; set; }

    public string PsupervisoNombre { get; set; }

    public string PsupervisoPaterno { get; set; }

    public string PsupervisoMaterno { get; set; }

    public string PsupervisoCompleto { get; set; }

    public string PautorizoNombre { get; set; }

    public string PautorizoPaterno { get; set; }

    public string PautorizoMaterno { get; set; }

    public string PautorizoCompleto { get; set; }

    public string ClaveNombre { get; set; }
}