// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class VwResumenPeriodo
{
    public int? EmpresaId { get; set; }

    public string EmpresaNombre { get; set; }

    public int PeriodoId { get; set; }

    public long? TotalMovimientos { get; set; }

    public decimal? TotalPercepcion { get; set; }

    public decimal? TotalDeduccion { get; set; }

    public decimal? TotalAportacion { get; set; }

    public decimal? TotalNeto { get; set; }
}