// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class VwSolicitudSalidum
{
    public int PkidSolicitudSalida { get; set; }

    public int FkidEmpresaSis { get; set; }

    public int? FkidAnioSis { get; set; }

    public int? AnioClave { get; set; }

    public string EmpresaNombre { get; set; }

    public int? FkidAreaSolicitaSis { get; set; }

    public string AreaSolicitaNombre { get; set; }

    public int? FkidAreaEntregaSis { get; set; }

    public string AreaEntregaNombre { get; set; }

    public int FkidEstatusSolicitudSalidaAlma { get; set; }

    public string EstatusDescripcion { get; set; }

    public string EstatusColor { get; set; }

    public string Folio { get; set; }

    public DateOnly FechaSolicitud { get; set; }

    public DateOnly? FechaRequerida { get; set; }

    public string Solicitante { get; set; }

    public string Justificacion { get; set; }

    public string Observaciones { get; set; }

    public bool Autorizado { get; set; }

    public DateTime? FechaAutorizacion { get; set; }

    public int? UsuarioAutorizacion { get; set; }

    public bool Activo { get; set; }

    public DateTime FechaCreacion { get; set; }

    public int UsuarioCreacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public int? UsuarioModificacion { get; set; }

    public int? FkidPolizaConta { get; set; }
}
