// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class VwSubFuncion
{
    public int PkidSf { get; set; }

    public int SubFuncionClave { get; set; }

    public string SubFuncionDescripcion { get; set; }

    public int FkidFnPres { get; set; }

    public bool Activo { get; set; }

    public int? FuncionClave { get; set; }

    public string FuncionDescripcion { get; set; }

    public string SubFuncionClaveNombre { get; set; }

    public string FuncionClaveNombre { get; set; }
}