// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class VwVinculacionProgramaPed
{
    public int PkidVinculacionPed { get; set; }

    public int FkidProgramaPresupuestarioPbr { get; set; }

    public int FkidObjetivoPedPbr { get; set; }

    public string LineaAccion { get; set; }

    public string Contribucion { get; set; }

    public DateTime FechaCreacion { get; set; }

    public int? FkidProgramaPres { get; set; }

    public string ProgramaDescripcion { get; set; }

    public string ObjetivoPedcodigo { get; set; }

    public string ObjetivoPeddescripcion { get; set; }
}