// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class VwVinculacionProgramaOd
{
    public int PkidVinculacionOds { get; set; }

    public int FkidProgramaPresupuestarioPbr { get; set; }

    public int FkidObjetivoOdsPbr { get; set; }

    public int? FkidMetaOdsPbr { get; set; }

    public string Contribucion { get; set; }

    public DateTime FechaCreacion { get; set; }

    public int? FkidProgramaPres { get; set; }

    public string ProgramaDescripcion { get; set; }

    public int? ObjetivoOdsnumero { get; set; }

    public string ObjetivoOdsnombre { get; set; }

    public string MetaOdsnumero { get; set; }

    public string MetaOdsdescripcion { get; set; }
}