// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Infraestructure.Models;

public partial class VwWorkflowEstado
{
    public int PkidWorkflowEstado { get; set; }

    public int FkidWorkflowTemplatePbr { get; set; }

    public string Codigo { get; set; }

    public string Nombre { get; set; }

    public int Orden { get; set; }

    public bool EsInicial { get; set; }

    public bool EsFinal { get; set; }

    public bool Activo { get; set; }

    public string WorkflowCodigo { get; set; }

    public string WorkflowNombre { get; set; }
}