// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Domain.Entities;

public partial class AspNetClaim
{
    public int Id { get; set; }

    public int? ClaimTypeId { get; set; }

    public string Name { get; set; }

    public string Group { get; set; }

    public string RoleId { get; set; }

    public string TokenFormat { get; set; }

    public DateTime Created { get; set; }

    public string SubGroup { get; set; }

    public string Code { get; set; }

    public string Description { get; set; }

    public string Values { get; set; }

    public int ReferenceId { get; set; }

    public virtual ICollection<AspNetClaimValue> AspNetClaimValues { get; set; } = new List<AspNetClaimValue>();

    public virtual AspNetClaimType ClaimType { get; set; }

    public virtual AspNetRole Role { get; set; }
}