// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Domain.Entities;

public partial class AspNetClaimValue
{
    public int Id { get; set; }

    public int? ClaimId { get; set; }

    public string Value { get; set; }

    public DateTime Created { get; set; }

    public virtual AspNetClaim Claim { get; set; }
}