// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Domain.Entities;

public partial class CatTipoSucursal
{
    public int PkidTipoSucursal { get; set; }

    public string Descripcion { get; set; }

    public bool Activo { get; set; }

    public virtual ICollection<Sucursal> Sucursals { get; set; } = new List<Sucursal>();
}