// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Domain.Entities;

public partial class EmpresaEstado
{
    public int FkidEmpresaSis { get; set; }

    public int FkidEstadoSis { get; set; }

    public DateOnly? FechaApertura { get; set; }

    public bool EsOficinaPrincipal { get; set; }

    public bool Activo { get; set; }

    public virtual Empresa FkidEmpresaSisNavigation { get; set; }

    public virtual Estado FkidEstadoSisNavigation { get; set; }
}