// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Domain.Entities;

public partial class Menu
{
    public int PkidMenu { get; set; }

    public string Nombre { get; set; }

    public int Tipo { get; set; }

    public int? FkidMenuSis { get; set; }

    public string LegacyName { get; set; }

    public string Ruta { get; set; }

    public string ImageUrl { get; set; }

    public string Lenguaje { get; set; }

    public int? Orden { get; set; }

    public bool Activo { get; set; }

    public int? CreatedByOperatorId { get; set; }

    public DateTime CreatedDateTime { get; set; }

    public int? ModifiedByOperatorId { get; set; }

    public DateTime? ModifiedDateTime { get; set; }

    public virtual Menu FkidMenuSisNavigation { get; set; }

    public virtual ICollection<Menu> InverseFkidMenuSisNavigation { get; set; } = new List<Menu>();

    public virtual ICollection<MenuRole> MenuRoles { get; set; } = new List<MenuRole>();
}