// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Domain.Entities;

public partial class Paise
{
    public int PkidPais { get; set; }

    public string Nombre { get; set; }

    public virtual ICollection<Estado> Estados { get; set; } = new List<Estado>();
}