// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Domain.Entities;

public partial class PerfilUsuario
{
    public int FkidUsuarioSis { get; set; }

    public byte[] Fotografia { get; set; }

    public string ContentType { get; set; }

    public string FileName { get; set; }

    public string FileExtension { get; set; }

    public bool Activo { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public int UsuarioCreacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public int? UsuarioModificacion { get; set; }

    public virtual Usuario FkidUsuarioSisNavigation { get; set; }
}