// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Domain.Entities;

public partial class SystemLog
{
    public int PkidSystemLog { get; set; }

    public int FkidOrigenLogMessageSis { get; set; }

    public DateTime? Date { get; set; }

    public string Type { get; set; }

    public string ProgName { get; set; }

    public string EmployeeNo { get; set; }

    public string Category { get; set; }

    public string Ipclient { get; set; }

    public string HostName { get; set; }

    public string Thread { get; set; }

    public string Level { get; set; }

    public string Logger { get; set; }

    public string Message { get; set; }

    public string Exception { get; set; }

    public string Context { get; set; }

    public string MethodName { get; set; }

    public string Parameters { get; set; }

    public int? ExecutionTime { get; set; }

    public virtual OrigenLogMessage FkidOrigenLogMessageSisNavigation { get; set; }
}