// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Domain.Entities;

public partial class SystemParamCatalog
{
    public int PkidSystemParamCatalog { get; set; }

    public string Code { get; set; }

    public string Name { get; set; }

    public bool Activo { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public int UsuarioCreacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public int? UsuarioModificacion { get; set; }

    public virtual ICollection<SystemParamValue> SystemParamValues { get; set; } = new List<SystemParamValue>();
}