// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Domain.Entities;

public partial class SystemParamCatalog
{
    public int PkIdSystemParamCatalog { get; set; }

    public string Code { get; set; }

    public string Name { get; set; }

    public int CtCreateBy { get; set; }

    public DateTime CtCreateDate { get; set; }

    public int? CtModifiedBy { get; set; }

    public DateTime? CtModifiedDate { get; set; }

    public bool? CtLive { get; set; }

    public virtual ICollection<SystemParamValue> SystemParamValues { get; set; } = new List<SystemParamValue>();
}