// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Domain.Entities;

public partial class SystemParamValue
{
    public int PkIdSystemParamValue { get; set; }

    public int FkIdSystemParamCatalogSis { get; set; }

    public string Value { get; set; }

    public string Descripcion { get; set; }

    public int CtCreateBy { get; set; }

    public DateTime CtCreateDate { get; set; }

    public int? CtModifiedBy { get; set; }

    public DateTime? CtModifiedDate { get; set; }

    public bool? CtLive { get; set; }

    public virtual SystemParamCatalog FkIdSystemParamCatalogSisNavigation { get; set; }
}