// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Domain.Entities;

public partial class UsuarioDepartamento
{
    public int FkidUsuarioSis { get; set; }

    public int FkidDepartamentoSis { get; set; }

    public bool EsJefe { get; set; }

    public DateTime FechaAsignacion { get; set; }

    public DateTime? FechaFinAsignacion { get; set; }

    public bool Activo { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public int UsuarioCreacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public int? UsuarioModificacion { get; set; }

    public virtual Departamento FkidDepartamentoSisNavigation { get; set; }

    public virtual Usuario FkidUsuarioSisNavigation { get; set; }
}