// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Domain.Entities;

public partial class VwEmpresaDepartamanto
{
    public int PkidEmpresa { get; set; }

    public string EmpresaNombre { get; set; }

    public string Rfc { get; set; }

    public int PkidDepartamento { get; set; }

    public string DepartamentoNombre { get; set; }

    public bool DepartamentoActivo { get; set; }

    public bool EmpresaActivo { get; set; }
}