// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Domain.Entities;

public partial class VwUsuarioEmpresa
{
    public int PkIdUsuario { get; set; }

    public string AspNetUserId { get; set; }

    public int IdEmpresa { get; set; }

    public string NombreCompleto { get; set; }

    public string Nombre { get; set; }

    public string ApellidoPaterno { get; set; }

    public string ApellidoMaterno { get; set; }

    public string Iniciales { get; set; }

    public string PayrollId { get; set; }

    public string CodigoPostalUsuario { get; set; }

    public string TelefonoUsuario { get; set; }

    public string Direccion1 { get; set; }

    public string Direccion2 { get; set; }

    public string Email { get; set; }

    public string NumeroSocial { get; set; }

    public string Gafete { get; set; }

    public string SexoDescripcion { get; set; }

    public bool Sexo { get; set; }

    public DateOnly? FechaIngreso { get; set; }

    public string FechaIngresoFormat { get; set; }

    public int? AntigüedadAños { get; set; }

    public int? IdIdiomaPreferido { get; set; }

    public string IdiomaPreferido { get; set; }

    public int? IdMonedaPreferida { get; set; }

    public string MonedaPreferida { get; set; }

    public string SimboloMoneda { get; set; }

    public bool EsAdministrador { get; set; }

    public bool UsuarioActivo { get; set; }

    public DateTime? UsuarioFechaCreacion { get; set; }

    public string UsuarioFechaCreacionFormat { get; set; }

    public int UsuarioCreadorId { get; set; }

    public int PkidEmpresa { get; set; }

    public string NombreEmpresa { get; set; }

    public string RfcEmpresa { get; set; }

    public string RazonSocialEmpresa { get; set; }

    public string GiroEmpresa { get; set; }

    public int IdMonedaBaseEmpresa { get; set; }

    public string MonedaBaseEmpresa { get; set; }

    public string SimboloMonedaBase { get; set; }

    public bool EmpresaActiva { get; set; }

    public DateTime? EmpresaFechaCreacion { get; set; }

    public string ListaDepartamentos { get; set; }

    public int? TotalDepartamentos { get; set; }

    public int EsJefeAlgunDepartamento { get; set; }

    public string DepartamentosComoJefe { get; set; }

    public string ListaSucursales { get; set; }

    public int TotalSucursales { get; set; }

    public string SucursalMatrizAsignada { get; set; }

    public string RolPrincipal { get; set; }

    public string CoberturaSucursales { get; set; }

    public int? UltimoAcceso { get; set; }

    public string NumeroEmpleado { get; set; }

    public string InicialesNombre { get; set; }
}