// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EG.Domain.Entities;

public partial class VwUsuarioSucursal
{
    public int PkIdUsuario { get; set; }

    public int IdEmpresa { get; set; }

    public string NombreEmpresa { get; set; }

    public string RfcEmpresa { get; set; }

    public string NombreCompleto { get; set; }

    public string NombreUsuario { get; set; }

    public string ApellidoPaterno { get; set; }

    public string ApellidoMaterno { get; set; }

    public string Iniciales { get; set; }

    public string PayrollId { get; set; }

    public string CodigoPostalUsuario { get; set; }

    public string TelefonoUsuario { get; set; }

    public string Direccion1 { get; set; }

    public string Direccion2 { get; set; }

    public string Email { get; set; }

    public string NumeroSocial { get; set; }

    public string Gafete { get; set; }

    public string SexoDescripcion { get; set; }

    public bool Sexo { get; set; }

    public bool UsuarioActivo { get; set; }

    public DateTime? UsuarioFechaCreacion { get; set; }

    public int UsuarioCreadorId { get; set; }
}