// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EG.Dommain.DTOs.Responses;
public partial class LoginResult
{
    public bool? Resultado { get; set; }
}
