<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <OverrideHtmlAssetPlaceholders>true</OverrideHtmlAssetPlaceholders>
    <PublishTrimmed>true</PublishTrimmed>
    <BlazorWebAssemblyEnableLinking>true</BlazorWebAssemblyEnableLinking>
    <RunAOTCompilation>false</RunAOTCompilation>
    <InvariantGlobalization>false</InvariantGlobalization>
    <BlazorWebAssemblyLoadAllGlobalizationData>true</BlazorWebAssemblyLoadAllGlobalizationData>
    <ServerGarbageCollection>false</ServerGarbageCollection>
    <WasmInitialHeapSize>67108864</WasmInitialHeapSize>
  </PropertyGroup>

  <ItemGroup>
    <RuntimeHostConfigurationOption Include="System.GC.Server" Value="false" />
    <RuntimeHostConfigurationOption Include="System.Globalization.Invariant" Value="false" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Services\Almacen\**" />
    <Content Remove="Services\Almacen\**" />
    <EmbeddedResource Remove="Services\Almacen\**" />
    <None Remove="Services\Almacen\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="10.0.9" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.9" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.9" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.9" />
    <PackageReference Include="MiniExcel" Version="1.45.0" />
    <PackageReference Include="MudBlazor" Version="9.6.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\BackEnd\EG.Common\EG.Common.csproj" />
    <ProjectReference Include="..\..\BackEnd\EG.Domain\EG.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Models\ConteoCiclico\" />
    <Folder Include="Models\DTO\Configuration\" />
    <Folder Include="Pages\Modules\GRP\Adquisiciones\Contratos\" />
    <Folder Include="Pages\Modules\GRP\Presupuesto\Tesoreria\CuentasXCobrar\ModificadoIngreso\" />
    <Folder Include="Pages\Modules\PBR\" />
    <Folder Include="Pages\Platform\" />
    <Folder Include="Pages\Platform\Sistema\" />
    <Folder Include="Pages\Modules\GRP\Configuration\Catalogos\Adquisicion\" />
    <Folder Include="Pages\Modules\GRP\Configuration\Catalogos\Presupuestales\" />
    <Folder Include="Pages\Modules\GRP\Patrimonio\" />
    <Folder Include="Pages\Modules\GRP\Contabilidad\" />
    <Folder Include="Pages\Modules\GRP\Presupuesto\Egreso\PresupuestoModificado\" />
    <Folder Include="Pages\Modules\GRP\Presupuesto\Egreso\PresupuestoComprometido\" />
    <Folder Include="Pages\Modules\GRP\Presupuesto\Egreso\Planeacion\" />
    <Folder Include="Pages\Modules\GRP\Presupuesto\Tesoreria\CuentasXPagar\" />
    <Folder Include="Services\ConteoCiclico\" />
  </ItemGroup>

</Project>
