CREATE DATABASE [GestionEmpresarial]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'GestionEmpresarial', FILENAME = N'C:\Desarrollo\Desarrollo\BD_RUN\GestionEmpresarial.mdf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'GestionEmpresarial_log', FILENAME = N'C:\Desarrollo\Desarrollo\BD_RUN\GestionEmpresarial_log.ldf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 WITH LEDGER = OFF
GO
ALTER DATABASE [GestionEmpresarial] MODIFY FILEGROUP [PRIMARY] AUTOGROW_ALL_FILES
GO
ALTER DATABASE [GestionEmpresarial] SET COMPATIBILITY_LEVEL = 160
GO
ALTER DATABASE [GestionEmpresarial] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [GestionEmpresarial] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [GestionEmpresarial] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [GestionEmpresarial] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [GestionEmpresarial] SET ARITHABORT OFF 
GO
ALTER DATABASE [GestionEmpresarial] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [GestionEmpresarial] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [GestionEmpresarial] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
ALTER DATABASE [GestionEmpresarial] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [GestionEmpresarial] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [GestionEmpresarial] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [GestionEmpresarial] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [GestionEmpresarial] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [GestionEmpresarial] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [GestionEmpresarial] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [GestionEmpresarial] SET  DISABLE_BROKER 
GO
ALTER DATABASE [GestionEmpresarial] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [GestionEmpresarial] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [GestionEmpresarial] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [GestionEmpresarial] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [GestionEmpresarial] SET  READ_WRITE 
GO
ALTER DATABASE [GestionEmpresarial] SET RECOVERY FULL 
GO
ALTER DATABASE [GestionEmpresarial] SET  MULTI_USER 
GO
ALTER DATABASE [GestionEmpresarial] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [GestionEmpresarial] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [GestionEmpresarial] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [GestionEmpresarial] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
USE [GestionEmpresarial]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [GestionEmpresarial] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
